ASTRO-1207
RocketCommunicationsInc/astro-components pull request #100
Opened 2021-03-17 13:30 UTC by nortonprojects

https://rocketcom.atlassian.net/browse/ASTRO-1207

2021-03-17 13:33 UTC, nortonprojects commented on static/css/astro.core.css
> +
Is there any particular reason we're storing this file in the repo instead of only generating it during builds?

2021-03-17 15:23 UTC, dmcalester commented on static/css/astro.core.css
> +
We do need a way to offer the compiled CSS as something a customer can just download without build for a couple of reasons, but the compiled CSS in the repo is not the best solution.

We have an effort this PI to move improve how we handle static CSS and its relation to the component library. I would say removing the compiled CSS from the repo, but finding a place to host the rendered CSS for those users who need it is a valuable effort.

2021-03-17 16:46 UTC, amalyah requested changes
- See comments. Also looks like there are some merge conflicts.
- Smaller Invalid sample needs to be updated to match new error styling.
- Notification message about errors feels really out of place where it is in the samples. Could it be at the bottom or in its own section with invalid examples?
- We don't need to show a sample, but would a developer be able to add error text to a group of checkboxes/push buttons/switches using the current code? (Does it have to be tied to input and select elements or can it stand on its own?)

2021-03-17 16:46 UTC, amalyah commented on src/css/core/forms.css
> +  background-image: url("data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20128%20128%22%3E%0A%20%20%3Cpath%20fill%3D%22%23FF3030%22%20fill-rule%3D%
What is this aspect? Is there a reason that we're not making this using CSS?

2021-03-17 16:46 UTC, amalyah commented on src/css/core/forms.css
> +  font-size: var(--fontSizeMD);
Would it be possible to use terminology closer to what design is using? So like Body 2? MD can mean a lot of things to me and I also think this is the smallest of the body text sizes?

2021-03-17 16:46 UTC, amalyah commented on src/css/core/forms.css
> +.rux-error-text.rux-error-text--right {
This element can be removed since we are no longer using right-aligned text for character count help or error text.

2021-03-17 16:46 UTC, amalyah commented on src/css/core/forms.css
> +.rux-error-text.rux-error-text--center {
We currently have no use case for center-aligned error text and don't intend to create one at this point.

2021-03-17 16:46 UTC, amalyah commented on src/css/core/forms.css
> +  background-image: url("data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20128%20128%22%3E%0A%20%20%3Cpath%20fill%3D%22%23FF3030%22%20fill-rule%3D%
Is this the icon?

2021-03-17 16:46 UTC, amalyah commented on src/css/core/forms.css
> +.rux-form-field .rux-error-text.rux-error-text--right {
I don't believe we need this any more now that character count errors have been changed to left-aligned.

2021-03-17 16:46 UTC, amalyah commented on src/css/documentation/input-fields-README.md
> +  <span class="help">Help Text</span>
See review comments in the Help Text PR.

2021-03-17 16:46 UTC, amalyah commented on stories/rux-form-elements.stories.js
> +            placeholder="Enter Search Term"
Enter search term

2021-03-17 16:46 UTC, amalyah commented on stories/rux-form-elements.stories.js
> +            placeholder="Enter a Number between 0 and 10"
Enter a number

2021-03-17 16:46 UTC, amalyah commented on stories/rux-form-elements.stories.js
> +          <span class="rux-error-text rux-error-text--right">Error text right</span>
Don't need a right-aligned version any more. Change to left-aligned.

2021-03-17 16:46 UTC, amalyah commented on stories/rux-form-elements.stories.js
> +          <option value="">Select an Option</option>
Select an option

2021-03-17 16:46 UTC, amalyah commented on stories/rux-form-elements.stories.js
> +          <optgroup label="Group One">
Group one

2021-03-17 16:46 UTC, amalyah commented on stories/rux-form-elements.stories.js
> +          <optgroup label="Group Two">
Group two

2021-03-17 16:46 UTC, amalyah commented on stories/rux-form-elements.stories.js
> +          <label for="input__search">Invalid search</label>
This is missing error text.

2021-03-17 16:46 UTC, amalyah commented on stories/rux-form-elements.stories.js
>            <label for="input__invalid">Invalid</label>
Missing error text and is missing updated field styling.

2021-03-17 16:46 UTC, amalyah commented on stories/rux-form-elements.stories.js
> +          <p>There were 2 errors found. Please complete all required fields.</p>
Anything with the red text needs to be bold.

2021-03-17 16:46 UTC, amalyah commented on stories/rux-form-elements.stories.js
> +          <p>There were 2 errors found. Please complete all required fields.</p>
The spacing between the left edge, the icon, and the text does not match the designs. If nothing else, please increase space between the icon and the text.

2021-03-17 16:46 UTC, amalyah commented on stories/rux-form-elements.stories.js
> +        <label>Invalid</label>
Please add error text example to this sample.

2021-03-17 16:48 UTC, dmcalester commented on src/css/core/forms.css
> +  font-size: var(--fontSizeMD);
This is out of scope for this effort.

2021-03-17 16:55 UTC, dmcalester commented on src/css/core/forms.css
> +  background-image: url("data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20128%20128%22%3E%0A%20%20%3Cpath%20fill%3D%22%23FF3030%22%20fill-rule%3D%
It’s a Base64 encapsulates an SVG image. There are pros and cons to this in terms of overall size, caching etc … but it’s the general approach for handling intrinsically linked SVGs with their associated CSS element

https://codepen.io/tigt/post/optimizing-svgs-in-data-uris

2021-03-17 16:55 UTC, dmcalester commented on src/css/core/forms.css
> +  background-image: url("data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20128%20128%22%3E%0A%20%20%3Cpath%20fill%3D%22%23FF3030%22%20fill-rule%3D%
Yes

2021-03-17 18:25 UTC, nortonprojects commented on src/css/core/forms.css
> +  background-image: url("data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20128%20128%22%3E%0A%20%20%3Cpath%20fill%3D%22%23FF3030%22%20fill-rule%3D%
I just took this from the existing warning icon, if there's a better way I'd be all for it

2021-03-17 18:32 UTC, nortonprojects commented
> * See comments. Also looks like there are some merge conflicts.
> * Smaller Invalid sample needs to be updated to match new error styling.
> * Notification message about errors feels really out of place where it is in the samples. Could it be at the bottom or in its own section with invalid examples?
> * We don't need to show a sample, but would a developer be able to add error text to a group of checkboxes/push buttons/switches using the current code? (Does it have to be tied to input and select elements or can it stand on its own?)

I've added it similarly to the help text, where it ought to be able to be atomically added. It might be a good idea to have some sort of sample form which uses the validation/help elements without them being tied to the input story, especially with the notification message.

2021-03-17 22:03 UTC, cskerbo approved these changes

2021-03-17 22:04 UTC, dmcalester requested changes
Please remove the invalid form banner from the input text story for now.

2021-03-17 22:04 UTC, dmcalester commented on stories/rux-form-elements.stories.js
> +      <div class="rux-form__invalid">
Please remove this for now.

2021-03-22 22:25 UTC, dmcalester approved these changes

2021-03-23 14:53 UTC, dmcalester commented
@nortonprojects does this need a re-review or can it be merged in to next?

2021-03-24 17:04 UTC, nortonprojects commented
@cskerbo @dmcalester  I rebased everything (in here and 1205), just want to verify I didn't break anything in the process

2021-03-24 17:18 UTC, dmcalester commented
@nortonprojects a brief review of several components they all appear to be working. FWIW the Details link on the final check should load up an ephemeral preview link https://deploy-preview-100--astro-components.netlify.app/?path=/story/astro-uxds-welcome--start-here

2021-03-24 17:18 UTC, dmcalester approved these changes

2021-03-24 18:18 UTC, amalyah requested changes
- Invalid input fields (small and large) still have an in-field error icon that needs to be removed.
- Select menu invalid state is missing the error icon before the error text.

2021-03-24 22:38 UTC, merged