Astro 1111 login component
RocketCommunicationsInc/astro-components pull request #103
Opened 2021-03-18 20:08 UTC by Cheshire89

https://rocketcom.atlassian.net/browse/ASTRO-1111
Basic login component with main functionality
DId best I could with designs ... considering they keep on changing

2021-03-18 22:24 UTC, cskerbo requested changes
When typing in either of the input fields, the login component forces fullscreen in the Storybook - is this intentional?

It also seemed to bounce back and forth between default and fullscreen on each key press.

2021-03-18 22:24 UTC, cskerbo commented on src/components/rux-login/rux-login.js
> +                  <label for="pass">Password ${this.passwordVisible}</label>
Should `${this.passwordVisible}` actually be inside the label?

![Screen Shot 2021-03-18 at 3 19 13 PM](https://user-images.githubusercontent.com/54558554/111705215-9a4ac880-87fd-11eb-9c61-bc51de2a6666.png)

2021-03-19 14:39 UTC, amalyah commented
FYI @Design-Kat this is up for review.

2021-03-19 14:58 UTC, Cheshire89 commented on src/components/rux-login/rux-login.js
> +                  <label for="pass">Password ${this.passwordVisible}</label>
Oops ... as for the screen view changing ... I've had it once but thought I've pressed something instead of it being a bug

2021-03-19 16:24 UTC, Cheshire89 commented
@tyvanleuven you're not in the list may you'll get a memo this way ? Need your review here as well

2021-03-19 21:16 UTC, Design-Kat commented on src/components/rux-login/rux-login.js
> +                  <label for="pass">Password ${this.passwordVisible}</label>
I am still seeing this issue in Safari, btw.

2021-03-19 21:17 UTC, Design-Kat commented on src/components/rux-login/rux-login.js
> +                  id="username"
To match our documentation, we should use "Email" in the UI for display, rather than Username.

2021-03-19 21:20 UTC, Design-Kat commented on src/components/rux-login/rux-login.js
> +                  SSO Enabled
In Safari I am seeing the "SSO Enabled" w/ lock underneath the login, that line should only display when the login is being designed for SSO entry. The Lock icon should also display as Primary Blue, rather than white.

2021-03-19 21:21 UTC, Design-Kat commented on src/components/rux-login/rux-login.js
> +                  <rux-icon
I'm seeing this icon display as 15px wide, the design has it a bit bigger (so that it fits in a square box that is 24px wide).

2021-03-19 21:24 UTC, Design-Kat requested changes
Added a few comments. Please let me know if you have any questions! (Ty can also speak to the visuals.)

2021-03-19 21:47 UTC, amalyah requested changes
- My largest concern is that I think this is supposed to be called Sign In instead of Login across Astro.
- @Design-Kat Is the SSO enabled part supposed to be a link? I thought they were two different examples altogether.
- SSO text and its icon is 1 rem in the design.
- I agree with the previous comment that the false/true part next to the Password label should be removed for publishing.

2021-03-19 21:47 UTC, amalyah commented on src/components/rux-login/README.md
> +# Login
I believe this component was actually called Sign In in the end. Would need to change the various file titles and function names as well for proper reference. Has that been changed @Design-Kat ?

2021-03-19 21:47 UTC, amalyah commented on src/components/rux-login/README.md
> +Login enables a user to pass a user name and a password to the backend for authentication verification
Login > Sign In

verification > verification.

2021-03-19 21:47 UTC, amalyah commented on src/components/rux-login/package.json
> +  "description": "Astro Web Component for login",
login > Sign In

2021-03-19 21:47 UTC, amalyah commented on src/components/rux-login/rux-login.js
> +      username: {
According to the visual design, this should be Email instead of Username.

2021-03-19 22:31 UTC, Design-Kat commented on src/components/rux-login/README.md
> +# Login
Good catch, you are correct, unless it was discussed with @dmcalester and there's need for a separate distinction for some circumstances?

2021-03-22 20:53 UTC, Cheshire89 commented
@amalyah && @Design-Kat  
renamed everything to from login to sign in
removed true / false test code
updated username field to email

2021-03-22 21:26 UTC, Design-Kat commented on src/components/rux-sign-in/rux-sign-in.js
> +        <form name="ruxLogin" id="ruxLogin" class="rux-form">
Should these instances be Signin- or is it only the items visible to the user on the website that were changed?

2021-03-22 21:36 UTC, Design-Kat commented on src/components/rux-sign-in/README.md
> +Sign in compoennt enables a user to pass an email and a password to the backend for authentication verification
"compoennt" should be "component"

2021-03-22 22:28 UTC, dmcalester commented on src/components/rux-sign-in/rux-sign-in.js
> +        <form name="ruxLogin" id="ruxLogin" class="rux-form">
This is ok

2021-03-22 22:36 UTC, Cheshire89 commented
![image](https://user-images.githubusercontent.com/13773493/112066825-af409800-8b2c-11eb-899f-9c2ab8d162a6.png)

I dot nline the copy of title here

2021-03-23 14:42 UTC, Design-Kat requested changes
Seeing a spelling mistake (compoennt > component) on readme. 
Lock and Visibility icon is still reading as  smaller than they should be. Ty will need to double check for approval of those.
 Still seeing “SSO Enabled” under the email field- that is only supposed to be visible in SSO mode. Seeing this in both safari and chrome.

2021-03-24 17:46 UTC, amalyah requested changes
SSO Enabled text and icon still causes the cursor to change to a hand which makes it look interactable, which it is not.

2021-03-24 20:04 UTC, cskerbo requested changes

2021-03-24 20:04 UTC, cskerbo commented on src/components/rux-sign-in/rux-sign-in.js
> +              cursor: pointer;
@Cheshire89 I am still seeing the "SSO Enabled" causing a cursor change. Is it because it's nested in the form and taking this style, perhaps?

You may have to apply direct styling of `cursor: none` instead of removing the pointer as your previously did.

2021-03-24 22:25 UTC, Cheshire89 commented
So sorry for that SSO thing :(

2021-03-25 00:03 UTC, dmcalester approved these changes
Approved with a lien for after PI to add README documentation https://rocketcom.atlassian.net/browse/ASTRO-1291

2021-03-25 02:21 UTC, amalyah requested changes
Shoot. Just realized that the email field is using the wrong invalid styling. The error icon is still inside the field instead of providing error text below the field with the icon.

2021-03-25 14:51 UTC, Cheshire89 commented
> Shoot. Just realized that the email field is using the wrong invalid styling. The error icon is still inside the field instead of providing error text below the field with the icon.

Isn't there a separate card for this ?  Because that will involve all the input fields

2021-03-25 15:23 UTC, amalyah commented
> > Shoot. Just realized that the email field is using the wrong invalid styling. The error icon is still inside the field instead of providing error text below the field with the icon.
> 
> @amalyah Isn't there a separate card for this ? Because that will involve all the input fields

You are totally right, @Cheshire89. Looks like that fix was supposed to be completed in [PR 100](https://github.com/RocketCommunicationsInc/astro-components/pull/100) by @nortonprojects. @nortonprojects the problem that I mentioned in that PR still seems to be re-occuring. Could you please look into this?

2021-03-25 18:08 UTC, Design-Kat commented
The only issue I'm seeing are the issues that Amalya had already brought up with the Invalid state, but I don't think it needs a disapproval when they're already mentioned. So once those issues have been sorted (this ticket/another?) I'm good with this implementation.

2021-03-25 18:21 UTC, Cheshire89 commented
> The only issue I'm seeing are the issues that Amalya had already brought up with the Invalid state, but I don't think it needs a disapproval when they're already mentioned. So once those issues have been sorted (this ticket/another?) I'm good with this implementation.

What is exactly wrong with invalid state. Error messages is exactly what I've added

2021-03-25 19:29 UTC, cskerbo approved these changes

2021-03-25 21:10 UTC, Design-Kat approved these changes
Approving with the added note that the validation summary (Email or password not found, yet not "tied" to a specific field) doesn't have official guidance, and may eventually need a ticket.

@dmcalester do you want another ticket split out for server-side type errors? (ie: access denied/lockout), or are you comfortable with the guidance being messaging in a modal dialog per the sign in documentation?

2021-03-25 21:17 UTC, Cheshire89 commented
> Approving with the added note that the validation summary (Email or password not found, yet not "tied" to a specific field) doesn't have official guidance, and may eventually need a ticket.
> 
> @dmcalester do you want another ticket split out for server-side type errors? (ie: access denied/lockout), or are you comfortable with the guidance being messaging in a modal dialog per the sign in documentation?

It is tied to invalid property of component which can be accessed

2021-03-25 21:56 UTC, merged