Astro 445
RocketCommunicationsInc/astro-components pull request #113
Opened 2021-04-02 15:23 UTC by markacianfrani

Fixes an issue with the notification component not closing entirely and throwing an error when using the closeAfter feature. The error was related to trying to assign a value to `_closeAfter`, but there was no setter. 

I'm not sure if clearTimeout is even necessary here though. I'm assuming thats there to prevent any potential memory leaks?

2021-04-07 16:02 UTC, Cheshire89 requested changes
small tweak

2021-04-07 16:02 UTC, Cheshire89 commented on src/components/rux-notification/rux-notification.js
> +      this.timerId = setTimeout(() => {
There is no initializer in the constructor for the timeId which may cause errors in some cases. And I'd call time timeoutRef to be more intuitive

2021-04-09 14:07 UTC, markacianfrani commented on src/components/rux-notification/rux-notification.js
> +      this.timerId = setTimeout(() => {
@Cheshire89 good idea, thanks!

2021-04-09 18:45 UTC, cskerbo approved these changes

2021-04-09 18:54 UTC, merged