ASTRO-1319 extend pop up menu to allow for custom content
RocketCommunicationsInc/astro-components pull request #116
Opened 2021-04-15 06:52 UTC by Cheshire89

https://rocketcom.atlassian.net/browse/ASTRO-1336

Allow insertion of custom content into pop up menu

I've tried a mirriad of things to make the custom event binding happen but we are limited by winodow scoped events that LitElement uses.

2021-04-16 17:29 UTC, markacianfrani commented on src/components/rux-pop-up-menu/rux-pop-up-menu.js
> +      return item.rule === 'separator' ?
Looks like a typo here. `return item.role === 'seperator' ?`

2021-04-16 18:01 UTC, dmcalester requested changes
A couple of notes

1. The separator element behaves like an active element. I am able to click on it and it highlights. This should be an inert element.
2. The separator element is not displaying the dotted line of the published iteration
3. Clicking on a menu item does not close the popup menu (was this requested behavior; we might need to push back on this)
4. The menu doesn’t close when using a "clickOutside" event (again was this a request? Might need to push back or add variant :grimace:
5. Related to #4 clicking on one menu and then another the first menu stays open
6. Possibly explaining 3-5 getting a JS error when clicking on a menu item
`this.onPopUpMenuExpandedChange is not a function`

2021-04-19 21:35 UTC, cskerbo approved these changes

2021-04-20 17:10 UTC, markacianfrani approved these changes
Should we change the long item text back to "Item 5 with a Really Long Title ..." as per the EGS compliance shown here https://www.astrouxds.com/components/pop-up/ ? Or is that outdated? Looks good to me!

2021-04-21 16:16 UTC, dmcalester approved these changes

2021-04-21 16:16 UTC, merged