Icons for ema
RocketCommunicationsInc/astro-components pull request #12
Opened 2020-08-07 22:22 UTC by dmcalester

This PR should remain open for the time being as icons are worked on for EMA.

See further comments in Jira ticket https://rocketcom.atlassian.net/secure/RapidBoard.jspa?rapidView=32&projectKey=ASTRO&modal=detail&selectedIssue=ASTRO-540&search=icon

2020-08-10 18:59 UTC, sknep commented
Is this a draft PR? You can use the draft state in github if it's not ready to merge (based on the comment about it staying open)

It's appropriate to add all new icons to the array in the icon story: https://github.com/RocketCommunicationsInc/astro-components/blob/next/stories/rux-icons-and-symbols.stories.js#L33

2020-08-10 19:32 UTC, sknep commented
Sorry, didn't see that you'd already added them to the story. As this grows, should we sort the array by name? Also, we should add notes about the new icons in the [changelog at the end of the Readme](https://github.com/RocketCommunicationsInc/astro-components/blob/next/src/components/rux-icon/README.md#revision-history) before merge.

2020-08-10 19:55 UTC, sknep commented on stories/rux-icons-and-symbols.stories.js
> +    'visibility-off',
I think these are backwards?

2020-08-13 17:18 UTC, sknep commented
I'm still of the opinion that we should add notes about the new icons in the changelog at the end of the Readme before merge here: https://github.com/RocketCommunicationsInc/astro-components/blob/next/src/components/rux-icon/README.md#revision-history

Even if it's just:

##### **4.1**
- Added new icons

2020-10-22 19:12 UTC, cskerbo requested changes

2020-10-22 19:12 UTC, cskerbo commented on static/icons/astro.svg
> +  <path id="notifications-filled" d="M53,128 C60.2875,128 66.25,122.092308 66.25,114.871795 L39.75,114.871795 C39.75,122.092308 45.64625,128 53,128 Z M92.75,88.6153846 L92.75,55.7948718 C92.75,35.643
Test comment.

2020-10-22 19:12 UTC, cskerbo commented on static/icons/astro.svg
> +
Another test comment. Hi Sarah!

2021-01-26 20:37 UTC, closed without merging