Astro 859 - button terminology update
RocketCommunicationsInc/astro-components pull request #148
Opened 2021-06-25 21:59 UTC by NicDominguez

Jira Ticket: [https://rocketcom.atlassian.net/browse/ASTRO-859](https://rocketcom.atlassian.net/browse/ASTRO-859)

This PR updates all uses of the term outline when used as a descriptor for a non-primary button to the term secondary. All components, stories, docs, and styling were changed to reflect the new secondary term.

2021-06-25 22:09 UTC, micahjones13 commented on src/components/rux-button/README.md
> +| `secondary` | Boolean | `false` | No       | Displays an button visual treatment suitable for secondary actions, such as a non-preferred alternative to an action identified by a standard button. Fo
"Displays a button", instead of "an". Or maybe just "displays a visual treatment"? Not sure if "...a button visual treatment..." makes much sense

2021-06-25 22:09 UTC, micahjones13 commented on src/components/rux-button/README.md
> +| `secondary` | Boolean | `false` | No       | Displays an button visual treatment suitable for secondary actions, such as a non-preferred alternative to an action identified by a standard button. Fo
Maybe, "Displays a secondary button visual..."?

2021-06-25 22:10 UTC, micahjones13 commented on src/components/rux-button/README.md
> +| `secondary`             | Boolean | `false` | No       | Displays a button visual treatment suitable for secondary actions, such as a non-preferred alternative to an action identified by a standard
"use a secondary button" vs "an secondary button"

2021-06-25 22:15 UTC, micahjones13 approved these changes
Just some grammar changes, but approving. Good work, this looked very tedious

2021-06-28 14:22 UTC, amalyah requested changes
One grammar error!

2021-06-28 14:22 UTC, amalyah commented on src/components/rux-button/README.md
> +| `secondary`             | Boolean | `false` | No       | Displays a secondary button visual treatment suitable for secondary actions, such as a non-preferred alternative to an action identified by
an secondary button > a secondary button

2021-06-28 16:38 UTC, amalyah approved these changes

2021-06-28 19:47 UTC, Cheshire89 approved these changes

2021-06-28 21:58 UTC, merged