Astro 1530 update switch km
RocketCommunicationsInc/astro-components pull request #150
Opened 2021-07-01 18:20 UTC by micahjones13

## Brief Description

Updated rux-switch colors in accordance with [Astro 6 Dark Library](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/master/files/1d17329d-e1a3-490a-a6ad-097e2ecd4825/pages/5DFC6D2A-252C-4612-B7B4-62409FB413A7?s=switch) and [Astro 6 Light Library](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/master/files/b7c2bf0c-9dec-4b07-96d4-ead85393c9d0?s=switch). This change updates rux-switch to match KM design as well.

## JIRA Link

https://rocketcom.atlassian.net/browse/ASTRO-1530

## Related Issue

https://rocketcom.atlassian.net/browse/ASTRO-1517

## General Notes

Switch CSS vars were updated on `scss/common/theme--dark` and `scss/common/theme--light` to match the current implementation in Abstract. 1 new CSS var, `--switchOffBorderColor` was added due to it not existing.

A lot of the versioning on different components was updated along with this PR, I believe from running storybook

## Motivation and Context

Updates the rux-switch component to be in line with KM and current Abstract library. 

## Issues and Limitations

## Types of changes

-   [ ] Bug fix
-   [x] New feature
-   [ ] Breaking change

## Checklist

-   [x] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.

2021-07-01 20:54 UTC, NicDominguez approved these changes
nice job keeping track of the various changes between states and pseudo classes.

2021-07-07 12:57 UTC, markacianfrani approved these changes

2021-07-07 20:56 UTC, amalyah requested changes

2021-07-07 20:56 UTC, amalyah commented on src/components/rux-switch/rux-switch.js
> +          border-radius: 4.7px;
This value matches the track border radius in Sketch, but the Sketch version looks much more rounded than the preview for this PR. @avillaindesire, could you take a look?

2021-07-07 20:56 UTC, amalyah commented on src/components/rux-switch/rux-switch.js
>            height: 11px;
In Sketch, this is 10px. Is there a reason for it to be different in code? (Or is this concern out of scope?)

2021-07-07 20:56 UTC, amalyah commented on src/components/rux-switch/rux-switch.js
>            width: 38px;
In Sketch, this is 30px width if that is within scope. (x and y values are both 4 with the thumb circle overhanging the edge of the track.)

2021-07-07 20:56 UTC, amalyah commented on src/components/rux-switch/rux-switch.js
> +          border-radius: 4.7px;
Is there a reason that we need to define the radius again here and in other switch-related definitions when it was already defined above?

2021-07-07 20:56 UTC, amalyah commented on src/components/rux-switch/rux-switch.js
>            height: 19px;
In Sketch, this is 18x18px, not 19x19 if that difference is within scope for this ticket.

2021-07-07 20:56 UTC, amalyah commented on src/components/rux-switch/rux-switch.js
> +          background: var(--switchOffColor);
This seems like a color variable name that no longer makes sense here since this background color is used for the buttons regardless of Off or On state.

2021-07-07 20:56 UTC, amalyah commented on src/components/rux-switch/rux-switch.js
> +          border: 1px solid var(--switchHoverOffColor);
This color is not used for the hover state in buttons AND is used in both hover and active states for buttons. This color variable name seems to be more confusing than helpful.

2021-07-07 20:56 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +    --switchDisabledOnColor: var(--primary);
Is this variable still used?

2021-07-07 20:56 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +    --switchDisabledOffColor: var(--secondaryText);
Is this variable still used?

2021-07-07 20:56 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --switchOffColor: rgb(234, 238, 244);
This should be using the color variable instead: --backgroundColor

2021-07-07 20:56 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --switchOffBorderColor: rgb(100, 156, 189);
Suggest making this a global color variable since it will show up in other components. (or at least making it a hexcode like the global variables for consistency)

2021-07-07 20:56 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --switchDisabledOnColor: var(--primary);
Are these disabled colors still in use?

2021-07-07 21:15 UTC, micahjones13 commented on src/components/rux-switch/rux-switch.js
> +          background: var(--switchOffColor);
Will change that to --switchBackgroundColor

2021-07-07 21:21 UTC, micahjones13 commented on src/components/rux-switch/rux-switch.js
> +          border: 1px solid var(--switchHoverOffColor);
Changing this to --switchBorderColor

2021-07-08 18:50 UTC, amalyah requested changes

2021-07-08 18:50 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --switchBackgroundColor: var(--lightBorderColor, #eaeef4);
This should be --backgroundColor

2021-07-08 18:50 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +    --switchOffBorderColor: #2b659b;
You are using a color variable for this new color in the _theme--light.scss file. I suggest being consistent with hexcode/variable usage between the two files.

2021-07-08 18:50 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --lightBackgroundColor: rgb(234, 238, 244);
This is the same as the --backgroundColor variable. Suggest referring to that here instead of a custom RGB value.

2021-07-08 18:50 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --lightBorderColor: rgb(100, 156, 189);
Nice to Have: I suggest a more generic variable name for the base definition for this color such as --primaryLighter. The value should be the same as --colorPrimaryLighten2

2021-07-08 18:50 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +    --switchOffBorderColor: #2b659b;
Note that this color value is the same as --colorSecondaryDarken2

2021-07-08 18:50 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --switchBackgroundColor: var(--lightBackgroundColor, #eaeef4);
Note: This is the same as the --backgroundColor

2021-07-08 18:50 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +    --switchOffBorderColor: #2b659b; /* This color does not exist globably and will most likely be used in the future for more components. Until those compoenents design is done, just using the value
You are using a color variable for this new color in the _theme--light.scss file. I suggest being consistent with hexcode/variable usage between the two files.

2021-07-08 18:50 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +    --switchOffBorderColor: #2b659b; /* This color does not exist globably and will most likely be used in the future for more components. Until those compoenents design is done, just using the value
Note that this color value is the same as --colorSecondaryDarken2

2021-07-09 15:24 UTC, amalyah approved these changes

2021-07-09 15:32 UTC, merged