Astro 1527 km input update
RocketCommunicationsInc/astro-components pull request #151
Opened 2021-07-01 18:35 UTC by NicDominguez

_[Jira Ticket](https://rocketcom.atlassian.net/browse/ASTRO-1527)
This is only the astro-components repo portion of the ticket._ 

Updates the input css to incorporate latest changes to KM guidelines. My apologies, but I did auto run prettier before adding the markdown files to the prettier ignore file. 

Dark Theme: (Abstract reference - [inputs](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/master/files/1d17329d-e1a3-490a-a6ad-097e2ecd4825?s=input),  [search](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/master/files/1d17329d-e1a3-490a-a6ad-097e2ecd4825?s=search))

- Field background color
- Field border color
- Filed focus border color
- Placeholder text color & opacity
- Label bottom margin
- Search & clear icons fill color
- Disabled field opacity

Light Theme: (Abstract reference - [inputs](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/master/files/b7c2bf0c-9dec-4b07-96d4-ead85393c9d0?s=input),  [search](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/master/files/b7c2bf0c-9dec-4b07-96d4-ead85393c9d0?s=search))
- Field background color
- Field focus border color
- Search & clear icons fill color

Changes that were not included:
1. Custom styling of input[type="number'] increment button due to need to incorporate JavaSscript.
2. Inclusion of a hide/reveal password icon due to need to discuss further implementation without using JavaScript.

2021-07-01 19:41 UTC, micahjones13 approved these changes

2021-07-07 01:30 UTC, markacianfrani requested changes
Is the global status bar color changing here a regression? https://deploy-preview-151--astro-components.netlify.app/?path=/story/components-global-status-bar--global-status-bar

2021-07-07 21:46 UTC, amalyah requested changes

2021-07-07 21:46 UTC, amalyah commented on src/scss/core/input.scss
> +    color: rgb(0, 0, 0);
This seems to be a mistake in the old code since the color variable is listed immediately below this.

2021-07-07 21:46 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +    --inputBorderColorAlt: var(--inputDark);
What is this used for?

2021-07-07 21:46 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +    --inputBorderColorDisabled: #292a2d;
Is this used at all? My impression was that disabled form elements are just lower opacity..not different colors.

2021-07-07 21:46 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +    --inputFocusTextColor: var(--colorWhite, #ffffff);
This can be removed now or the value can be replaced by defaultText like in the non-focus input styles.

2021-07-07 21:46 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +    --inputBackground: var(--colorDarkBlue, #2b659b);
Text input background color is currently set to inputBackground at #2b659b, but it should actually be the backgroundColor (#101923) instead.

2021-07-07 21:46 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +    --inputBorderColor: #2b659b;
Use the variable already created here: --colorDarkBlue

2021-07-07 21:46 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +    --inputFocusBorderColor: #92cbff;
Use the color variable instead (--primaryLight).

2021-07-07 21:46 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --inputBorderColorAlt: var(--inputDark);
Is this used at all currently?

2021-07-07 21:46 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --inputBorderColorDisabled: #292a2d;
Is this used at all currently?

2021-07-07 21:46 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --inputBorderColor: #649cbd;
I suggest making this a color variable since it is in use in other components as well.

2021-07-07 22:18 UTC, closed without merging

2021-07-07 22:21 UTC, NicDominguez commented
Due to additions in the base color variables needed for this style change it will be easier to redo this ticket and create a new PR.

2021-07-08 15:13 UTC, NicDominguez commented on src/scss/common/_theme--dark.scss
> +    --inputBorderColorAlt: var(--inputDark);
It looks like it is used for the rux-select border color

2021-07-08 15:24 UTC, NicDominguez commented on src/scss/common/_theme--dark.scss
> +    --inputBackground: var(--colorDarkBlue, #2b659b);
#101923 equates to the variable --colorTertiaryDarken3 so I have changed it to that being the root variable.

2021-07-08 15:27 UTC, NicDominguez commented on src/scss/common/_theme--dark.scss
> +    --inputBorderColor: #2b659b;
I created --colorDarkBlue without understanding that there were new colors being added to the astro color palette and that a naming convention had to be decided upon. In my new PR I have added new temporary color variables which we will need to discuss to make sure they are accurate and decide on names.

2021-07-08 15:29 UTC, NicDominguez commented on src/scss/common/_theme--dark.scss
> +    --inputFocusBorderColor: #92cbff;
I have changed it to --colorSecondaryLighten2 since that is the root color variable for --primaryLight as well.

2021-07-08 15:30 UTC, NicDominguez commented on src/scss/common/_theme--light.scss
> +    --inputBorderColorAlt: var(--inputDark);
It is used in the rux-select element

2021-07-08 15:31 UTC, NicDominguez commented on src/scss/common/_theme--light.scss
> +    --inputBorderColorDisabled: #292a2d;
It has been removed.