Astro 1531 km segemented button update
RocketCommunicationsInc/astro-components pull request #153
Opened 2021-07-02 21:56 UTC by NicDominguez

_[Jira Ticket](https://rocketcom.atlassian.net/browse/ASTRO-1531)
This is only the astro-components repo portion of the ticket._ 

Updates the segmented button css to incorporate latest changes to KM guidelines. 

The SCSS file for segmented button and the component styles did not share the same class naming convention and were missing some of the shared styles. I essentially mirrored the two so they would be inline with the documentation. I also created three variables in the theme files to declare values for the hover while checked(selected) state.

Dark Theme: (Abstract reference - [segmented button](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/master/files/1d17329d-e1a3-490a-a6ad-097e2ecd4825?s=segmented))

For unselected, selected, hover, and selected/hover states
- button segment background color
- button segment border color
- button segment text color

Light Theme: (Abstract reference - [segmented button](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/master/files/b7c2bf0c-9dec-4b07-96d4-ead85393c9d0?s=segmented))

For unselected, selected, hover, and selected/hover states
- button segment background color
- button segment border color
- button segment text color

2021-07-06 16:52 UTC, micahjones13 commented on src/scss/common/_theme--light.scss
> +    --segmentedButtonSelectedTextColor: var(--defaultText);
This value is off by 1:  rgb(41, 43, 45) in this repo and rgb(41, 42, 45) in abstract light library. This is just default text being off by 1, so it may be an abstract error rather than a repo error. @amalyah when you get back, could you look at this?

2021-07-09 14:34 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --segmentedButtonSelectedTextColor: var(--defaultText);
In light theme in Sketch I see the selected state text as #292A2D or rgb(41, 42, 45) which is what we have labeled as the Default Text color variable in Sketch.

Looking at the UXDS website colors page, #292A2D or rgb(41, 42, 45) is the hex and rgb value listed for quaternaryDarken4.
https://astrouxds.com/design-guidelines/color/

Looking at the KM guidelines v1.4 document, the mandated default text color should be #292A2D.
https://www.dropbox.com/home/SMC%20%3A%20Astro/Kobayashi%20Maru%20UXWG?preview=KM+Design+Standard+V1.4.pdf

2021-07-09 17:12 UTC, amalyah reviewed
Pending conflict resolution for light and dark theme files before review.

2021-07-09 17:12 UTC, amalyah commented on src/scss/components/segmented-button.scss
>  .rux-segmented-button__segment input:checked + label {
Is there a reason that a box-shadow definition and variable is mentioned in the js file but not in this file?

2021-07-09 20:04 UTC, amalyah requested changes

2021-07-09 20:04 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --segmentedButtonSelectedHoverBackgroundColor: #cee9fc;
Same comment as in the dark theme file. After talking about naming structure with other developers, this would be better as a variable.

2021-07-09 20:04 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --segmentedButtonSelectedBackgroundColor: #cee9fc;
Same comment as in the dark theme file. After talking about naming structure with other developers, this would be better as a variable.

2021-07-09 22:00 UTC, NicDominguez commented on src/scss/common/_theme--light.scss
> +    --segmentedButtonSelectedTextColor: var(--defaultText);
--colorQuaternaryDarken4 has been changed to rgb(41, 42, 45).

2021-07-09 22:06 UTC, NicDominguez commented on src/scss/components/segmented-button.scss
>  .rux-segmented-button__segment input:checked + label {
If the segmented-button had a box shadow previously it might be left over. It looks like there are no box-shadows in the current design. I will remove it from the JS file.

2021-07-09 22:11 UTC, NicDominguez commented on src/components/rux-segmented-button/rux-segmented-button.js
> +                    box-shadow: var(--segmentedButtonSelectedBoxShadow);
It is not defined anywhere. My guess is it is left over from a previous design.

2021-07-09 22:18 UTC, NicDominguez commented on src/scss/common/_theme--light.scss
> +    --segmentedButtonSelectedHoverBorderColor: var(--primary);
good catch, thank you.

2021-07-13 12:56 UTC, markacianfrani approved these changes

2021-07-15 14:41 UTC, amalyah requested changes

2021-07-15 14:41 UTC, amalyah commented on src/components/rux-segmented-button/rux-segmented-button.js
> +                    height: 1.6875rem;
This should probably change to the standard small size as well (1.625 rem)

2021-07-15 14:41 UTC, amalyah commented on src/components/rux-segmented-button/rux-segmented-button.js
> +                    height: 1.6875rem;
1.625 rem I believe

2021-07-15 14:41 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +    /* Segmented Unselected */
Thank you for this comment! It helps.

2021-07-15 14:41 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +        --colorSnowflakesDarkSelected
Nice to have: the spacing here looks a little odd compared to the rest. Is this intentional to highlight the snowflake color?

2021-07-15 14:41 UTC, amalyah commented on src/scss/common/_theme--light.scss
>    */
Nice to have: Missing comment title. Would love to have one here like in the dark theme file.

2021-07-15 14:41 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +        --colorSnowflakesLightSelected
Nice to have: For here and in line 170. Same question as in dark theme for snowflake variable indenting.

2021-07-15 15:55 UTC, NicDominguez commented on src/scss/common/_theme--light.scss
> +        --colorSnowflakesLightSelected
See response on previous comment.

2021-07-15 16:40 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +        --colorSnowflakesDarkSelected
Ah gotcha. Thanks!

2021-07-15 16:48 UTC, amalyah approved these changes

2021-07-20 15:31 UTC, micahjones13 approved these changes

2021-07-20 15:39 UTC, merged