select element updated light/dark
RocketCommunicationsInc/astro-components pull request #154
Opened 2021-07-02 22:56 UTC by micahjones13

Updates the select element (rux-select) class to be in line with KM updates and current Abstract libraries. 
One notable change is adding a background color behind the SVG, which was accomplished by adding an additional param to `background-image` of a linear gradient, and then positioning that accordingly. 
Light changes: 
```
--selectHoverOptBackgroundColor: rgb(28, 63, 94);
    --selectMenuBorderColor: rgb(100, 156, 189);
    --selectMenuCaretBackgroundColor: linear-gradient(
        rgba(206, 233, 252, 1),
        rgba(206, 233, 252, 1)
    );
    --selectMenuBackgroundColor: rgb(234, 238, 244);
    --selectMenuTextColor: var(--primary);
    --selectMenuInvalidBorder: var(--criticalBorder);
    --selectMenuTextHoverColor: rgb(0, 72, 114);
    --selectInactiveCaret: url('data:image/svg+xml,%3Csvg%20width%3D%2210%22%20height%3D%225%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cpath%20fill%3D%22%23005a8f%22%20d%3D%22M0%200h10L5%205z%22%20fill-rule%3D%22evenodd%22%2F%3E%3C%2Fsvg%3E');
    --selectActiveCaret: url('data:image/svg+xml,%3Csvg%20width%3D%2210%22%20height%3D%225%22%20style%3D%22transform%3A%20rotate%28180deg%29%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cpath%20fill%3D%22%23005a8f%22%20d%3D%22M0%200h10L5%205z%22%20fill-rule%3D%22evenodd%22%3E%3C%2Fpath%3E%3C%2Fsvg%3E');
'''
Dark changes: 
'''
 --selectHoverOptBackgroundColor: rgb(28, 63, 94);
    --selectMenuBorderColor: rgb(43, 101, 155);
    --selectMenuCaretBackgroundColor: linear-gradient(
        rgba(28, 63, 94, 1),
        rgba(28, 63, 94, 1)
    );
    --selectMenuBackgroundColor: var(--backgroundColor);
    --selectMenuTextColor: var(--primary);
    --selectMenuInvalidBorder: var(--criticalBorder);
    --selectMenuTextHoverColor: rgb(146, 203, 255);
    --selectInactiveCaret: url('data:image/svg+xml,%3Csvg%20width%3D%2210%22%20height%3D%225%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cpath%20fill%3D%22%234dacff%22%20d%3D%22M0%200h10L5%205z%22%20fill-rule%3D%22evenodd%22%2F%3E%3C%2Fsvg%3E');
    --selectActiveCaret: url('data:image/svg+xml,%3Csvg%20width%3D%2210%22%20height%3D%225%22%20style%3D%22transform%3A%20rotate%28180deg%29%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cpath%20fill%3D%22%234dacff%22%20d%3D%22M0%200h10L5%205z%22%20fill-rule%3D%22evenodd%22%3E%3C%2Fpath%3E%3C%2Fsvg%3E');
'''

2021-07-12 22:41 UTC, NicDominguez approved these changes

2021-07-13 13:03 UTC, markacianfrani approved these changes

2021-07-15 15:54 UTC, amalyah requested changes

2021-07-15 15:54 UTC, amalyah commented on src/scss/core/select.scss
> +    border-radius: 3px;
Is there a reason that this isn't using a variable? (It's fine if there is, but I think it's meant to have the same radius as the select menu currently)

2021-07-15 15:54 UTC, amalyah commented on src/scss/core/select.scss
> +    background-color: var(--selectHoverOptBackgroundColor);
Nice to Have: Is there a reason that this variable isn't --selectMenuOptHoverBackgroundColor? Just looking a the other variables the order of this one seems inconsistent and it took me a bit to realize that the Opt wasn't a Hover Option but a Menu Option.

2021-07-15 15:54 UTC, amalyah commented on src/scss/core/select.scss
> +    color: var(--selectMenuTextHoverColor);
Nice to Have: Match this variable structure to the other variable in terms of specifics: --selectMenuOptTextHoverColor

2021-07-15 15:54 UTC, amalyah commented on src/scss/core/select.scss
> +    background-image: var(--selectInactiveCaret),
Nice to have: change variable to be consistent: --selectMenuInactiveCaret

2021-07-15 15:54 UTC, amalyah commented on src/scss/core/select.scss
> +.rux-select:disabled:hover {
It feels a little weird that hovering over a disabled field still gets a hover state. I believe in general that we don't allow that in our components, so disabled state doesn't get other visual changes. Is this correct by your dev knowledge as well of other components?

2021-07-15 15:54 UTC, amalyah commented on src/scss/core/select.scss
> +    border-color: var(--inputBorderColorDisabled);
In design, the disabled state is the same as the active state but with the 0.4 opacity. Is there a need to declare a specific border-color here?

2021-07-15 15:54 UTC, amalyah commented on src/scss/core/select.scss
> +    border: 1px solid var(--primary);
This should be --primaryLight

2021-07-15 15:54 UTC, amalyah commented on src/scss/core/select.scss
> +    border-radius: var(--buttonBorderRadius);
Nice to have: Does it make sense to call this out here when the border radius never changes?

2021-07-15 15:54 UTC, amalyah commented on src/scss/core/select.scss
> +    background-image: var(--selectActiveCaret);
Nice to have: --selectMenuActiveCaret for consistency

2021-07-15 15:54 UTC, amalyah commented on src/scss/core/select.scss
> +    border: 1px solid var(--selectMenuTextHoverColor);
This seems like the wrong variable for this line. --selectMenuBorderHoverColor maybe instead?

2021-07-15 15:54 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +    --selectMenuTextHoverColor: rgb(146, 203, 255);
If this should be the Select Menu text hover than this one remain --primary. However, I think this is actually used for the Select Menu Option Text Hover, in which case the value should be --primaryLight.

2021-07-15 15:54 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +    --selectMenuCaretBackgroundColor: linear-gradient(
Is there a reason that this is a linear gradient, when we just have it as a solid fill of the snowflakes/dark-selected color. (See other dev PRs for the appropriate naming system for the new color variable)

2021-07-15 15:54 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +    --selectMenuBorderColor: rgb(43, 101, 155);
This should be --colorSecondaryDarken2

2021-07-15 15:54 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +    --selectHoverOptBackgroundColor: rgb(28, 63, 94);
If this is for the Select Menu Option item background color on hover, then the value should be the snowflakes/dark-selected value (whatever is the agreed upon variable between developers across PRs) at 30% opacity. In context in the designs, the 30% opacity value is over the menu background fill which is --backgroundColor.

2021-07-15 15:54 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +    --selectHoverOptBackgroundColor: rgb(28, 63, 94);
Looks like a variable for the Select Menu Option item background color when that item is selected is missing from this list. It's the snowflakes/dark-selected color at 100% opacity.

2021-07-15 15:54 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +    --selectMenuTextHoverColor: rgb(146, 203, 255);
Looks like this is missing the Select Menu Option selected text color which should be --defaultText I believe.

2021-07-15 15:54 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --selectHoverOptBackgroundColor: rgb(28, 63, 94);
Same variable naming concern as in the dark theme.

2021-07-15 15:54 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --selectHoverOptBackgroundColor: rgb(28, 63, 94);
This should be the snowflakes/light-selected color at 30% opacity.

2021-07-15 15:54 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --selectMenuBorderColor: rgb(100, 156, 189);
This should be --colorPrimaryLighten2

2021-07-15 15:54 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +        rgba(206, 233, 252, 1),
This should be a snowflakes/light-selected variable.

2021-07-15 15:54 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --selectMenuBackgroundColor: rgb(234, 238, 244);
--backgroundColor

2021-07-15 15:54 UTC, amalyah commented on src/scss/common/_theme--light.scss
>      Drop Down/Select Colors
Missing Select Menu Option selected states. Background: snowflakes/light-selected. Text: --defaultText

2021-07-15 15:54 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --selectMenuTextHoverColor: rgb(0, 72, 114);
--primaryLight

2021-07-20 22:57 UTC, micahjones13 commented on src/scss/core/select.scss
> +.rux-select:disabled:hover {
This changes the cursor to have a cancel sign underneath it. I know that rux-tabs uses the same cursor on a disabled hover state.

2021-07-21 15:25 UTC, micahjones13 commented on src/scss/common/_theme--dark.scss
> +    --selectMenuCaretBackgroundColor: linear-gradient(
There is - because this is a native select HTML element, there isn't a way to add something inside it to add a background color too, like a span. The solution I came up with here was adding a second background argument to the `background-image` on the select, but straight colors aren't accepted as a second argument for that `background-image` but linear gradients are, so I used that. I will update the color names within the linear gradient though.

2021-07-21 18:20 UTC, amalyah requested changes
One small change to SelectMenuOptTextHoverColor value.

2021-07-21 18:20 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --selectMenuHoverOptBackgroundColor: rgba(206, 233, 252, 0.3);
Nice to have: --selectMenuOptHoverBackgroundColor for consistency

2021-07-21 18:47 UTC, amalyah requested changes
Sorry, looks like I missed or made mistakes on a few color variables.

2021-07-21 18:47 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --selectMenuBorderHoverColor: var(--primary);
If this is just for the menu field and not the options then this should be --primaryDark.

2021-07-21 18:47 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --selectMenuTextHoverColor: var(--primaryLight);
Sorry, I think I got this wrong earlier. If this is the text color in the menu field on hover and not hover over an option, then this should just be --primary.

2021-07-21 18:47 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +    --selectMenuTextHoverColor: var(--primaryLight);
Sorry, I got this wrong earlier. If this is just for the menu field's text and not a menu option, then this should be --primary.

2021-07-21 20:59 UTC, amalyah requested changes

2021-07-21 20:59 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --selectMenuInvalidBorder: var(--criticalBorder);
Ah, I did not realize that criticalBorder in light theme was a different value than in the dark theme in code, but this makes sense now. I'm pretty sure the bright red color that is the same as used in the dark theme for this variable is used in the light theme in a slightly different way. I think you could steal the variable from the input invalid borders.

2021-07-21 21:23 UTC, micahjones13 commented on src/scss/common/_theme--light.scss
> +    --selectMenuInvalidBorder: var(--criticalBorder);
Just to clarify, the `--selectMenuInvalidBorder` should be `rgb(255, 56, 56)`, correct?

2021-07-21 21:28 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --selectMenuInvalidBorder: var(--criticalBorder);
Correct

2021-07-22 13:46 UTC, amalyah approved these changes

2021-07-22 14:38 UTC, merged