Astro 1527 km input updates v2
RocketCommunicationsInc/astro-components pull request #155
Opened 2021-07-08 00:37 UTC by NicDominguez

_[Jira Ticket](https://rocketcom.atlassian.net/browse/ASTRO-1527)
This is only the astro-components repo portion of the ticket._ 

Updates the input scss to incorporate latest changes to KM guidelines.

**New temporary global color variables have been created to account for new KM preferred colors while keeping the hierarchy of the css custom properties. The naming convention will need to change once it has been decided upon. I will not be merging this PR until we have the new variable names.** 

Dark Theme Changes: (Abstract reference - [inputs](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/master/files/1d17329d-e1a3-490a-a6ad-097e2ecd4825?s=input),  [search](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/master/files/1d17329d-e1a3-490a-a6ad-097e2ecd4825?s=search))

- Field background color
- Field border color
- Field focus border color
- Search & clear icons fill color

Light Theme Changes: (Abstract reference - [inputs](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/master/files/b7c2bf0c-9dec-4b07-96d4-ead85393c9d0?s=input),  [search](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/master/files/b7c2bf0c-9dec-4b07-96d4-ead85393c9d0?s=search))

- Field background color
- Field focus border color
- Search & clear icons fill color

General Input & Label Changes:
- Placeholder text color & opacity
- Label bottom margin

Changes that were not included:
1. Custom styling of input[type="number'] increment button due to need to incorporate JavaSscript.
2. Inclusion of a hide/reveal password icon due to need to discuss further implementation without using JavaScript.

2021-07-09 16:00 UTC, amalyah requested changes
As discussed yesterday, there will have to be a separate effort to check the color variable hex/rgb codes against the values in design/KM guidelines/the AstroUXDS website. Let me know if that's going to be in this ticket or if we need to create a new one (if it hasn't already been created.)

2021-07-09 16:00 UTC, amalyah commented on src/scss/core/input.scss
> +    border-radius: 4px;
Border-radius of input field is 3px in Sketch.

2021-07-09 16:00 UTC, amalyah commented on src/scss/core/input.scss
> +    background-color: var(--colorSecondaryLighten3);
Nice to have: It seems inconsistent to me to not give this an --inputSelectedBackgroundColor variable like the other input variables. Would be easier to change it in the future if all the color assignments are in the theme files, for example. For selections, there will be a separate color assignment for dark vs. light theme.

2021-07-09 16:00 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +    --inputTextColor: var(--colorWhite);
Nice to have: Suggest changing this to var(--defaultText)

2021-07-09 16:00 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +    --inputBackgroundColor: var(--colorTertiaryDarken3);
Nice to have: Suggest changing this to var(--backgroundColor)

2021-07-09 16:00 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +    --inputFocusBorderColor: var(--colorSecondaryLighten2);
Nice to have: Suggest changing this to var(primaryLight)

2021-07-09 16:00 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --inputBackgroundColor: var(--colorQuaternaryLighten3);
Nice to have: change to var(--backgroundColor)

2021-07-09 16:00 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --inputFocusBorderColor: var(--colorPrimaryDarken1);
Nice to have: change to var(--primaryDark)

2021-07-09 16:00 UTC, amalyah commented on src/scss/common/_variables.scss
> +    --colorTemp6b8ca5: #6b8ca5;
As we discussed yesterday, I don't believe this color is in use in the design files.

2021-07-09 16:39 UTC, NicDominguez commented on src/scss/common/_theme--dark.scss
> -  --primaryDarkHover: #6b8ca5;
This --primaryDarkHover color is not referenced in the design files. Should it be a standard color variable. The light theme file has the following comment next to this variable: "this is a temporary fix, the use of opacity from Sketch is new and not accounted for in CSS".

2021-07-09 16:39 UTC, NicDominguez commented on src/scss/common/_variables.scss
> +    --colorTemp6b8ca5: #6b8ca5;
I figured out where I got this. It is referenced as a the color for --primaryDarkHover in the dark theme file. I'm not sure we should be using it. See my comment on in the dark theme file row 18.

2021-07-09 16:50 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> -  --primaryDarkHover: #6b8ca5;
Can you figure out where the primaryDarkHover variable is in use in the code? I can cross-reference what is used in the relevant components in design then.

2021-07-09 17:32 UTC, NicDominguez commented on src/scss/core/input.scss
> +    background-color: var(--colorSecondaryLighten3);
Just to clarify. This is the selector for the background color when the user highlights text within the input field and not focus state. I created a --inputSelectionBackgroundColor variable as recommend.

2021-07-09 17:39 UTC, NicDominguez commented on src/scss/common/_theme--dark.scss
> -  --primaryDarkHover: #6b8ca5;
The only place I see it used is in the light-theme file as  --tableRowHoverBackgroundColor: var(--primaryDarkHover);

2021-07-13 13:19 UTC, markacianfrani commented
is this ready for review? 

There's currently some regressions with Tree, Progress, Select. The borders appear to be missing.

2021-07-13 16:29 UTC, NicDominguez commented
> is this ready for review?
> 
> There's currently some regressions with Tree, Progress, Select. The borders appear to be missing.

I was able to fix the Tree and Progress borders but the Select regression fail is due to a shared variable if the input fields. I believe this change would be fixed in #154 once merged.

2021-07-15 18:39 UTC, amalyah requested changes

2021-07-15 18:39 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --inputTextColor: var(--colorQuaternaryDarken4);
Nice to have: --defaultText instead

2021-07-15 18:39 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --inputFocusTextColor: var(--colorQuaternaryDarken4);
Nice to have: --defaultText instead

2021-07-15 21:44 UTC, NicDominguez commented on src/scss/core/input.scss
> +    border: 1px solid var(--inputFocusBorderColor) !important;
This current design has the same focus border color however, by having this structure it allows us to separate the two if the designs ever differ in the future. In general I tried not to change the css rules and just updated the values whenever possible.

2021-07-15 21:46 UTC, NicDominguez commented on src/scss/core/input.scss
> +    /* outline: none; */
It would apply to all input focus states including search however the property is commented out and not doing anything. I suppose this is left in from a previous need.

2021-07-15 21:50 UTC, NicDominguez commented on src/scss/core/input.scss
> +    background-color: var(--inputSelectionBackgroundColor);
This is when the input text is highlighted by the user. I do not see a reference to it in the design but it was part of the css and I changed it to use a component specific variable rather than a color variable.

2021-07-15 21:53 UTC, NicDominguez commented on src/scss/core/input.scss
>  .rux-form-field input:focus,
The definitions on 216 target the focus state, but they do share the same color value.

2021-07-15 21:54 UTC, NicDominguez commented on src/scss/common/_theme--dark.scss
> +    --inputSelectionBackgroundColor: var(--colorSecondaryLighten3);
This is the color of highlighted text.

2021-07-15 21:58 UTC, NicDominguez commented on src/scss/common/_theme--dark.scss
> +    --inputBorderColor: var(--colorSecondaryDarken2, #2b659b);
They are left over from me copy and pasting. I have removed them from the component level variables and left them in the global theme variables because they act as nice to have color references. In the code they act as fallback colors if the variables are undefined.

2021-07-15 22:04 UTC, NicDominguez commented on src/scss/common/_theme--dark.scss
> +    --inputBorderColorAlt: var(--colorTertiaryDarken4);
The only place it is used is in rux-select as the primary border color. Select shares the css rules. with input so I left it in there. 

.../core/select.scss
```
.rux-select {
...
  border: 1px solid var(--inputBorderColorAlt);
...
}
```

2021-07-16 15:06 UTC, amalyah commented on src/scss/core/input.scss
>  .rux-form-field input:focus,
So it's a duplicate?

2021-07-16 15:09 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +    --inputSelectionBackgroundColor: var(--colorSecondaryLighten3);
Ah okay. Not in the designs at all, but seems fine as is. 🤷‍♀️ FYI @avillaindesire

2021-07-16 15:18 UTC, amalyah approved these changes

2021-07-19 21:13 UTC, markacianfrani approved these changes
just want to make sure, are there tickets for:

- Custom styling of input[type="number'] increment button due to need to incorporate JavaSscript.
- Inclusion of a hide/reveal password icon due to need to discuss further implementation without using JavaScript.

2021-07-19 21:13 UTC, markacianfrani commented on src/scss/common/_theme--dark.scss
> -    --inputBorderColorDisabled: #292a2d;
this is removed but still called in select.scss. I cant visually see a difference though

2021-07-19 21:20 UTC, avillaindesire commented on src/scss/common/_theme--dark.scss
> +    --inputSelectionBackgroundColor: var(--colorSecondaryLighten3);
Ah, this isn't in the design. I see what you mean. Can we try changing the highlight background (not the text) to use the selected color (#1c3f5e)? That background is super bright and you can't read the text.

2021-07-19 22:16 UTC, NicDominguez commented on src/scss/common/_theme--dark.scss
> -    --inputBorderColorDisabled: #292a2d;
Just made the tickets for those two issues. I also removed the disabled border color as the design changed to have disabled status signified by change in opacity and not color now.

2021-07-20 17:16 UTC, NicDominguez commented on src/scss/core/input.scss
>  .rux-form-field input:focus,
Sorry, you meant line 116. The rule on line 120 is left over and yes, a duplicate. It has been removed.

2021-07-20 20:06 UTC, micahjones13 approved these changes

2021-07-20 20:40 UTC, merged