Astro 1556 scroll bar km
RocketCommunicationsInc/astro-components pull request #156
Opened 2021-07-08 21:35 UTC by micahjones13

2021-07-08 21:39 UTC, micahjones13 commented on src/scss/common/_global.scss
> +    // border-radius: 4px;
Abstract has border-radius at 4px, but it doesn't look anything like abstract's implementation if 4 is provided here.

2021-07-13 00:03 UTC, markacianfrani requested changes
for some reason, it looks like this breaks the select form component styles. can you take a look? its hard for me to see what's going on in the diff history

2021-07-15 19:35 UTC, amalyah requested changes

2021-07-15 19:35 UTC, amalyah commented on src/scss/common/_global.scss
> +    // border-radius: 4px;
In Sketch we use 4px for the radius of the thumb.

2021-07-15 19:35 UTC, amalyah commented on src/scss/common/_global.scss
> +    border: 3px solid transparent;
Is there a reason to have a transparent border? Just a placeholder for if we ever add a border later?

2021-07-15 19:35 UTC, amalyah commented on src/scss/common/_global.scss
> +    background-color: var(--scrollBarThumbBackgroundHoverColor);
Having a different color when the thumb is active or hovered is not recorded in the design files. @avillaindesire is this something you consulted with dev on? (If yes, we should add those states to the design files. If no, we should remove it from code.)

2021-07-15 19:35 UTC, amalyah commented on src/scss/common/_theme--dark.scss
>          rgb(58, 129, 191)
Would suggest not referencing the RGB values in these definitions since we will be updating those values soon.

2021-07-15 19:35 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +    --scrollBarTrackBackgroundColor: rgb(27, 45, 62);
Please use new variable for the snowflakes/dark-surface design color.

2021-07-15 19:35 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +    --scrollBarThumbBackgroundColor: rgb(43, 101, 155);
Use the --colorSecondaryDarken2 here to make the color changes easier later.

2021-07-15 19:35 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --scrollBarThumbBackgroundColor: var(--primary, rgb(0, 90, 143));
In Sketch this is --primary at 70% opacity

2021-07-15 19:35 UTC, amalyah commented on .storybook/manager-head.html
> +    /* scrollbars */
Changes mentioned in other files would need to be applied here as well

2021-07-15 19:35 UTC, amalyah commented on src/components/rux-button/rux-button.js
> +                *[hidden] {
Is there a reason that there are button changes in this PR?

2021-07-20 15:16 UTC, micahjones13 commented on src/scss/core/select.scss
> +    border: 1px solid var(--selectMenuInvalidBorder);
Definitely looks out of place. Time to figure out what 10 days ago Micah was thinking

2021-07-20 15:30 UTC, micahjones13 commented on src/scss/common/_variables.scss
> +        Roboto, Oxygen-Sans, Ubuntu, Cantarell, 'Helvetica Neue', sans-serif;
The changes here are due to prettier, but I believe it's listed twice because after the first 'Roboto' the rest are lists of alternatives to use and are specific to certain platforms.

2021-07-20 16:30 UTC, amalyah commented on src/components/rux-button/rux-button.js
> +                *[hidden] {
Ah didn't realize that it would add new *[hidden] sections as well as change spacing and punctuation

2021-07-20 16:35 UTC, micahjones13 commented on src/components/rux-button/rux-button.js
> +                *[hidden] {
It's really hard to tell what's happening in huge diffs like this, but it didn't add any new ones, it just re-writes it to be spaced correctly and that registers on github as a deletion and an addition.

2021-07-20 16:41 UTC, micahjones13 commented on src/scss/common/_global.scss
> +    // border-radius: 4px;
<img width="110" alt="Screen Shot 2021-07-20 at 10 38 56 AM" src="https://user-images.githubusercontent.com/48889844/126362531-6190e8f5-273e-4fc6-83a7-be992de570ee.png">

Here's what it looks like with a 4px border-radius. Doesn't look rounded at all. This may be because of some of the other options like the `border-left-width` for the `::-webkit-scrollbar-thumb:vertical` but I'll need to look more into it.

2021-07-20 17:12 UTC, micahjones13 commented
> for some reason, it looks like this breaks the select form component styles. can you take a look? its hard for me to see what's going on in the diff history

Just reverted the select scss to match current implementation in master - I'm not sure how this ended up here. I must have forgot to swap branches when I worked on some changes for select :no_good:

2021-07-20 17:15 UTC, micahjones13 commented on src/scss/core/select.scss
> +    border: 1px solid var(--selectMenuInvalidBorder);
These have been reverted. I blame this on vacation brain.

2021-07-20 17:19 UTC, avillaindesire commented on src/scss/common/_global.scss
> +    // border-radius: 4px;
Looking at the scrollbar, it’s built really weird. There’s a background-clip on the ::webkit-scrollbar-thumb which, when disabled, doubles the size of it. I think that's why you don't see the rounded corners with 4px. You need to double it to 8px to actually see it show up.

2021-07-20 17:55 UTC, NicDominguez approved these changes

2021-07-20 17:55 UTC, NicDominguez commented on src/scss/common/_theme--light.scss
> +    --primaryWithOpacity: rgba(var(--primary), 0.7);
I had this same kind of change in my component and was unable to get the rgba function to compile properly from scss to css. The chrome dev tools is showing --scrollBarThumbBackgroundColor as undefined so I think you might have the same issue. I still need to talk to Sasha about this so maybe you can jump on a call with us. He said he knows a solution.

2021-07-20 22:17 UTC, micahjones13 commented on src/scss/common/_theme--light.scss
> +    --primaryWithOpacity: rgba(0, 90, 143, 0.7);
Just went with this due to some limitations adding an opacity to a css variable. With the move to Stencil, I don't feel this is the largest priority. @Cheshire89 , I tried your scss variable way that you showed Nic and me, but couldn't get it to work. I think it has something to do with this being translated to CSS through gulp and having a SCSS var isn't valid CSS. Just a hunch, though. Thoughts?

2021-07-21 13:39 UTC, amalyah approved these changes
Approved pending Daniel's response to hover colors.

2021-07-21 13:39 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --scrollBarTrackBackgroundColor: var(--colorWhite, rgb(255, 255, 255));
Nice to have: switch to surface element variable

2021-07-21 16:50 UTC, avillaindesire commented on src/scss/common/_global.scss
> +    background-color: var(--scrollBarThumbBackgroundHoverColor);
I think we talked about it before, but I'm not sure. In any case, I like it. Let's add it to the design files.

2021-07-21 18:54 UTC, markacianfrani approved these changes

2021-07-21 19:47 UTC, merged