Astro 1557 update slider km
RocketCommunicationsInc/astro-components pull request #157
Opened 2021-07-09 21:43 UTC by micahjones13

Updated the slider color vars and values to be in line with current abstract and KM standards. 

Dark theme changes: 

1. `--sliderThumbBackgroundColor: var(--backgroundColor);` from `  --sliderThumbBackgroundColor: var(--primaryDark);`
2. `--sliderThumbBorderColor: var(--primary);` from `--sliderThumbBorderColor: var(--inputBackground);`
3. `--sliderTrackBackgroundColor: var(--primary);` from ` --sliderTrackBackgroundColor: var(--secondaryText);`
4. `    --sliderSelectedThumbBorderColor: var(--primaryLight);` from `--sliderSelectedThumbBorderColor: var(--primaryLight);`
5.  Upped `--sliderThumbBorderSize` to 2px instead of 1px, as per abstract 

Light theme: 

1. `--sliderThumbBackgroundColor: var(--backgroundColor);` from `--sliderThumbBackgroundColor: var(--primaryDark);`
2.  `--sliderThumbBorderColor: var(--primary);` from `--sliderThumbBorderColor: var(--inputBackground);`
3. `    --sliderTrackBackgroundColor: var(--primary);` from `--sliderTrackBackgroundColor: var(--inputBackground);`
4.  Upped `--sliderThumbBorderSize` to 2px instead of 1px, as per abstract

2021-07-09 22:05 UTC, micahjones13 commented on src/components/rux-slider/rux-slider.js
> -          background: radial-gradient(circle,
Removed the radial gradient here, [current abstract](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/master/commits/26319f70445d912070d1e40bd7904fd95a4038c0/files/1d17329d-e1a3-490a-a6ad-097e2ecd4825/layers/7BC0B628-BEA4-41E8-90DF-2A15E49C8F64?mode=build) doesn't use it.

2021-07-15 20:33 UTC, amalyah requested changes

2021-07-15 20:33 UTC, amalyah commented on src/components/rux-slider/rux-slider.js
> +                    --thumbShadow: 0 3px 5px rgba(0, 0, 0, 0.14),
In the current designs, there are no shadows.

2021-07-15 20:33 UTC, amalyah commented on src/components/rux-slider/rux-slider.js
> +                    --trackHeight: 3px;
In the current designs, the unselected track is 1px high while the selected track is 5px high. (Relevant to multiple lines in this file.)

2021-07-15 20:33 UTC, amalyah commented on src/components/rux-slider/rux-slider.js
> +                    /* added */
What does added mean here?

2021-07-15 20:33 UTC, amalyah commented on src/components/rux-slider/rux-slider.js
> +                    background: radial-gradient(
No radial gradient present in the current designs.

2021-07-15 20:33 UTC, amalyah commented on src/scss/common/_theme--dark.scss
>      --sliderHoverThumbBackgroundColor: var(--primaryDark);
--backgroundColor

2021-07-15 20:33 UTC, amalyah commented on src/scss/common/_theme--dark.scss
>      --sliderHoverThumbBorderColor: var(--inputBackground);
--primaryLight

2021-07-15 20:33 UTC, amalyah commented on src/scss/common/_theme--light.scss
>      --sliderHoverThumbBackgroundColor: var(--primaryDark);
--backgroundColor

2021-07-15 20:33 UTC, amalyah commented on src/scss/common/_theme--light.scss
>      --sliderHoverThumbBorderColor: var(--inputBackground);
--primaryLight
(@avillaindesire I suspect this is a design bug since usually hover in light goes to primaryDark. What do you think?)

2021-07-15 20:33 UTC, amalyah commented on src/scss/common/_theme--light.scss
>      --sliderTrackBorderColor: var(--secondaryText);
Is this in use right now? This is not a color we have anywhere in the current Slider designs.

2021-07-15 20:33 UTC, amalyah commented on src/scss/common/_theme--light.scss
>      --sliderTrackBorderSize: 0.25px;
1px to match the dark theme

2021-07-15 20:36 UTC, amalyah commented
Ah I see what happened. You can use the Pressed state in Abstract for Hover. This brings up some need for better naming or at least commenting functions in the design files. We will work on that in the future. @avillaindesire do you agree with using the Pressed state for the hover state as well?

2021-07-19 20:45 UTC, avillaindesire commented
> Ah I see what happened. You can use the Pressed state in Abstract for Hover. This brings up some need for better naming or at least commenting functions in the design files. We will work on that in the future. @avillaindesire do you agree with using the Pressed state for the hover state as well?

Yep, we can use the pressed state for hover. In the future, we may want to explore a different state for hover since you can select any point on the track to move the thumb there.

2021-07-19 20:50 UTC, avillaindesire commented on src/scss/common/_theme--light.scss
>      --sliderHoverThumbBorderColor: var(--inputBackground);
Yep, it looks like a design bug. It should go to --primaryDark

2021-07-19 20:51 UTC, NicDominguez approved these changes
With the design changes requested by Amalya and Daniel this looks good. The merge conflicts are probably only a couple corrected rgb values so won't mess anything up.

2021-07-19 21:26 UTC, avillaindesire requested changes
The slider was was one of the components that required more than a color change. As @amalyah pointed out, the left side of the thumb should be 5px high and the left 1px. The pressed state should not change the fill (shouldn't go primary blue with a white dot). The disabled state has a weird thing where it is making all of the elements transparent. This means that you can see the track behind the thumb. We shouldn't be seeing that. let's make sure that the thumb is obscuring the track even in the disabled state.

2021-07-20 16:29 UTC, amalyah commented on src/scss/common/_theme--light.scss
>      --sliderHoverThumbBorderColor: var(--inputBackground);
Ticket for design fix: https://rocketcom.atlassian.net/browse/ASTRO-1585

2021-07-21 13:54 UTC, markacianfrani requested changes
the select styles are broken here. do we need to merge https://github.com/RocketCommunicationsInc/astro-components/pull/154 in first?

2021-07-26 17:15 UTC, micahjones13 commented on src/scss/common/_theme--light.scss
>      --sliderTrackBorderColor: var(--secondaryText);
It's not, I'll remove it

2021-07-27 20:58 UTC, amalyah requested changes

2021-07-27 20:58 UTC, amalyah commented on src/components/rux-slider/rux-slider.js
> +                    --thumbShadow: 0 3px 5px rgba(0, 0, 0, 0.14),
Is there a reason to keep these in @micahjones13?

2021-07-27 20:58 UTC, amalyah commented on src/components/rux-slider/rux-slider.js
> +                    min-height: var(--trackHeight);
Is there a reason that we're switching from fixed height to min- and max-heights?

2021-07-27 20:58 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +    --sliderThumbSize: 19px;
Nice to have: The slider thumb size, slider border size, and slider track border size are the same between themes. Would suggest keeping that in a slider-specific file instead of a theme-specific file.

2021-07-27 20:58 UTC, amalyah commented on src/scss/common/_theme--light.scss
>      --sliderTrackBorderSize: 0.25px;
I suspect that this is supposed to be the same value in both themes (right now they're different).

2021-07-27 21:57 UTC, micahjones13 commented on src/components/rux-slider/rux-slider.js
> +                    --thumbShadow: 0 3px 5px rgba(0, 0, 0, 0.14),
Sorry, an oversight on my part. Shadows have been removed.

2021-07-27 22:00 UTC, micahjones13 commented on src/components/rux-slider/rux-slider.js
> +                    min-height: var(--trackHeight);
Yes - because we're using a native HTML input[type=range], it's really difficult to style the height of each side of the thumb differently, hence the linear-gradient approach I took. If we set height explicitly here, then all of the slider track will be that height and no more or less, thus making the different heights impossible. This way, the background-size is being set depending on which end of the thumb it's on, and that gives us the 5px and the 1px height. It can't be less than 1px or more than 5px though, hence max/min-height

2021-07-27 22:02 UTC, micahjones13 commented on src/scss/common/_theme--dark.scss
> +    --sliderThumbSize: 19px;
Great point. Also removing --sliderTrackBorderSize because it's not being used

2021-07-28 13:52 UTC, amalyah approved these changes

2021-07-28 15:30 UTC, markacianfrani approved these changes

2021-07-28 15:31 UTC, merged