Astro 1559 km radio button update
RocketCommunicationsInc/astro-components pull request #158
Opened 2021-07-12 16:30 UTC by NicDominguez

Updates radio button dark-theme, light-theme, and core scss for KM updates.

Dark Theme Changes:
`--controlBorderColor: var(--primary) >>>  var(--colorSecondaryDarken2)`
`--controlSelectedBorderColor: var(--primary) >>> var(--colorSecondaryDarken2);`

Light Theme Changes:
`--controlBorderColor: var(--primary) >>> var(--colorTemp649cbd)`

Core Changes:
```
.rux-radio-button input[type="radio"]:checked + label::before {
    border-color: var(--controlSelectedOutlineBorderColor) >>> var(--controlSelectedBorderColor);;
}
```

_The hex value 649cbd appears in abstract but not in the Figma color palette. I still need to get designs input on whether this value is accurate or not and how to name it._

2021-07-12 17:31 UTC, markacianfrani commented
should this also be affecting the styles of checkbox and switch?

2021-07-12 21:02 UTC, NicDominguez commented
> should this also be affecting the styles of checkbox and switch?

Yes, they share the same global variables and all components have been are in the process of being updated to the new values just haven't been merge yet.

2021-07-15 20:57 UTC, amalyah requested changes

2021-07-15 20:57 UTC, amalyah commented on src/scss/core/radio.scss
> +    background-color: transparent;
Not sure if this is the relevant line, but the radio buttons no longer have transparent backgrounds. They use --backgroundColor now instead (for both themes).

2021-07-15 20:57 UTC, amalyah commented on src/scss/common/_theme--light.scss
>      --controlSelectedBackgroundColor: transparent;
This might be out of scope but it seems weird that this color is transparent in light theme but has a value in dark theme.

2021-07-15 20:57 UTC, amalyah commented on src/scss/common/_theme--light.scss
>      --controlSelectedBorderColor: var(--primary);
--colorPrimaryLighten2

2021-07-15 20:57 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --controlHoverOutlineBackgroundColor: none;
Out of scope, but it seems odd that the dark theme file doesn't have this variable or the variable on line 95.

2021-07-15 22:39 UTC, NicDominguez commented on src/scss/common/_theme--light.scss
>      --controlSelectedBackgroundColor: transparent;
I've changed it to the value matching what would normally show with transparent. Visual outcome is the same.

2021-07-15 22:44 UTC, NicDominguez commented on src/scss/common/_theme--light.scss
> +    --controlHoverOutlineBackgroundColor: none;
I've added them to dark theme to keep the files the same but `--controlHoverOutlineBackgroundColor` appears to have no use and must be left over from a previous design.

2021-07-16 16:54 UTC, amalyah commented on src/scss/core/radio.scss
> -    background-color: transparent;
Is there a declaration elsewhere in the file that states that the background-color is always --backgroundColor (or some variable that ties up to that eventually)?

2021-07-16 16:54 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --controlHoverOutlineBackgroundColor: none;
Ah okay. Thanks!

2021-07-16 21:07 UTC, NicDominguez commented on src/scss/core/radio.scss
> -    background-color: transparent;
The code relied on the default value for background-color being transparent. I have added new variables to explicitly declare the background color which should make it easier to update in the future.

2021-07-19 15:57 UTC, amalyah approved these changes

2021-07-20 21:06 UTC, Cheshire89 approved these changes

2021-07-21 13:57 UTC, markacianfrani approved these changes

2021-07-21 15:30 UTC, merged