Astro 1568 km pop up update
RocketCommunicationsInc/astro-components pull request #159
Opened 2021-07-12 21:19 UTC by NicDominguez

Updates radio button dark-theme, light-theme, and core scss for KM updates.
[JIRA Ticket](https://rocketcom.atlassian.net/browse/ASTRO-1568)

Dark Theme Changes:
    `--popupMenuBackgroundColor: var(--inputBackground) >>> var(--backgroundColor);`
    `--popupMenuBorderColor: var(--primary) >>> var(--primaryDarker);`
    `--popupMenuTextColor: var(--primaryElementText) >>> var(--primary);`
    `--popupCaretBackgroundColor: var(--primary) >>> var(--primaryDarker);`
    `--popupMenuItemBackgroundColor: var(--primary) >>> var(--backgroundColor);`
    `--popupMenuItemHoverBackgroundColor: var(--primaryLight) >>> rgba(28, 63, 94, 0.3);` 
    _^ unable to set an alpha value on a custom variable and have the scss compile correctly, if you know a way to do this please let me know._
    `--popupMenuItemHoverTextColor: var(--primaryElementText) >>> var(--primaryLight);`
    `--popupMenuItemSeperatorBorderColor: var(--primaryElementText) >>> var(--primaryDarker);`

Light Theme Changes:
    `--popupMenuBackgroundColor: var(--inputBackground) >>> var(--backgroundColor);`
    `--popupMenuBorderColor: var(--primary) >>> var(--colorTemp649cbd);`
    `--popupMenuTextColor: var(--defaultText) >>> var(--primary);`
    `--popupCaretBackgroundColor: var(--primary) >>> var(--colorTemp649cbd);`
    `--popupMenuItemBackgroundColor: var(--primary) >>> var(--backgroundColor);`
    `--popupMenuItemHoverBackgroundColor: var(--primaryLight) >>> rgba(28, 63, 94, 0.3);` _see note in dark theme changes_
    `--popupMenuItemHoverTextColor: vary(--primaryElementText) >>> var(--primaryLight);`
    `--popupMenuItemSeperatorBorderColor: var(--primaryElementText) >>> var(--primaryDarker);`

2021-07-16 20:35 UTC, amalyah requested changes

2021-07-16 20:35 UTC, amalyah commented on src/components/rux-button/rux-button.js
> +                .rux-button-group rux-button:not(:last-child),
Is there a reason that button changes are happening in this PR?

2021-07-16 20:35 UTC, amalyah commented on src/scss/components/pop-up.scss
> +    border-radius: 3px;
@avillaindesire what is the radius of the pop up supposed to be? In Sketch, I'm seeing 4px for the background, 2 px for the lead-in list background to the arrow, and then the arrow side-span is using 3px.

2021-07-16 20:35 UTC, amalyah commented on src/scss/components/pop-up.scss
> +    border-right: 1px solid var(--popupMenuBorderColor);
Duplicate line

2021-07-16 20:35 UTC, amalyah commented on src/scss/components/pop-up.scss
> +    border-top: 3px solid var(--popupMenuBorderColor);
If this is referring to the thicker line below the caret, then all of these references should be a 4px border line.

2021-07-16 20:35 UTC, amalyah commented on src/scss/components/pop-up.scss
> +    border-bottom: 1px solid var(--popupMenuBorderColor);
Sorry, need some education. What are these two borders for? (line 116 and 117)

2021-07-16 20:35 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +    --popupMenuItemHoverBackgroundColor: rgba(28, 63, 94, 0.3);
This value with this opacity is used in other PRs for this sprint as well. Suggest talking with other devs to see if it makes sense to make a variable for the 30% opacity version of Dark Selected for consistency in where colors are defined.

2021-07-16 20:35 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --popupMenuBorderColor: var(--colorPrimaryLighten2);
Nice to Have: Could you do a named variable for the light theme like you did in the dark theme? So in dark theme it's primaryDarker. In light theme it could be primaryLighter.

2021-07-16 20:35 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --popupCaretBackgroundColor: var(--colorPrimaryLighten2);
Nice to Have: --primaryLighter

2021-07-16 20:35 UTC, amalyah commented on src/scss/common/_theme--light.scss
>      --popupMenuItemBackgroundColor: var(--inputBackground);
This should be --backgroundColor instead

2021-07-16 20:35 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --popupMenuItemHoverBackgroundColor: rgba(206, 233, 252, 0.3);
Same comment as in dark theme

2021-07-16 20:35 UTC, amalyah commented on src/scss/common/_theme--dark.scss
> +    --popupMenuItemSeperatorBorderColor: var(--primaryDarker);
If it matters, Seperator is a misspelling of Separator.

2021-07-16 20:35 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --popupMenuItemSeperatorBorderColor: var(--colorPrimaryLighten2);
Nice to have: --primaryLighter

2021-07-16 21:12 UTC, NicDominguez commented on src/components/rux-button/rux-button.js
> +                .rux-button-group rux-button:not(:last-child),
We have a recently added automatic code formatting program called Prettier that runs when we commit changes. It ran and made changes to rux-button. They are only formatting changes and have no impact on the code itself. These should go away as Prettier runs on our code more frequently and everyone gets up to date.

2021-07-16 21:16 UTC, NicDominguez commented on src/scss/components/pop-up.scss
> +    border-right: 1px solid var(--popupMenuBorderColor);
One is border-bottom and the other is border-right

2021-07-16 21:31 UTC, NicDominguez commented on src/scss/components/pop-up.scss
> +    border-bottom: 1px solid var(--popupMenuBorderColor);
116 is for the border on the bottom of the box and 117 is the border for the left side of the box.

2021-07-16 21:32 UTC, NicDominguez commented on src/scss/components/pop-up.scss
> +    border-bottom: 1px solid var(--popupMenuBorderColor);
116 is for the border on the bottom of the box and 117 is the border for the left side of the box.

2021-07-16 21:33 UTC, NicDominguez commented on src/scss/common/_theme--dark.scss
> +    --popupMenuItemHoverBackgroundColor: rgba(28, 63, 94, 0.3);
I will talk with the other devs, its actually a bit tough to solve due to how our code compiles.

2021-07-16 21:45 UTC, NicDominguez commented on src/scss/common/_theme--light.scss
> +    --popupMenuBorderColor: var(--colorPrimaryLighten2);
primaryLighter exits in the light theme file. I have switched the color variables to global theme variables. I can see why having the separate theme variables is useful but something makes me feel uneasy about having global theme variables that don't sync up. According to the new figma file many of the current global theme variables are not named properly and I personally would like to get us closer to that file.

2021-07-16 21:52 UTC, NicDominguez commented on src/scss/common/_theme--dark.scss
> +    --popupMenuItemSeperatorBorderColor: var(--primaryDarker);
All references to the separator were spelled incorrectly. It's fixed now.

2021-07-19 15:59 UTC, amalyah commented
Quick note: In the branch description I think you meant to say that you're making changes to pop ups in the first sentence instead of radio buttons.

2021-07-19 19:39 UTC, amalyah commented on src/scss/components/pop-up.scss
> +    border-right: 1px solid var(--popupMenuBorderColor);
Bleh. You are completely correct. I can't believe I missed that.

2021-07-19 19:41 UTC, amalyah commented on src/scss/components/pop-up.scss
> +    border-bottom: 1px solid var(--popupMenuBorderColor);
I guess what I'm missing is why are only the bottom and left sides called out? I would have thought that it would be all but the side with the arrow on it.

2021-07-19 19:46 UTC, amalyah approved these changes

2021-07-19 21:09 UTC, avillaindesire commented on src/scss/components/pop-up.scss
> +    border-radius: 3px;
Looks like a design bug. Let's go with 3px for the outside and 2px for the inside to be consistent with other elements. So the dev implementation here is good and we'll fix the sketch file

2021-07-20 16:20 UTC, amalyah commented on src/scss/components/pop-up.scss
> +    border-radius: 3px;
Made ticket: https://rocketcom.atlassian.net/browse/ASTRO-1584

2021-07-20 19:50 UTC, markacianfrani approved these changes

2021-07-20 19:55 UTC, dmcalester approved these changes

2021-07-20 20:58 UTC, merged