Astro 1558 checkbox km
RocketCommunicationsInc/astro-components pull request #161
Opened 2021-07-14 18:35 UTC by Cheshire89

https://rocketcom.atlassian.net/browse/ASTRO-1558

- Updated dev storybook build to run gulp in parallel
- removed __variables.scss and associated gulp tasks as tests with Nick showed that this file is no longer used anywhere
- added Primary, Secondary, Tertiary, and Quaternary colors from figma color sheet to variables file
- updated checkbox colors as per designs using newly added variables

* new colors are scoped to checkbox and radio buttons as not to break rest of the app

2021-07-16 21:07 UTC, amalyah requested changes

2021-07-16 21:07 UTC, amalyah commented on src/scss/common/_theme--dark.scss
>      For checkboxes, radio buttons etc …
Nice to Have: As a note, it would be a lot easier for me to do reviews on these controls if they actually had separate variables so that the variable names could make more sense in context. Just from this file I can't tell which colors are just used in some controls and not others or what "...TextColor" variables are referring to for each control.

2021-07-16 21:07 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --controlTextColor: var(--colorPrimary500);
Nice to have: --primary

2021-07-16 21:07 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --controlBorderColor: var(--colorPrimary600);
Just FYI, I think another PR is using --primaryLighter as an alias for this.

2021-07-16 21:07 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --controlBorderColor: var(--colorPrimary600);
Also, I believe that this is supposed to be the equivalent of --colorPrimary300

2021-07-16 21:07 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --controlSelectedBackgroundColor: var(--colorQuaternary200);
Nice to have: --backgroundColor

2021-07-16 21:07 UTC, amalyah commented on src/scss/common/_theme--light.scss
> +    --controlHoverBorderColor: var(--colorPrimary300);
Nice to have: --primaryDark

2021-07-16 21:07 UTC, amalyah commented on src/scss/common/_theme--light.scss
>      --controlSelectedOutlineBorderColor: var(--primary);
Not sure what this control variable is used for, but it doesn't match the pattern in the dark theme. My guess is that this is supposed to be the same as --controlBorderColor's variable.

2021-07-16 21:07 UTC, amalyah commented on src/scss/common/_theme--light.scss
>      --controlSelectedOutlineBackgroundColor: none;
This does not seem to have an equivalent in the dark theme file. Seems odd.

2021-07-19 05:17 UTC, Cheshire89 commented on src/scss/core/table.scss
> +	border-color: var(--primary);
controlSelectedBorderColor was set to primary
Since control* variables are reserved for checkboxes and radio buttons I've substituted the value as not to cause a confusion down the line

2021-07-19 05:20 UTC, Cheshire89 commented on src/scss/common/_variables.scss
> +    --colorPrimary100: #CBDEE9;
Correct and because we are doing incremental changes we cant yet override colors such as primaryDark and primary because it will override the entire app

2021-07-19 13:12 UTC, markacianfrani commented
"Updated dev storybook build to run gulp in parallel"

Can you explain what problem this solves?

2021-07-19 16:45 UTC, Cheshire89 commented
> "Updated dev storybook build to run gulp in parallel"
> 
> Can you explain what problem this solves?

before when you ran  `npm run storybook` it would only recompile if html templates changes and would not recognize changes happening to scss files. One would have to open second console window and run gulp in order for global styles to be compiled. Updated command get rid of the need for the second terminal window and runs storybook build and scss compilation in parallel like we have in stencil repo

2021-07-19 18:49 UTC, NicDominguez requested changes
Since the radio button change has yet to be merged we have some differences in component level variables.  The additions I made should only be used by the radio buttons but you may want to reference them if it makes sense in checkbox. This is what my variables in the radio button pr currently look like:

Dark Theme - 
```    
    --controlTextColor: var(--primaryElementText);
    --controlLabelColor: var(--defaultText);
    --controlBackgroundColor: var(--primary);
    --controlOutlineBackgroundColor: var(--backgroundColor);
    --controlBorderColor: var(--colorSecondaryDarken2);
    --controlAccentColor: var(--primary);

    --controlSelectedTextColor: var(--defaultText);
    --controlSelectedBackgroundColor: var(--primaryDark);
    --controlSelectedBorderColor: var(--colorSecondaryDarken2);
    --controlHoverBorderColor: var(--primaryLight);

    --controlSelectedOutlineBorderColor: var(--primary);

    --controlHoverOutlineBackgroundColor: var(--backgroundColor);
    --controlSelectedOutlineBackgroundColor: var(--backgroundColor); 
``` 

Light Theme - 
```
    --controlTextColor: var(--primaryElementText);
    --controlLabelColor: var(--defaultText);
    --controlBackgroundColor: var(--primary);
    --controlOutlineBackgroundColor: var(--backgroundColor);
    --controlBorderColor: var(--colorPrimaryLighten2);
    --controlAccentColor: var(--primary);

    --controlSelectedTextColor: var(--defaultText);
    --controlSelectedBackgroundColor: var(--primary);
    --controlSelectedBorderColor: var(--colorPrimaryLighten2);
    --controlHoverBorderColor: var(--primaryDark);

    --controlSelectedOutlineBorderColor: var(--primary);

    --controlHoverOutlineBackgroundColor: var(--backgroundColor);
    --controlSelectedOutlineBackgroundColor: var(--backgroundColor);
```

2021-07-19 18:49 UTC, NicDominguez commented on src/scss/common/_variables.scss
> +    --colorPrimary100: #CBDEE9;
I think we may want to wait to insert these and do them as a separate ticket. Then we can change the naming convention and make sure the regression still passes. I am totally on board with doing this change though as the 100-900 convention makes a lot more sense to me.

2021-07-19 18:49 UTC, NicDominguez commented on src/scss/common/_theme--dark.scss
> +    --controlTextColor: var(--colorSecondary500);
Just for reference, all color[...]500 colors are equivalent to the base color variable color[...]. So --colorSecondary500 in the new convention is equivalent to --colorSecondary in the current convention.

2021-07-20 21:17 UTC, NicDominguez approved these changes

2021-07-21 14:00 UTC, markacianfrani approved these changes

2021-07-21 15:04 UTC, amalyah approved these changes

2021-07-21 18:50 UTC, Cheshire89 commented on src/scss/core/radio.scss
> +    background-color: var(--controlBackgroundColor);
radio and checkbox dont have a transparent background (design does have a background set)

2021-07-21 18:50 UTC, merged