Astro 842 naming change to medium/primary
RocketCommunicationsInc/astro-components pull request #182
Opened 2021-09-24 19:17 UTC by NicDominguez

[ASTRO-842](https://rocketcom.atlassian.net/browse/ASTRO-842)

Updates references to standard button size to medium button size.
Updates references to standard button element to primary button element

2021-09-27 13:58 UTC, amalyah requested changes

2021-09-27 13:58 UTC, amalyah commented on src/components/rux-button/README.md
> +| `secondary`             | Boolean | `false` | No       | Displays a secondary button visual treatment suitable for secondary actions, such as a non-preferred alternative to an action identified by
"a  button" > "a primary button"

2021-09-27 15:36 UTC, NicDominguez commented on src/components/rux-button/README.md
> +| `secondary`             | Boolean | `false` | No       | Displays a secondary button visual treatment suitable for secondary actions, such as a non-preferred alternative to an action identified by
good find

2021-09-27 15:37 UTC, amalyah approved these changes

2021-09-28 17:52 UTC, nortonprojects approved these changes

2021-09-28 17:59 UTC, micahjones13 approved these changes

2021-09-28 18:08 UTC, merged