ASTRO-377 - Classification Marking Banners and Labels
RocketCommunicationsInc/astro-components pull request #19
Opened 2020-09-18 11:51 UTC by im-cr

# https://rocketcom.atlassian.net/browse/ASTRO-377

WIP: Updating readme and waiting to publish `rux-classification-marking` to NPM. 

[Design Reference](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/master/commits/00bfa7e635536e882e33ecc99d7311f3ec69d5dd/files/A86AC1CD-D207-4A1D-B7C0-80C938419411/layers/64234A0D-2398-44D2-84CF-799851441B26)
[Component Doc](https://rocketcom.atlassian.net/wiki/spaces/AS11/pages/731709441/Patterns+Classification+Control+Markings)

2020-09-18 15:15 UTC, sknep requested changes
I think you're still working on the smaller labels component, but wanted to point out a few things in the banners for you.

2020-09-18 15:15 UTC, sknep commented on src/components/rux-classifications/rux-classification.js
> +	  <div class="rux-classification__message">${this.message}</div>
This allows for anyone to pass any note at all into the classifications banner and doesn't make sure that the message they typed also matches the color they chose. For example, I could pass "classified" for message and the "topsecret" type / class. I think we'd rather just have them pass one item, the classification, and have that inform the message, rather than leave this open to any input. (based on what I understand of the component requirements -- feel free to correct me if I've oversimplified the expectation)

2020-09-18 15:15 UTC, sknep commented on src/components/rux-classifications/package.json
> +    "@astrouxds/rux-icon": "^4.0.3",
Does this actually need the icons component?

2020-09-18 15:15 UTC, sknep commented on src/components/rux-classifications/package.json
> +  "license": "SEE LICENSE IN LICENSE.md",
Make sure to add a license.md file -- these are missing in the others on master but have been added to the v5 branch for each component folder

2020-09-18 15:18 UTC, dmcalester commented on src/components/rux-classifications/rux-classification.js
> +			visible: {
Check with Amalya, but I don’t think there is an instance where a classification marking should be hidden. Opening up this property could invite unintended consequences

2020-09-18 15:18 UTC, dmcalester commented on src/components/rux-classifications/rux-classification.js
> +    this.classification = 'unclassified';
Again check with Amalya, but I suspect if there is a default we should default to the highest level of classification

2020-09-18 15:20 UTC, sknep commented on src/components/rux-classifications/rux-classification.js
> +	  <div class="rux-classification__message">${this.message}</div>
Here's a link to the component with the knobs set up in a way that explains what I mean: https://deploy-preview-19--astro-components.netlify.app/?path=/story/components-classification--classification-banner&knob-classification=topsecret&knob-Type=banner&knob-Classification Message=Top Secret color but I typed what I want, so UNCLASSIFIED

2020-09-18 15:20 UTC, dmcalester commented on src/components/rux-classifications/rux-classification.js
> +    this.message = '';
Message shouldn't be decoupled from classification level. E.g., top secret shall always be top secret. Check with Amalya about appending a custom message after classification level, but I suspect this is unnecessary

2020-09-18 15:45 UTC, dmcalester requested changes
- Please target the `next` branch not `master`
- When switching between tag and banner version the tag version fills the width of its containing element. The Classification Tags entry exhibits expected behavior of width filling to its internal content
- Validate with Amalya and Carmen the differences between font size and padding between the Sketch document, the specification and the component. The coded example appears
<img width="1012" alt="Screen Shot 2020-09-18 at 8 45 18 AM" src="https://user-images.githubusercontent.com/60529018/93617825-54669200-f98b-11ea-8726-bb9d909f3c13.png">

2020-09-18 16:03 UTC, sknep commented on src/components/rux-classifications/rux-classification.js
> +			visible: {
I wondered about this, but then thought maybe an area would conditionally have classified info... then realized you can apply `hidden` to any node if you want to hide it, so someone could do that on rux-whatever even if we didn't expose a property explicitly: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/hidden

2020-09-18 20:39 UTC, dmcalester commented on src/components/rux-classifications/rux-classification.js
> +			visible: {
@sknep I believe with Custom Elements the `hidden` attribute doesn’t actually hide the element unless you add a specific rule to hide it. I don’t recall if we have that rule as a global property, in which case it should be considered if it should be made local to each component so that ones we absolutely don't want hidden ever like this can be made permanent. I realize that starts to toe the line of being presumptive about developer intentions.

https://developers.google.com/web/fundamentals/web-co…

2020-09-18 20:42 UTC, dmcalester commented on src/components/rux-classifications/rux-classification.js
> +    this.message = '';
To add further clarification to this. We can retain the message/label @sknep do you have preference or guidance on label/message/other term that aligns with other components.

The message should always be appended to the broader classification marker. E.g.,
```
this.message = "Seatec Astronomy"
this.classification = "classified"
```
Would result in a component label of **CLASSIFIED//SEATEC ASTRONOMY**

The only slight outlier is TS//SCI which would be **TS//SCI//SEATEC ASTRONOMY**

2020-09-23 17:05 UTC, sknep commented on src/components/rux-classifications/rux-classification.js
> +					styleLabel = 'Top Secret//SCI';
@amalyah Does this make sense as the 'default' banner type (ie, most common)?

2020-09-23 17:07 UTC, sknep commented on stories/rux-classifications.stories.js
> +        message=" ${markerText}">
Is this space intentional? if so, I don't think we should expect users to pass in a string that starts with a space to have the text not run together in the message.

2020-09-24 16:00 UTC, im-cr commented on stories/rux-classifications.stories.js
> +        message=" ${markerText}">
Yes it was intentional, but decided to remove it. As I understand it's likely that '//SCI' style abbreviations will be passed without spaces.

2020-09-24 16:17 UTC, im-cr commented on stories/rux-classifications.stories.js
> +        message=" ${markerText}">
Confirmed with Amalya, no space should be present.

2020-09-24 16:19 UTC, im-cr commented on src/components/rux-classifications/rux-classification.js
> +					styleLabel = 'Top Secret//SCI';
Confirmed with Amalya, default changed back to unclassified.

2020-09-24 16:23 UTC, im-cr commented on src/components/rux-classifications/package.json
> +  "license": "SEE LICENSE IN LICENSE.md",
added. Thanks @sknep

2020-09-24 17:47 UTC, merged

2020-09-24 23:25 UTC, sknep commented on src/components/rux-classifications/rux-classification.js
> +            markLabel = 'TS//SCI';
So you have the default class as unclassified, but the default label as TS//SCI -- they should match, no?

2020-09-24 23:25 UTC, sknep commented on src/components/rux-classifications/rux-classification.js
> +		if(markerLabel == markerClass){
What should happen if these don't match? I'm not sure what this conditional is doing for the component

2020-09-24 23:25 UTC, sknep commented on src/components/rux-classifications/rux-classification.js
> +      } else if (markType === 'tag') {
Could you maybe combine these switch cases into one, with all the props you'd need set just once?
```js
switch(markClass) {
  case 'unclassified':
    this.markClass = 'unclassified';
    this.markerStyle = 'unclassified';
    this.markLabel = 'unclassified';
    this.tagLabel = 'u';
    break;
```

2020-09-24 23:25 UTC, sknep commented on src/components/rux-classifications/rux-classification.js
> +    const markClass = this.classification.toLowerCase().replace(/\s+/g, '');
Something about having the class name be directly derived from whatever the user might pass in makes me nervous. I think we should have it select from a list of available classes, which match against the user, and provide a 'none' or default when there's no match.

Also, what happens when someone doesn't pass in a classification? What does this line return?

2020-09-24 23:25 UTC, sknep commented on src/components/rux-classifications/rux-classification.js
> +      type: {
I think of "type" as String, Integer, Object, Boolean, etc. I wonder if we could be just a little more specific here in this parameter name.

Also, since there are only two supported options, what we've done in the past is choose one that's a default, and have the other be a variant  that responds to a boolean attribute present (or not present) on the element. For example:

`<rux-whatever prop="something" variantB>`

in this case, that might be a boolean attribute like "tag", which, if present, makes this not a banner.

2020-09-24 23:25 UTC, sknep commented on src/components/rux-classifications/rux-classification.js
> +    :host([classification='${this.getClass('topsecret//sci')}']) {
As we also need to maintain CSS-only versions of Astro, I think we should go ahead and hard-code (so to speak) the class names in, and make sure to add them to the Astro CSS files as well. However, I can understand wanting to keep classes consistent across CSS, HTML, and JS. You can see how we do this with the Notification banner component, which is similar.

2020-09-24 23:25 UTC, sknep commented on stories/rux-classifications.stories.js
> +        type="${markerType}"
If you do change this to a Boolean attribute, then you'd want the Knob to be a checkbox, not a select.

2020-09-24 23:25 UTC, sknep commented on stories/rux-classifications.stories.js
> +          classification="top secret//sci"
I'm not sure about accepting slashes in an HTML attribute. It doesn't look to be officially supported, even though it's working in chrome: https://www.w3.org/TR/CSS21/syndata.html#characters

Could you consider slugifying these parameters so that folks might make fewer mistakes with them? I'm imagining people who might pass it in with just one slash, or who might add spaces.

2020-09-24 23:25 UTC, sknep commented on src/components/rux-classifications/README.md
> +```
This readme doesn't follow the format/template of the others on Astro. I think it's best to keep these consistent. It's also missing a props table and CSS-only directions. There's a template file you can use to keep with the established structure here: https://github.com/RocketCommunicationsInc/astro-components/tree/master/src/components/__rux-template

2020-09-24 23:25 UTC, sknep commented on src/components/rux-classifications/rux-classification.js
> +			width: fit-content;
I'm the last person to scold someone about whitespace, but it does look a little messy across the file here and lines 162-3, and lines 108-9.

2020-09-24 23:25 UTC, sknep commented on src/components/rux-classifications/package.json
> +  "description": "Astro Web Component for classification banners",
Such a nitpick, but since these are banners and tags, maybe call it "classification markings"

2020-09-24 23:25 UTC, sknep commented on src/components/rux-classifications/README.md
> + Apply the ```type``` property attribute to set the marking type. The `type` attribute property accepts two attribute values for marking generation. 1) `banner` generates a banner markingr and 2) `ta
"markingr" -> "marking"
"\```type```" -> "\`type`"

2020-09-28 15:24 UTC, im-cr commented on src/components/rux-classifications/rux-classification.js
> +			width: fit-content;
We can/should implement a linter config. not seeing this white space issue on my repo

2020-09-29 16:15 UTC, sknep commented on src/components/rux-classifications/rux-classification.js
> +					styleLabel = 'Top Secret//SCI';
So when this one got changed, the other switch cases got out-of-sync