Astro 377 - Classification Markings hotfix
RocketCommunicationsInc/astro-components pull request #24
Opened 2020-09-28 17:07 UTC by im-cr

### https://rocketcom.atlassian.net/browse/ASTRO-377

WIP: Created to address remainging updates to Classification Marking Component 

[Previous PR](https://github.com/RocketCommunicationsInc/astro-components/pull/19)

2020-09-28 22:19 UTC, cskerbo approved these changes

2020-09-29 15:52 UTC, sknep requested changes
Did you try combining the switch statements into one? If it didn't work out, I'm just curious why.

Also, you have the switches' default **label** text "TOP SECRET//SCI" but the default **class** as "unclassified" -- having these in the same switch case would prevent those not matching. I can't approve this until the two defaults match, such as when someone misspells or omits an attribute. 

https://github.com/RocketCommunicationsInc/astro-components/pull/19#discussion_r494655819

2020-09-29 18:25 UTC, sknep commented on src/components/rux-classifications/rux-classification.js
> +    :host([classification='${this.marking('topsecret//sci').style}']) {
@im-cr How do you feel about classnames with `//` in them? It seems nonstandard to me. Did you investigate it?

2020-09-29 18:26 UTC, sknep commented on src/components/rux-classifications/rux-classification.js
> +						markingStyle = 'top secret';
This has a space in the string, which means your class name gets broken into two? Is that intentional?

2020-09-30 16:20 UTC, dmcalester commented on src/components/rux-classifications/rux-classification.js
> +    :host([classification='${this.marking('topsecret//sci').style}']) {
Please remove or replace forward slashes. While valid it does introduce potential issues with escaping characters https://mathiasbynens.be/notes/css-escapes

2020-09-30 18:15 UTC, im-cr commented on src/components/rux-classifications/rux-classification.js
> +    :host([classification='${this.marking('topsecret//sci').style}']) {
@sknep @dmcalester updated in last push

2020-09-30 18:31 UTC, im-cr commented on src/components/rux-classifications/rux-classification.js
> +						markingStyle = 'top secret';
@sknep It is, it's used on the classification attribute so it's not two class names, just one string. I don't think this is an issue.

2020-09-30 19:08 UTC, sknep commented on src/components/rux-classifications/rux-classification.js
> +						markingStyle = 'top secret';
@im-cr would this make the class name into two classes, if you pass it in like that?

2020-09-30 19:19 UTC, im-cr commented on src/components/rux-classifications/rux-classification.js
> +						markingStyle = 'top secret';
@sknep nope, 'top secret' is treated as a single string for the classification declaration not .top.secret like a class declaration would.

The marking style output ultimately matches the human readable/writeable version of the marking classification. Like we mentioned when we discussed, it might be helpful to see if that is an issue for users. I'm open to additional thoughts.

2020-09-30 19:27 UTC, sknep approved these changes

2020-09-30 20:53 UTC, merged