ASTRO-663 Removed moment.js in favor of date-fns
RocketCommunicationsInc/astro-components pull request #28
Opened 2020-10-08 18:44 UTC by nortonprojects

2020-10-08 18:45 UTC, nortonprojects commented on package.json
> +    "military-timezones": "^1.0.0"
This is basically just a json file, it would be simple to add it in to the actual code base is we didn't want to add a dependency

2020-10-08 18:46 UTC, nortonprojects commented on src/components/rux-clock/rux-clock.js
> +    this.tzFormat = 'O';
The Intl API doesn't recognize military time zones, so this just forces it to display in terms of GMT offset when one is provided, which is what the military zones map to anyway.

2020-10-08 21:38 UTC, dmcalester commented on package.json
> +    "military-timezones": "^1.0.0"
I think it’s fine for this iteration. 2021 we’ll be looking at ways to reduce/eliminate dependencies.

2020-10-08 22:39 UTC, cskerbo approved these changes
Good work, thank you!

2020-10-08 23:01 UTC, sknep commented
What version do you think this should be released in? given that it's removing and adding a dependency, is that a Major or Minor release? It seems like the implementation itself for developers using Astro is unchanged?

2020-10-09 16:18 UTC, nortonprojects commented
I'd think it's a minor release, there shouldn't be any difference for developers

2020-10-09 16:25 UTC, dmcalester commented
A few notes. Two are essential, one is a minor note.

1. The Day of Year/Julian Date doesn’t appear to be updating. It’s Saturday in Sydney and the Julian date would be 284.
2. Non-essential but the existing clock uses the 3/4 character string value for timezones. This is not critical, timezone support is to be honest an added bonus. All DoD customers use UTC or Z
<img width="1301" alt="Screen Shot 2020-10-09 at 9 16 52 AM" src="https://user-images.githubusercontent.com/60529018/95607292-5f539600-0a10-11eb-99cf-0a17492bead6.png">

3. The use of Z should reflect Z in the clock itself rather than GMT+0 this is a requirement from the ATLAS team
<img width="1066" alt="Screen Shot 2020-10-09 at 9 22 39 AM" src="https://user-images.githubusercontent.com/60529018/95607806-1cde8900-0a11-11eb-82ac-6593bc0cd4e5.png">

2020-10-09 16:26 UTC, dmcalester requested changes
Change request in comments

2020-10-14 14:15 UTC, nortonprojects commented
1 and 3 are fixed, but it looks like 2 is a browser thing, and it should show *most* of them using their abbreviations rather than GMT offset.

https://github.com/marnusw/date-fns-tz/issues/34

2020-10-14 17:27 UTC, merged