Astro-854- GSB Button replace/update
RocketCommunicationsInc/astro-components pull request #32
Opened 2020-11-04 17:28 UTC by im-cr

### https://rocketcom.atlassian.net/browse/ASTRO-854

**Changes:**
- replace button text on GSB
- replaced button text on GSB with tabs
- replace text reference in GSB readme documentaiton.

2020-11-05 14:39 UTC, amalyah requested changes
Comment on Line 3 in the README. Also, line 53 in the README has the outdated wording.

2020-11-05 14:39 UTC, amalyah commented on src/components/rux-global-status-bar/README.md
> +The Global Status Bar is a full width view across the top of an application — an area commonly reserved for global status, global command and top-level navigation. The Global Status Bar often include
Emergency Shut Off **Button**.

2020-11-05 16:45 UTC, im-cr commented on src/components/rux-global-status-bar/README.md
> +The Global Status Bar is a full width view across the top of an application — an area commonly reserved for global status, global command and top-level navigation. The Global Status Bar often include
Added and updated

2020-11-05 19:48 UTC, amalyah approved these changes

2020-11-09 17:33 UTC, cskerbo approved these changes

2020-11-10 17:28 UTC, merged