(WIP) - Astro 971 - KM colors/fonts update
RocketCommunicationsInc/astro-components pull request #33
Opened 2020-12-02 13:05 UTC by im-cr

**Connected Task:**
 - https://rocketcom.atlassian.net/browse/ASTRO-971

**Changes:**

- roboto fonts added w/browser support
- update to _theme--dark.css
- update to _theme--light.css

**Remaining Items:**
- Questions around select and progress svg colors for light and dark

2020-12-02 20:04 UTC, dmcalester commented on src/css/common/_fonts.css
> +	src: url('/fonts/RobotoThin.eot');
Is there benefit to having .eot as the primary file type?

2020-12-02 20:04 UTC, dmcalester commented on src/css/common/_fonts.css
> +/* Medidum */
typo

2020-12-02 20:10 UTC, dmcalester requested changes
- Please remove all fallback colors in var e.g., `var(--someVar, rgb(0,0,0))` becomes `var(--someVar)`
- Please replace all RGB values from KM with hex values (this is true of all color values moving forward (https://rocketcom.atlassian.net/browse/ASTRO-543). For this ticket, just the new KM are fine
- Not technically part of this ticket, but while you’re in the typography CSS please add system native font fallbacks per https://rocketcom.atlassian.net/browse/ASTRO-690

2020-12-03 18:12 UTC, im-cr commented on src/css/common/_fonts.css
> +	src: url('/fonts/RobotoThin.eot');
In the habit on including eot. Have had previous issues with woff/woff2 loading correctly in IE browsers...usually related to an issue of how the fonts are being imported into an app (usually via google fonts). This can be taken out with marginal concern. Any concerns around keeping?

2020-12-03 18:15 UTC, dmcalester commented on src/css/common/_fonts.css
> +	src: url('/fonts/RobotoThin.eot');
Yep they can be removed. According to this EOT are only relevant for IE8 and below https://stackoverflow.com/questions/36105194/are-eot-ttf-and-svg-still-necessary-in-the-font-face-declaration

2020-12-03 21:29 UTC, dmcalester commented on src/css/common/_typography.css
> +  color: var(--fontLinkColor);
Replace with KM value. I believe `--primaryBlue`

2020-12-03 21:31 UTC, dmcalester commented on src/css/common/_global.css
>    color: var(--fontColor, rgb(255, 255, 255));
- Remove fallback color
- Use KM `--defaultText`

2020-12-03 21:51 UTC, im-cr commented on src/css/common/_typography.css
> +  color: var(--fontLinkColor);
For clarity, would this be changed here? '--fontLinkColor' is a variable used in dark and light css theme files. The value has been updated to be '--primary' which is the updated blue. shouldn't the change for the appropriate blue stay at the theme specific css? The color used would default to the correct blue based on the particular theme.

2020-12-03 21:52 UTC, im-cr commented on src/css/common/_global.css
>    color: var(--fontColor, rgb(255, 255, 255));
updated. changes to global were included in another PR

2020-12-04 20:10 UTC, dmcalester requested changes
While most of these items are updating property names there are a few that may require updating the behavior in the component or CSS itself. 

I _**did not**_ log individual changes in _theme-light.css assume all changes reflected will likely also be changed in the light theme

There are some instances that are not clearly defined in the design docs, I have denoted those where possible, they can be ignored for the time being.

I may not have caught every single instance that needs changing. After implementing these, please review this file carefully for any instance of an old CSS custom property that has a new Color Var defined in Sketch.

2020-12-04 20:10 UTC, dmcalester commented on src/css/common/_theme--dark.css
> +  --tableControlsBackgroundColor: var(--globalAppHeader);
Hold on lines 410-414 for the time being

2020-12-04 20:10 UTC, dmcalester commented on src/css/common/_theme--dark.css
> +  --timelineHeaderBackgroundColor: var(--colorTertiaryDarken1);
--globalAppHeader, but validate with Sketch/Abstract

2020-12-04 20:10 UTC, dmcalester commented on src/css/common/_theme--dark.css
> +  --timelineRulerBackgroundColor: var(--colorTertiaryDarken1);
--globalAppHeader, but validate with Sketch/Abstract

2020-12-04 20:10 UTC, dmcalester commented on src/css/common/_theme--dark.css
> +  --timelineRulerTextColor: var(--fontColor);
--defaultText, but validate with Sketch/Abstract

2020-12-04 20:10 UTC, dmcalester commented on src/css/common/_theme--dark.css
> +  --timelineTrackLabelBackgroundColor: var(--colorTertiary);
-defaultText, but validate with Sketch/Abstract

2020-12-04 20:10 UTC, dmcalester commented on src/css/common/_theme--dark.css
> +  --timelineTrackBackgroundColor: var(--colorTertiary);
--surfaceElements, but validate with Sketch/Abstract

2020-12-04 20:10 UTC, dmcalester commented on src/css/common/_theme--dark.css
> +  --timelineRegionBackgroundColor: var(--colorPrimaryDarken3);
--backgroundColor, but validate with Sketch/Abstract

2020-12-04 20:10 UTC, dmcalester commented on src/css/common/_theme--dark.css
> +  --timelineRegionSelectedBorderColor: var(--colorWhite);
--defaultText, but validate with Sketch/Abstract

2020-12-04 20:10 UTC, dmcalester commented on src/css/common/_theme--dark.css
> +  --timelineRegionBorderColor: var(--colorPrimary);
--primaryDark, but validate with Sketch/Abstract

2020-12-04 20:10 UTC, dmcalester commented on src/css/common/_theme--dark.css
> +  --timelineRegionTextColor: var(--fontColor);
--defaultText, but validate with Sketch/Abstract

2020-12-04 20:10 UTC, dmcalester commented on src/css/common/_theme--dark.css
> +  --timelineRegionSelectedBackgroundColor: var(--colorSecondaryDarken2);
--primaryDark, but validate with Sketch/Abstract

2020-12-04 20:10 UTC, dmcalester commented on src/css/common/_theme--dark.css
> +  --timelineRegionSelectedTextColor: var(--fontColor);
--defaultText, but validate with Sketch/Abstract

2020-12-04 20:50 UTC, merged