V2:astro-905 - Update to Radio Buttons
RocketCommunicationsInc/astro-components pull request #38
Opened 2020-12-04 12:50 UTC by im-cr

**Ticket**
- https://rocketcom.atlassian.net/browse/ASTRO-905

**Changes**
 - control.css
 - theme--dark
 - theme--light

**Design References**
 - [Dark Colors](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/b5da7ebe-46f7-45e1-8eb0-10e781a59b26/commits/067f407614265e59b5abb677c35b52672ddfffa6/files/1d17329d-e1a3-490a-a6ad-097e2ecd4825/layers/5301AD0D-8053-49B2-925C-4D4026FD418B)
 - [Light Colors](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/b5da7ebe-46f7-45e1-8eb0-10e781a59b26/commits/c165a3f0bd1da98c19002047b9585bcf01ee2fad/files/b7c2bf0c-9dec-4b07-96d4-ead85393c9d0/layers/5301AD0D-8053-49B2-925C-4D4026FD418B)

2020-12-04 16:09 UTC, dmcalester commented on src/css/common/_theme--dark.css
> +	/* KM Dark Palette Colors */
Change all KM references to **Astro 5 Simplified Color Palette**

2020-12-04 16:11 UTC, dmcalester commented on src/css/common/_theme--dark.css
> +  --controlLabelColor: var(--colorWhite);
Should be `--defaultText`

2020-12-04 16:14 UTC, dmcalester commented on src/css/common/_theme--dark.css
> +  --controlSelectedTextColor: var(--colorWhite);
Should be `--defaultText`

2020-12-04 16:17 UTC, dmcalester commented on src/css/common/_theme--dark.css
> +  --controlBackgroundColor: var(--colorPrimary);
Check to see but this looks like it should be `--primary`

2020-12-04 16:17 UTC, dmcalester commented on src/css/common/_theme--dark.css
> +  --controlAccentColor: var(--colorSecondaryLighten1);
This appears to be unused in control.css, but should likely be `--primary`

2020-12-04 16:18 UTC, dmcalester commented on src/css/common/_theme--dark.css
> +  --controlBorderColor: var(--colorSecondaryLighten1);
Validate assumption, but this should be --primary

2020-12-04 16:20 UTC, dmcalester commented on src/css/common/_theme--light.css
> +	/* KM Light Palette Colors */
Change to ** Astro 5 Simplified Color Palette**

2020-12-04 16:22 UTC, dmcalester commented on src/css/common/_theme--light.css
> +  --controlLabelColor: var(--colorBlack);
--defaultText

2020-12-04 16:22 UTC, dmcalester commented on src/css/common/_theme--light.css
> +  --controlAccentColor: var(--colorSecondary);
Same as dark, likely not used but if it is should be --primary

2020-12-04 16:23 UTC, dmcalester commented on src/css/common/_theme--light.css
> +  --controlSelectedTextColor: var(--colorBlack);
--defaultText

2020-12-04 16:25 UTC, dmcalester commented on src/css/common/_theme--light.css
> +  --controlSelectedBackgroundColor: var(--colorSecondaryDarken1);
This is likely unused, but validate. Seems most likely it would be transparent

2020-12-04 16:26 UTC, dmcalester requested changes
Overall Storybook rendering looks good, but there are several of the older CSS custom properties in use.

2020-12-04 21:00 UTC, im-cr commented
> Overall Storybook rendering looks good, but there are several of the older CSS custom properties in use.

Yep, are account for in each component pr. Anything missed will be include in a variable clean up branch

2020-12-04 22:00 UTC, dmcalester requested changes
Minor change

2020-12-05 01:12 UTC, im-cr commented
@dmcalester var values updated

2020-12-07 15:04 UTC, amalyah approved these changes

2020-12-07 15:04 UTC, amalyah commented on static/css/astro.core.min.css
> +  );--timelineRegionBackgroundColor: var(--primaryLighten4);--timelineRegionBorderColor: var(--primaryLighten3);--timelineRegionSelectedBorderColor: var(--colorSecondaryDarken3);--timelineRegionSelec
Is there a reason that Timeline changes are in this PR?

2020-12-07 16:13 UTC, im-cr commented on static/css/astro.core.min.css
> +  );--timelineRegionBackgroundColor: var(--primaryLighten4);--timelineRegionBorderColor: var(--primaryLighten3);--timelineRegionSelectedBorderColor: var(--colorSecondaryDarken3);--timelineRegionSelec
@amalyah some of the earlier PR contain some earlier changes from to the general updates from light/dark theme css. this can be ignored for now.

2020-12-07 16:41 UTC, amalyah approved these changes

2020-12-07 18:28 UTC, im-cr commented
@dmcalester need your approval when ready

2020-12-07 19:27 UTC, amalyah commented
Have radio buttons ever had a hover state? If we need one, standard pattern applies. Change the primary color to primary-light for dark theme and primary-dark for light theme.

2020-12-07 19:27 UTC, amalyah requested changes
Question regarding whether we should have a hover state or not (not designed, but we know what the pattern would be)

2020-12-07 19:46 UTC, im-cr commented
> Question regarding whether we should have a hover state or not (not designed, but we know what the pattern would be)

@amalyah added hover state for uncheck radio/check borders. dark -> light and light -> dark. Do we want the hover state to apply in when checked as well?

2020-12-07 22:30 UTC, cskerbo approved these changes

2020-12-07 22:53 UTC, merged

2020-12-09 19:17 UTC, amalyah commented
> > Question regarding whether we should have a hover state or not (not designed, but we know what the pattern would be)
> 
> @amalyah added hover state for uncheck radio/check borders. dark -> light and light -> dark. Do we want the hover state to apply in when checked as well?

That would make sense to me.