V2:Astro-913 - Segmented Button
RocketCommunicationsInc/astro-components pull request #39
Opened 2020-12-04 13:42 UTC by im-cr

**Ticket**
- 913: https://rocketcom.atlassian.net/browse/ASTRO-913

**Changes**
 - theme-dark
 - theme-light
 - segmented-button.css
 - rux-segmented-button.js

**Related Commit:**
https://github.com/RocketCommunicationsInc/astro-components/commit/4eaad9100d584064f1abed0b35b2a7dd4271f4ad

**Design References**
  - [Dark Colors](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/f22ccbcd-6954-4228-b52f-34e5288e75c8/files/1d17329d-e1a3-490a-a6ad-097e2ecd4825?filter=changed)
  - [Light Colors](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/f22ccbcd-6954-4228-b52f-34e5288e75c8/files/b7c2bf0c-9dec-4b07-96d4-ead85393c9d0?filter=changed&s=segmented)

2020-12-04 16:37 UTC, dmcalester commented on src/css/common/_theme--dark.css
> +	/* KM Dark Palette Colors */
Change to Astro 5 Simplified Colors

2020-12-04 16:37 UTC, dmcalester commented on src/css/common/_theme--dark.css
> +  --segmentedButtonBorderColor: var(--colorTertiaryDarken1);
should be --primary

2020-12-04 16:38 UTC, dmcalester commented on src/css/common/_theme--dark.css
> +  --segmentedButtonTextColor: var(--primaryLight);
Should be --pimary

2020-12-04 16:49 UTC, dmcalester commented on src/css/common/_theme--light.css
> +	/* KM Light Palette Colors */
Change to Astro 5 Simplified Colors

2020-12-04 16:51 UTC, dmcalester commented on src/css/common/_theme--light.css
> +  --segmentedButtonHoverBackgroundColor: var(--primaryLight);
should be `--primaryDark`

2020-12-04 16:52 UTC, dmcalester commented on src/css/common/_theme--light.css
> +  --segmentedButtonHoverTextColor: var(--colorWhite);
should be `--defaultText`

2020-12-04 16:52 UTC, dmcalester commented on src/css/common/_theme--light.css
> +  --segmentedButtonSelectedTextColor: var(--colorWhite);
should be `--defaultText`

2020-12-04 16:55 UTC, dmcalester commented on src/css/common/_theme--light.css
> +  --segmentedButtonHoverTextColor: var(--colorWhite);
should be `--primaryElementText`

2020-12-04 16:55 UTC, dmcalester commented on src/css/common/_theme--light.css
> +  --segmentedButtonSelectedTextColor: var(--colorWhite);
should be `--primaryElementText`

2020-12-04 22:56 UTC, dmcalester commented on static/css/astro.css
>    transition: box-shadow 0.067 ease-out;
remove transition

2020-12-04 22:56 UTC, dmcalester commented on static/css/astro.css
> +  box-shadow: var(--segmentedButtonSelectedBoxShadow);
remove box-shadow

2020-12-04 22:57 UTC, dmcalester commented on static/css/astro.css
> +	/* --segmentedButtonSelectedBoxShadow: inset 0 3px 4px rgba(0, 0, 0, 0.1), inset 0 1px 5px rgba(0, 0, 0, 0.06);
remove all references to box shadow

2020-12-04 22:57 UTC, dmcalester commented on static/css/astro.css
> +	/* --segmentedButtonSelectedBoxShadow:
remove all referenced to box-shadow

2020-12-04 22:57 UTC, dmcalester commented on static/css/astro.core.css
> +	/* --segmentedButtonSelectedBoxShadow:
remove all references to box shadow

2020-12-04 22:58 UTC, dmcalester commented on src/css/components/segmented-button.css
> +  box-shadow: var(--segmentedButtonSelectedBoxShadow);
Remove all box-shadow props

2020-12-04 22:58 UTC, dmcalester commented on src/css/components/segmented-button.css
>    transition: box-shadow 0.067 ease-out;
Remove transition

2020-12-04 22:58 UTC, dmcalester commented on src/css/common/_theme--light.css
> +	/* --segmentedButtonSelectedBoxShadow: inset 0 3px 4px rgba(0, 0, 0, 0.1), inset 0 1px 5px rgba(0, 0, 0, 0.06);
remove

2020-12-04 22:58 UTC, dmcalester commented on src/css/common/_theme--light.css
> +	--segmentedButtonSelectedBoxShadow: none;
remove

2020-12-04 22:59 UTC, dmcalester commented on src/css/common/_theme--dark.css
> +	/* --segmentedButtonSelectedBoxShadow:
remove

2020-12-04 22:59 UTC, dmcalester commented on src/css/common/_theme--dark.css
> +		--segmentedButtonSelectedBoxShadow:none;
remove

2020-12-04 22:59 UTC, dmcalester requested changes
Minor remove box-shadow vars, props and associated transitions

2020-12-05 01:13 UTC, im-cr commented
@dmcalester box shadows and transitions removed

2020-12-07 15:10 UTC, amalyah commented
Missing hover state on selected button section. @carmenparks Is this okay or should we add in a hover state for the selected segment as well?

2020-12-07 15:14 UTC, amalyah commented
Hover state still uses the primary color for the border line around the hover fill colors. Is this acceptable @carmenparks? The design file has the same border color as the background color on hovered segments. We would have to alter the design to align with the code.

2020-12-07 15:16 UTC, amalyah requested changes
Need alignment with designs or approval from Visual Design to alter the designs to match the code.

2020-12-07 15:20 UTC, amalyah commented
Font size needs to change to 16px equivalent (A5 KM v1.1 body font size)

2020-12-07 15:50 UTC, carmenparks commented
> Missing hover state on selected button section. @carmenparks Is this okay or should we add in a hover state for the selected segment as well?

Selected state should not have a hover since no action can be taken when it's selected. It's fine as is.

2020-12-07 15:54 UTC, carmenparks commented
> Hover state still uses the primary color for the border line around the hover fill colors. Is this acceptable @carmenparks? The design file has the same border color as the background color on hovered segments. We would have to alter the design to align with the code.

Hover state border should match the fill.

2020-12-07 16:43 UTC, amalyah requested changes
Needs font size change to body font size. Also, hover state should have border color of that segment be the same as the background color of the hovered segment.

2020-12-07 17:54 UTC, im-cr commented
> Needs font size change to body font size. Also, hover state should have border color of that segment be the same as the background color of the hovered segment.

font-size and hove state border updated

2020-12-07 19:29 UTC, amalyah approved these changes

2020-12-07 20:06 UTC, cskerbo approved these changes

2020-12-07 21:06 UTC, merged