V2:Astro-915 - Update to Push Button KM Styles
RocketCommunicationsInc/astro-components pull request #40
Opened 2020-12-04 13:57 UTC by im-cr

**Ticket**
- https://rocketcom.atlassian.net/browse/ASTRO-915

**Changes** - commit: https://github.com/RocketCommunicationsInc/astro-components/pull/38/commits/20c3be31744c35309bf89462f82aa298a5dde8f7
 - rux-push-button.js
 - pushbutton.css
 - theme--dark
 - theme--light

**Design References**
  - [Dark](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/f22ccbcd-6954-4228-b52f-34e5288e75c8/files/1d17329d-e1a3-490a-a6ad-097e2ecd4825?filter=changed&s=push)
  - [Light](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/f22ccbcd-6954-4228-b52f-34e5288e75c8/files/b7c2bf0c-9dec-4b07-96d4-ead85393c9d0?filter=changed&s=push)

2020-12-04 22:41 UTC, dmcalester commented on src/components/rux-push-button/rux-push-button.js
>            box-shadow: inset 0 0 4px rgba(0, 0, 0, 0.33);
Remove inset shadow

2020-12-04 22:42 UTC, dmcalester commented on src/css/components/pushbutton.css
>    box-shadow: inset 0 0 4px rgba(0, 0, 0, 0.13);
Remove inset shadow

2020-12-04 22:43 UTC, dmcalester requested changes
Remove inset shadow from selected state in rux-push-button.js and pushbutton.css

2020-12-05 01:00 UTC, im-cr commented
@dmcalester shadows removed

2020-12-07 15:21 UTC, amalyah commented
Font size needs to change to 16px equivalent (A5 KM v1.1 body font size)

2020-12-07 15:24 UTC, amalyah requested changes
Needs font size change

2020-12-07 15:51 UTC, im-cr commented
@amalyah font-size bumped up to 1rem/16px

2020-12-07 16:46 UTC, amalyah approved these changes

2020-12-07 20:10 UTC, cskerbo approved these changes

2020-12-07 21:09 UTC, merged