V2:astro-942 - Input/Search KM Style Update
RocketCommunicationsInc/astro-components pull request #42
Opened 2020-12-04 15:02 UTC by im-cr

**Tickets**
  - https://rocketcom.atlassian.net/browse/ASTRO-942

**Changes** - commit: https://github.com/RocketCommunicationsInc/astro-components/commit/44f88d9c2b736b4523366857ac1204e84184c69d
  - input.css
  - theme--dark
  - theme--light

**Designs**
  - [Dark](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/e4eee8e2-20a2-4977-a7b1-c2d4e6af22ad/files/1d17329d-e1a3-490a-a6ad-097e2ecd4825?filter=changed&s=input)
  - [Light](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/e4eee8e2-20a2-4977-a7b1-c2d4e6af22ad/files/b7c2bf0c-9dec-4b07-96d4-ead85393c9d0?filter=changed&s=input)

2020-12-07 16:50 UTC, amalyah commented
This appears to be using the wrong search icon for search inputs. Do you have access to the other search icon file?

2020-12-07 16:59 UTC, amalyah requested changes
Pending answer from Carmen

2020-12-07 16:59 UTC, amalyah commented on src/css/common/_theme--dark.css
> +  --inputFocusBoxShadow: inset 0 0 0 1px var(--primary),
We don't have any shadows in the design files on this component.  @carmenparks Do you want to keep or throw out the Focus Box Shadow for inputs on focus?

2020-12-07 18:34 UTC, im-cr commented
> This appears to be using the wrong search icon for search inputs. Do you have access to the other search icon file?

can we attached the correct icon file to the dev ticket. https://rocketcom.atlassian.net/browse/ASTRO-942

2020-12-07 19:38 UTC, amalyah commented
> > This appears to be using the wrong search icon for search inputs. Do you have access to the other search icon file?
> 
> @amalyah can we attached the correct icon file to the dev ticket. https://rocketcom.atlassian.net/browse/ASTRO-942

Attached to ticket

2020-12-07 19:39 UTC, amalyah requested changes
Needs search icon attached to dev ticket. Need answer from Visual Design regarding shadow.

2020-12-07 21:21 UTC, carmenparks commented on src/css/common/_theme--dark.css
> +  --inputFocusBoxShadow: inset 0 0 0 1px var(--primary),
With the updated library, we've been removing shadows on components, so let's throw it out here.

2020-12-08 14:53 UTC, amalyah requested changes
Sorry, remove shadows and update search icon and approved by me.

2020-12-08 14:53 UTC, amalyah commented on src/css/common/_theme--dark.css
> +  --inputFocusBoxShadow: inset 0 0 0 1px var(--primary),
@im-cr The verdict from Carmen is throw out component shadows.

2020-12-08 14:53 UTC, amalyah commented on src/css/common/_theme--light.css
>    --inputFocusBoxShadow: none;
This one is none, but would it be better to just remove the shadow altogether?

2020-12-08 16:38 UTC, amalyah requested changes
-- (accidental extra review) --

2020-12-08 16:42 UTC, im-cr commented on src/css/common/_theme--light.css
>    --inputFocusBoxShadow: none;
yes

2020-12-08 17:20 UTC, im-cr commented
@amalyah  can you confirm search icon is correct now. Also, on light theme search icon had a color value of #005a92. This isn't represented in the light theme color values.

2020-12-08 17:43 UTC, amalyah commented
> @amalyah can you confirm search icon is correct now. Also, on light theme search icon had a color value of #005a92. This isn't represented in the light theme color values.

Icon is the correct image now. @carmenparks, can you weigh in on the appropriate size of the search icon vs. the clear icon and the spacing between the search icon and the text?

Checking the latest master design files, on light and dark theme, the search icon should be primary-dark.

2020-12-08 18:02 UTC, amalyah requested changes

2020-12-08 18:02 UTC, amalyah commented on static/css/astro.core.css
>    box-shadow: inset 0 0 3px var(--colorGray);
If it matters, this can also be updated to a newer color variable

2020-12-08 18:02 UTC, amalyah commented on static/css/astro.core.css
>    box-shadow: inset 0 0 3px rgb(204, 204, 204);
If this is a normal shadow, I believe that @carmenparks would like it removed.

2020-12-08 18:31 UTC, im-cr commented on static/css/astro.core.css
>    box-shadow: inset 0 0 3px rgb(204, 204, 204);
box-shadows removed

2020-12-08 19:08 UTC, im-cr commented on static/css/astro.core.css
>    box-shadow: inset 0 0 3px var(--colorGray);
box shadows removed

2020-12-08 19:08 UTC, im-cr commented
@carmenparks can you confirm icon style/visuals

2020-12-08 19:24 UTC, carmenparks commented
> > @amalyah can you confirm search icon is correct now. Also, on light theme search icon had a color value of #005a92. This isn't represented in the light theme color values.
> 
> Icon is the correct image now. @carmenparks, can you weigh in on the appropriate size of the search icon vs. the clear icon and the spacing between the search icon and the text?
> 
> Checking the latest master design files, on light and dark theme, the search icon should be primary-dark.

@amalyah I'm not sure if this is what you're asking, but the icons should match how it's depicted in the Sketch library.
Search icon: 15 x 15px
Clear icon: 11 x 11px
Spacing between Search icon and text: 10px

2020-12-08 23:05 UTC, im-cr commented on src/css/core/input.css
>    color: black;
text color variable created and update for dark/light

2020-12-08 23:47 UTC, cskerbo approved these changes

2020-12-09 13:31 UTC, im-cr commented
@carmenparks those icons are in place. please confirm via the link below:

- https://deploy-preview-42--astro-components.netlify.app/?path=/story/components-form-elements--input-fields

2020-12-09 14:10 UTC, carmenparks commented
> @carmenparks those icons are in place. please confirm via the link below:
> 
> * https://deploy-preview-42--astro-components.netlify.app/?path=/story/components-form-elements--input-fields

Looks good @im-cr

2020-12-09 14:10 UTC, carmenparks approved these changes

2020-12-09 14:27 UTC, merged