V2:Astro-946 - Popup KM Styles update
RocketCommunicationsInc/astro-components pull request #43
Opened 2020-12-04 15:34 UTC by im-cr

**Tickets**
  - https://rocketcom.atlassian.net/browse/ASTRO-946

**Changes** - commit: https://github.com/RocketCommunicationsInc/astro-components/commit/09dc6215e3a5d89588542d8a0f6a9171327b4b26
  - rux-pop-up.js
  - pop-up.css
  - theme--dark
  - theme--light

**Designs**
  - [Dark](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/815a2a91-3715-4151-8575-f9382f3e2946/files/b7c2bf0c-9dec-4b07-96d4-ead85393c9d0?filter=changed&s=pop)
  - [Light](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/815a2a91-3715-4151-8575-f9382f3e2946/files/b7c2bf0c-9dec-4b07-96d4-ead85393c9d0?filter=changed&s=pop)

2020-12-04 23:15 UTC, dmcalester requested changes
Cortney this isn’t a real request for change. I think the design might be in error, but putting a hold on this for now

2020-12-04 23:15 UTC, dmcalester commented on src/css/common/_theme--light.css
> +  --popupMenuItemHoverBackgroundColor: var(--primaryLight);
Sketch Doc show Primary for hover state. I think this will likely change so de-prioritize in favor of other PRs

2020-12-05 01:05 UTC, im-cr commented on src/css/common/_theme--light.css
> +  --popupMenuItemHoverBackgroundColor: var(--primaryLight);
@dmcalester @amalyah using this is reference for hover in light theme. It shows the hover state with primaryLight/2f7aa7. Is this correct?

https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/bba22ad9-950c-4122-ad49-a0f29e96f263/commits/1154da9f75b98239949e9f1f818ea7230a103c80/files/b7c2bf0c-9dec-4b07-96d4-ead85393c9d0/layers/CF1FF015-B6B8-44F0-A0BF-224BCA9F62B1

2020-12-07 17:41 UTC, amalyah commented on src/css/common/_theme--light.css
> +  --popupMenuItemHoverBackgroundColor: var(--primaryLight);
Light theme should be primary dark for hover state. Dark theme should be primary light for hover state. These are both true in the Master files now.
https://share.goabstract.com/3aa86ec9-c6d1-41de-aa9f-863302d7e9cc

2020-12-07 19:08 UTC, im-cr commented on src/css/common/_theme--light.css
> +  --popupMenuItemHoverBackgroundColor: var(--primaryLight);
@amalyah @dmcalester updated

2020-12-07 19:14 UTC, amalyah commented on src/css/common/_theme--light.css
> +  --popupMenuItemHoverBackgroundColor: var(--primaryLight);
Light theme hover should be primary light. Dark theme hover should be primary dark. See Master for latest designs.
https://share.goabstract.com/cb65486d-f7c8-42be-84fe-95c18f7505e5?sha=0c5cc334256157d9b0fbf9a1f6adf801c4ca2145

2020-12-07 19:19 UTC, im-cr commented on src/css/common/_theme--light.css
> +  --popupMenuItemHoverBackgroundColor: var(--primaryLight);
@amalyah updated

2020-12-07 19:42 UTC, amalyah requested changes
Font change request can be ignored if we're handling that later. Otherwise, apologies for the opposite answers regarding hover colors. The actual colors for hover are light for dark theme and dark for light theme.

2020-12-07 19:42 UTC, amalyah commented on src/css/components/pop-up.css
>    font-size: 0.875rem;
1 rem for text in pop ups now

2020-12-07 19:53 UTC, im-cr commented on src/css/components/pop-up.css
>    font-size: 0.875rem;
updated in css and component

2020-12-07 20:17 UTC, cskerbo approved these changes

2020-12-08 16:50 UTC, amalyah approved these changes

2020-12-08 17:22 UTC, merged