V2:Astro-920 - Slider KM style update
RocketCommunicationsInc/astro-components pull request #44
Opened 2020-12-04 15:52 UTC by im-cr

**Tickets**
  - 920: https://rocketcom.atlassian.net/browse/ASTRO-920

**Changes** - commit: https://github.com/RocketCommunicationsInc/astro-components/commit/db005f82009cb8927c4ff92947f5276a1c3718dc
  - rux-slider.js
  - slider.css
  - theme--light
  - theme--dark

**Designs**
  - [Dark](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/90456599-f0d6-4a10-8d8b-cd03a0f37381/files/1d17329d-e1a3-490a-a6ad-097e2ecd4825?filter=changed)
  - [Light](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/90456599-f0d6-4a10-8d8b-cd03a0f37381/files/b7c2bf0c-9dec-4b07-96d4-ead85393c9d0?filter=changed)

2020-12-04 23:35 UTC, dmcalester requested changes
Please review Sketch doc for color properties, I found several inconsistencies, but there may be more

2020-12-04 23:35 UTC, dmcalester commented on src/css/common/_theme--dark.css
>    --sliderThumbBorderColor: var(--colorWhite);
--inputBackground

2020-12-04 23:35 UTC, dmcalester commented on src/css/common/_theme--light.css
>    --sliderThumbBackgroundColor: var(--primary);
--primaryDark

2020-12-04 23:35 UTC, dmcalester commented on src/css/common/_theme--light.css
>    --sliderThumbBorderColor: var(--colorWhite);
--inputBackground

2020-12-04 23:35 UTC, dmcalester commented on src/css/common/_theme--light.css
>    --sliderTrackBackgroundColor: var(--colorWhite);
--inputBackground

2020-12-04 23:35 UTC, dmcalester commented on src/css/common/_theme--light.css
>    --sliderTrackBorderColor: var(--colorQuaternary);
--secondaryText

2020-12-05 01:23 UTC, im-cr commented
@dmcalester values updated

2020-12-07 19:57 UTC, amalyah requested changes
Question for Carmen, some color change requests. Also, in this branch, the thumb appears to be floating below the slider track.

2020-12-07 19:57 UTC, amalyah commented on src/components/rux-slider/rux-slider.js
> +          font-family: var(--fontFamilyMono);
@carmenparks Do you want the numbers under slider components to be Roboto Mono or Roboto?

2020-12-07 19:57 UTC, amalyah commented on src/css/common/_theme--dark.css
>    --sliderTrackBackgroundColor: var(--colorGray);
Does --colorGray match up with the same value as the Secondary Text color in the design files?

2020-12-07 19:57 UTC, amalyah commented on src/css/common/_theme--dark.css
> +  --sliderThumbBorderColor: var(--inputBackground);
Not sure what line this is on in the code, but the border around the thumb pressed slider part (the circle) should be primary light, not primary.

2020-12-07 19:57 UTC, amalyah commented on src/css/common/_theme--light.css
> +  --sliderTrackBorderColor: var(--secondaryText);
If it isn't already, could we change the border width for the light theme to 0.25 width.

2020-12-07 19:57 UTC, amalyah commented on src/css/common/_theme--light.css
> +	--sliderHoverThumbBackgroundColor: var(--primary);
On select, the border should be primaryLight

2020-12-07 19:57 UTC, amalyah commented on src/css/components/slider.css
> +  --thumbShadowActive: inset 0 0 0 4px var(--colorPrimary),
@carmenparks We don't have any shadows here in the design files. Would you like to keep or get rid of the shadows on  the active slider thumb?

2020-12-07 21:23 UTC, carmenparks commented on src/components/rux-slider/rux-slider.js
> +          font-family: var(--fontFamilyMono);
So far we only use Roboto Mono on the Clock/Date/Time component, so until we decide it makes sense on something else too, I'd like to continue to use Roboto on the other Patterns.

2020-12-07 21:23 UTC, carmenparks commented on src/css/components/slider.css
> +  --thumbShadowActive: inset 0 0 0 4px var(--colorPrimary),
Would like to remove shadows, please.

2020-12-07 22:01 UTC, im-cr commented on src/css/common/_theme--light.css
> +  --sliderTrackBorderColor: var(--secondaryText);
@amalyah .25 rem or 25px? variable has been added to themes

2020-12-07 22:02 UTC, im-cr commented on src/css/common/_theme--dark.css
> +  --sliderThumbBorderColor: var(--inputBackground);
@amalyah updated

2020-12-07 22:02 UTC, im-cr commented on src/css/common/_theme--dark.css
>    --sliderTrackBackgroundColor: var(--colorGray);
@amalyah  believe it did, but has been updated to secondary

2020-12-07 22:05 UTC, im-cr commented on src/css/components/slider.css
> +  --thumbShadowActive: inset 0 0 0 4px var(--colorPrimary),
@amalyah this style declaration is what creates the the center white dot when the input range is selected. It's not adding a box shadow to the overall element

2020-12-07 22:33 UTC, cskerbo approved these changes

2020-12-08 16:53 UTC, amalyah commented on src/css/common/_theme--light.css
> +  --sliderTrackBorderColor: var(--secondaryText);
Sorry, 0.25 px width. That's what we have in the design files and sometimes I forget to add a unit. >_<

2020-12-08 17:11 UTC, amalyah requested changes

2020-12-08 17:11 UTC, amalyah commented on src/components/rux-slider/rux-slider.js
>            opacity: var(--disabledOpacity, 0.4);
Is there a reason to keep the 0.4 mentioned explicitly here instead of just using the variable as defined elsewhere?

2020-12-08 17:11 UTC, amalyah commented on src/components/rux-slider/rux-slider.js
> +          font-family: var(--fontFamilyMono);
@im-cr Please change the font for the slider to be normal body font (Roboto).

2020-12-08 17:11 UTC, amalyah commented on src/css/components/slider.css
>    --thumbShadowHover: 0 6px 10px rgba(0, 0, 0, 0.14),
Are any of these shadows necessary to portray the new visual design of the sliders? (Carmen is getting rid of shadows in general in the visual designs.)

2020-12-08 17:11 UTC, amalyah commented on src/css/components/slider.css
>    box-shadow: inset 0 0 1px 0 rgba(255, 255, 255, 0.9), var(--thumbShadow);
Change to color variable if the shadow is necessary for non-traditional shadow purposes.

2020-12-08 17:11 UTC, amalyah commented on src/css/components/slider.css
>    box-shadow: inset 0 0 1px 0 rgba(255, 255, 255, 0.9), var(--thumbShadow);
Same box-shadow comment

2020-12-08 17:11 UTC, amalyah commented on src/css/components/slider.css
>    background-color: rgb(0, 90, 143);
Can we use a color variable instead?

2020-12-08 17:11 UTC, amalyah commented on src/css/components/slider.css
>      0 1px 3px rgba(0, 0, 0, 0.2);
Can we use a color variable instead?

2020-12-08 17:11 UTC, amalyah commented on static/css/astro.core.css
> +	--borderThumbSize: .25px;
Is there a reason that this ThumbSize is .25px but the one further down in light theme is 1px?

2020-12-08 17:29 UTC, im-cr commented on src/components/rux-slider/rux-slider.js
>            box-shadow: inset 0 0 1px 0 rgba(255, 255, 255, 0.9), var(--thumbShadow);
@amalyah yep, the 'thumbShadow' variables.

2020-12-08 17:32 UTC, im-cr commented on src/components/rux-slider/rux-slider.js
>            box-shadow: var(--thumbShadowActive);
@amalyah yes

2020-12-08 17:35 UTC, im-cr commented on src/components/rux-slider/rux-slider.js
>            box-shadow: inset 0 0 1px 0 rgba(255, 255, 255, 0.9), var(--thumbShadow);
@amalyah yes

2020-12-08 18:09 UTC, im-cr commented on src/components/rux-slider/rux-slider.js
>            background-color: rgb(0, 90, 143);
@amalyah weird, must have gotten overwritten, fix coming

2020-12-08 18:09 UTC, im-cr commented on src/components/rux-slider/rux-slider.js
>            color: var(--fontColor, #fff);
removed

2020-12-08 18:11 UTC, im-cr commented on src/css/components/slider.css
>    box-shadow: inset 0 0 1px 0 rgba(255, 255, 255, 0.9), var(--thumbShadow);
Thumb shadow isn't just a color declaration, it sets the the box shadow values and uses some transparency settings as well. I'd recommend leaving this as is for now.

2020-12-08 18:23 UTC, im-cr commented on src/css/components/slider.css
>      0 1px 3px rgba(0, 0, 0, 0.2);
@amalyah same box shadow comment from above

2020-12-08 18:23 UTC, im-cr commented on src/components/rux-slider/rux-slider.js
> +          font-family: var(--fontFamilyMono);
updated

2020-12-08 19:59 UTC, amalyah commented on static/css/astro.core.css
> +	--borderThumbSize: .25px;
Sorry, the border I meant was on the track border, not the thumb border, for light theme.

2020-12-08 20:11 UTC, amalyah requested changes

2020-12-08 20:11 UTC, amalyah commented on src/css/common/_theme--light.css
> +	--borderThumbSize: .25px;
If I'm reading this correctly, it looks like the .25px was applied to the thumb border instead of the track border. Is that accurate? If yes, then please apply that value to the track border in light theme instead of the thumb border.

2020-12-08 20:11 UTC, im-cr commented on static/css/astro.core.css
> +	--borderThumbSize: .25px;
Sorry, updated on track border for light theme. added some additional variable to handle thumb and track size.

2020-12-08 20:33 UTC, amalyah requested changes

2020-12-08 20:33 UTC, amalyah commented on src/css/components/slider.css
>    --thumbShadowHover: 0 6px 10px rgba(0, 0, 0, 0.14),
Deprioritized

2020-12-08 20:33 UTC, amalyah commented on src/css/components/slider.css
>    background-color: rgb(0, 90, 143);
Needs to be converted to slider thumb background color.

2020-12-08 20:46 UTC, im-cr commented on src/css/common/_theme--light.css
> +  --sliderTrackBorderColor: var(--secondaryText);
updated

2020-12-08 21:22 UTC, amalyah requested changes
Also, still seeing the slider thumb as below the track instead of on top of it. (Chrome)

2020-12-08 21:22 UTC, amalyah commented on src/css/components/slider.css
>    opacity: 0.4;
In case this is something that should be a variable as well, commenting on another 0.4 opacity in non-variable code.

2020-12-08 21:22 UTC, amalyah commented on src/components/rux-slider/rux-slider.js
>            opacity: var(--disabledOpacity, 0.4);
Still seeing this issue

2020-12-08 21:43 UTC, im-cr commented on src/css/components/slider.css
>    opacity: 0.4;
yes it can be. Some instances, if the hardcoded value matches the default variables.

2020-12-08 21:43 UTC, im-cr commented on src/css/components/slider.css
>    opacity: 0.4;
updated

2020-12-08 22:06 UTC, amalyah requested changes
CSS file changes approved, but Chrome v87 still sees the thumb as offset below the track (not true in v86).

2020-12-08 22:41 UTC, amalyah approved these changes

2020-12-08 22:43 UTC, merged