V2:Astro-923 - Scroll Bar KM Style update
RocketCommunicationsInc/astro-components pull request #45
Opened 2020-12-04 16:58 UTC by im-cr

**Tickets**
 - https://rocketcom.atlassian.net/browse/ASTRO-923

**Changes** - commit: 
 - global.css
 - theme-dark
 - theme-light

2020-12-04 23:43 UTC, dmcalester commented on src/css/common/_theme--dark.css
> +  --scrollBarTrackBackgroundColor: var(--colorGray);
--backgroundColor

2020-12-04 23:43 UTC, dmcalester commented on src/css/common/_theme--dark.css
> +  --scrollBarTrackCornerBackgroundColor: var(--colorGray);
--backgroundColor

2020-12-04 23:45 UTC, dmcalester commented on src/css/common/_theme--dark.css
> +  --scrollBarThumbBackgroundHoverColor: var(--primaryDark);
--primaryLight

Note: this may change after design discussion. Feel free to deprioritize in favor of more concrete requested changes.

2020-12-04 23:49 UTC, dmcalester commented on src/css/common/_theme--light.css
>    --scrollBarTrackBackgroundColor: transparent;
--backgroundColor

2020-12-04 23:49 UTC, dmcalester commented on src/css/common/_theme--light.css
>    --scrollBarTrackBackgroundColor: transparent;
--backgroundColor

2020-12-04 23:50 UTC, dmcalester requested changes
Dark theme had some light theme vars associated. Light theme needed updating per Sketch/Abstract

2020-12-07 20:03 UTC, amalyah requested changes
Dark theme scrollbar appears to be using light theme colors.  Should be background color with primary dark border for the track and primary blue for the scrollbar.

2020-12-09 14:16 UTC, im-cr commented
> Dark theme scrollbar appears to be using light theme colors. Should be background color with 0.25 primary dark border for the track and primary blue for the scrollbar.
> 
> Light theme needs to use updated colors too. Bar should be primary and track should be background color with primary dark borders at 0.25 width.

@amalyah color values swapped and border added via box-shadow. let me know if you have any concerns around this.

2020-12-09 15:00 UTC, amalyah requested changes

2020-12-09 15:07 UTC, im-cr commented on src/css/common/_theme--light.css
> +  --fontColor: var(--defaultText);
let make a separe ticket and we can update the A5 colors there. I'll add to the clean up branch

2020-12-09 15:10 UTC, im-cr commented on src/css/common/_theme--light.css
> +	--scrollBarTrackBackgroundColor:var(--backgroundColor);
@amalyah not seeing this. can you add a screenshot or we can get on a call.

2020-12-09 15:11 UTC, im-cr commented on src/css/common/_theme--light.css
> +	--scrollBarThumbBorderColor: var(--primaryDark);
removed

2020-12-09 15:11 UTC, im-cr commented on src/css/common/_theme--dark.css
> +	--scrollBarThumbBorderColor: var(--primaryDark);
removed

2020-12-09 15:12 UTC, im-cr commented on src/css/common/_theme--dark.css
> +  --fontLinkHoverColor: var(--colorSecondaryLighten1);
answered below

2020-12-09 15:23 UTC, amalyah commented on src/css/common/_theme--light.css
> +  --fontColor: var(--defaultText);
https://rocketcom.atlassian.net/browse/ASTRO-1054

2020-12-09 15:46 UTC, amalyah requested changes

2020-12-09 15:46 UTC, amalyah commented on src/css/common/_theme--light.css
> +	--scrollBarTrackBackgroundColor:var(--backgroundColor);
https://deploy-preview-45--astro-components.netlify.app/?path=/story/astro-uxds-welcome--contributing

2020-12-09 16:10 UTC, im-cr commented
@amalyah preview track fixed/updated

2020-12-09 16:16 UTC, amalyah approved these changes

2020-12-09 16:27 UTC, im-cr commented
@dmcalester @cskerbo need secondary approval for merge

2020-12-09 16:30 UTC, cskerbo approved these changes

2020-12-09 16:34 UTC, merged