V2:Astro-926 - Update to toggle KM Styles
RocketCommunicationsInc/astro-components pull request #46
Opened 2020-12-04 21:35 UTC by im-cr

**Tickets**
  - https://rocketcom.atlassian.net/browse/ASTRO-926

**Changes**
 - theme-dark
 - theme-light
 - toggle.css
 - rux-toggle.js

**Designs**
  - [Dark](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/4982f2f9-69bc-4f22-a731-6cfacfc4cc52/files/1d17329d-e1a3-490a-a6ad-097e2ecd4825?filter=changed)
  - [Light](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/4982f2f9-69bc-4f22-a731-6cfacfc4cc52/files/b7c2bf0c-9dec-4b07-96d4-ead85393c9d0?filter=changed)

2020-12-07 20:20 UTC, amalyah requested changes
Some colors changes and code structure questions

2020-12-07 20:20 UTC, amalyah commented on src/css/common/_theme--dark.css
>    /* Disabled State */
Shouldn't disabled state just be an opacity difference visually?

2020-12-07 20:20 UTC, amalyah commented on src/css/common/_theme--dark.css
> +  --toggleSelectedThumbBorderColor:var(--primary);
Should be primary dark instead for now

2020-12-07 20:20 UTC, amalyah commented on src/css/common/_theme--dark.css
> +  --toggleSelectedTrackBorderColor: var(--primary);
Should be primary dark according to designs

2020-12-07 20:20 UTC, amalyah commented on src/css/common/_theme--dark.css
>    /* Alt Toggle */
Which piece of code is the non-selected state? I see Alt Toggle and then another set above that.

2020-12-07 20:20 UTC, amalyah commented on src/css/common/_theme--dark.css
>    --toggleThumbBorderColor: var(--defaultText);
Change to secondary text color

2020-12-07 20:20 UTC, amalyah commented on src/css/common/_theme--light.css
> +  --toggleDisabledThumbBorderColor: var(--secondaryText);
Same comment as dark library. Why not just an opacity change for disabled?

2020-12-07 20:20 UTC, amalyah commented on src/css/common/_theme--light.css
> +  --toggleSelectedThumbBackgroundColor: var(--primary);
This looks like a duplicate of line 212 and 213?

2020-12-07 20:20 UTC, amalyah commented on src/css/common/_theme--light.css
> +  /* Default Toggle */
Is there a reason that it's called Default Toggle here and Alt Toggle in the dark theme CSS?

2020-12-07 20:20 UTC, amalyah commented on src/css/common/_theme--light.css
> +	--toggleThumbBackgroundColor: var(--backgroundColor);
This should be input background color instead

2020-12-07 20:20 UTC, amalyah commented on src/css/common/_theme--light.css
> +  --toggleButtonBackgroundColor: var(--primary);
What is this line for? There are no backgrounds in the toggle button that uses the  primary color in light theme.

2020-12-07 20:20 UTC, amalyah commented
Does this component have a hover state? If not, we'll probably need to design this later. Just wanted to check.

2020-12-07 20:48 UTC, im-cr commented on src/css/common/_theme--dark.css
>    /* Disabled State */
The opacity value is handled in the component css. colors are still set in the theme css.

2020-12-07 20:50 UTC, im-cr commented on src/css/common/_theme--dark.css
> +  --toggleSelectedThumbBorderColor:var(--primary);
updated

2020-12-07 20:50 UTC, im-cr commented on src/css/common/_theme--dark.css
> +  --toggleSelectedTrackBorderColor: var(--primary);
updated

2020-12-07 20:51 UTC, im-cr commented on src/css/common/_theme--dark.css
>    /* Alt Toggle */
@amalyah 169 -172 is the default 'non-selected' state

2020-12-07 20:53 UTC, im-cr commented on src/css/common/_theme--light.css
> +  --toggleDisabledThumbBorderColor: var(--secondaryText);
opacity handled in toggle.css, colors still set in component theme files

2020-12-07 20:59 UTC, im-cr commented on src/css/common/_theme--light.css
> +  /* Default Toggle */
@amalyah  updated to match

2020-12-07 21:00 UTC, im-cr commented on src/css/common/_theme--light.css
> +  --toggleSelectedThumbBackgroundColor: var(--primary);
@amalyah I believe one set is for the thumb styling and the other is for the track. Also in some instances variables may be declared in the the theme css files but not used in the component css files.

2020-12-07 21:00 UTC, im-cr commented on src/css/common/_theme--dark.css
>    --toggleThumbBorderColor: var(--defaultText);
@amalyah updated

2020-12-07 21:03 UTC, im-cr commented on src/css/common/_theme--light.css
> +  --toggleButtonBackgroundColor: var(--primary);
@amalyah not totally sure, these declarations aren't currently used toggle.css. Updated but didn't remove incase they impact another area.

2020-12-07 21:10 UTC, im-cr commented
> Does this component have a hover state? If not, we'll probably need to design this later. Just wanted to check.

@amalyah not currently, only seeing default/selected/disabled

2020-12-07 21:59 UTC, cskerbo approved these changes

2020-12-08 19:51 UTC, im-cr commented
> Does this component have a hover state? If not, we'll probably need to design this later. Just wanted to check.

not currently

2020-12-08 19:51 UTC, im-cr commented
@amalyah is this component ready for approval?

2020-12-08 21:04 UTC, amalyah requested changes
See comments and questions.

Side note: Checked knob does not appear to be working on Storybook. Let me know  if you would prefer me to create a bug ticket to deal with this later.

2020-12-08 21:04 UTC, amalyah commented on src/css/common/_theme--dark.css
> +  --toggleBaseBorderColor: var(--primary);
Is this variable in use? I don't know what this is affecting since there aren't any primary borders that I can see.

2020-12-08 21:04 UTC, amalyah commented on src/css/common/_theme--dark.css
> +  --toggleBaseBackgroundColor: var(--primary);
What is the difference between the Button and Base Background?

2020-12-08 21:09 UTC, amalyah commented
> > Does this component have a hover state? If not, we'll probably need to design this later. Just wanted to check.
> 
> @amalyah not currently, only seeing default/selected/disabled

https://rocketcom.atlassian.net/browse/ASTRO-838

2020-12-08 23:08 UTC, im-cr commented on src/css/common/_theme--dark.css
> +  --toggleBaseBackgroundColor: var(--primary);
@amalyah none of the 'toggleBase*' variables are used in toggle.css or rux-toggle.

2020-12-08 23:08 UTC, im-cr commented on src/css/common/_theme--dark.css
> +  --toggleBaseBorderColor: var(--primary);
@amalyah no

2020-12-08 23:18 UTC, im-cr commented
@amalyah disabled opacity isn't applied to toggle thumb in this case, only disable cursor. Because we are using pseudo-selectors to generate those elements reduced opacity on both cause an overlapping issue.

2020-12-09 14:39 UTC, im-cr commented on src/css/common/_theme--dark.css
>    --toggleBaseSelectedTextColor: var(--colorNormal);
@amalyah none of the 'toggleBase..*' variables are in use. Just declared in the theme files.

2020-12-09 14:40 UTC, im-cr commented on src/css/common/_theme--dark.css
>    /* --toggleThumbBorderColor: var(--colorGrayDarken2); */
no need comment removed though

2020-12-09 15:14 UTC, amalyah commented
> @amalyah disabled opacity isn't applied to toggle thumb in this case, only disable cursor. Because we are using pseudo-selectors to generate those elements reduced opacity on both cause an overlapping issue.
> 
> ![toggle-disabled](https://user-images.githubusercontent.com/1438061/101553043-f93cae00-3981-11eb-91e5-0f2c6b15ed89.png)

That's unfortunate. In that case, would it be easier/better to make additional color variables to mimic the disabled states for  the thumbs or to add a 100% opacity surface color circle behind the thumb, so the thumb can just use opacity like normal?

2020-12-09 15:16 UTC, amalyah requested changes
Need to work out the disabled state

2020-12-09 15:16 UTC, amalyah commented on src/css/common/_theme--dark.css
>    /* Disabled State */
Addressing in general comments

2020-12-09 15:16 UTC, amalyah commented on src/css/common/_theme--light.css
> +  --toggleDisabledThumbBorderColor: var(--secondaryText);
See general comments

2020-12-09 15:35 UTC, im-cr commented
> Need to work out the disabled state

@amalyah fixed

2020-12-09 15:57 UTC, amalyah requested changes

2020-12-09 15:57 UTC, amalyah commented on src/css/common/_theme--dark.css
>    --toggleThumbBorderColor: var(--defaultText);
Doesn't look like this was updated here.

2020-12-09 15:57 UTC, amalyah commented on src/css/common/_theme--dark.css
> +  --toggleSelectedThumbBorderColor:var(--primary);
Not seeing this  update.

2020-12-09 15:57 UTC, amalyah commented on src/css/common/_theme--dark.css
> +  --toggleSelectedTrackBorderColor: var(--primary);
Not seeing this change

2020-12-09 15:57 UTC, amalyah commented on src/css/common/_theme--light.css
> +	--toggleThumbBackgroundColor: var(--backgroundColor);
Not seeing this change

2020-12-09 16:14 UTC, im-cr commented
@amalyah the item has been updated

2020-12-09 16:23 UTC, amalyah approved these changes

2020-12-09 16:27 UTC, merged