V2:astro-944 - Select Dropdown KM Style update
RocketCommunicationsInc/astro-components pull request #47
Opened 2020-12-04 22:11 UTC by im-cr

**Tickets**
  - https://rocketcom.atlassian.net/browse/ASTRO-944

**Changes**
  - drop-down.css
  - theme--dark
  - theme--light

**Designs**
  - [Dark](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/e4eee8e2-20a2-4977-a7b1-c2d4e6af22ad/files/1d17329d-e1a3-490a-a6ad-097e2ecd4825?filter=changed&s=drop)
  - [Light](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/e4eee8e2-20a2-4977-a7b1-c2d4e6af22ad/files/b7c2bf0c-9dec-4b07-96d4-ead85393c9d0?filter=changed)

2020-12-07 20:23 UTC, amalyah commented
Do we control any of the select menu pop up styling? Like the hover state or background colors?

2020-12-07 20:32 UTC, amalyah requested changes

2020-12-07 20:32 UTC, amalyah commented on src/css/common/_theme--dark.css
> +	--selectTextColor: var(--defaultText);
Change to primary element font color

2020-12-07 20:32 UTC, amalyah commented on src/css/common/_theme--dark.css
> +	--selectHoverOptBackgroundColor: var(--primaryLight);
I'm not seeing these Opt colors applied in the Storybook demo. Did we not hook something up correctly?

2020-12-07 20:32 UTC, amalyah commented on src/css/common/_theme--dark.css
> +	--selectOptBackground: var(--inputBackground);
Is there a way to have the pop up menu not cover the original select menu control?

2020-12-07 20:32 UTC, amalyah commented on src/css/common/_theme--light.css
> +	--selectBackgroundColor: var(--inputBackground);
Needs to be primary

2020-12-07 20:32 UTC, amalyah commented on src/css/common/_theme--light.css
> +  --selectBorderColor: var(--primaryLight);
primary

2020-12-07 20:32 UTC, amalyah commented on src/css/common/_theme--light.css
> +	--selectTextColor: var(--defaultText);
Primary element font color

2020-12-07 20:32 UTC, amalyah commented on src/css/common/_theme--light.css
> +	--selectHoverOptBackgroundColor: var(--primaryLight);
primaryDark

2020-12-07 20:32 UTC, amalyah commented on src/css/common/_theme--light.css
>    /*
Pop up menu covers the original control. Can we fix this?

2020-12-07 20:32 UTC, amalyah commented on src/css/common/_theme--light.css
> +	--selectHoverOptBackgroundColor: var(--primaryLight);
Not seeing the Opt colors in practice. I suspect I'm seeing the default select menu from my Chrome browser instead.

2020-12-07 22:41 UTC, cskerbo approved these changes

2020-12-07 22:42 UTC, dmcalester commented
> Do we control any of the select menu pop up styling? Like the hover state or background colors?

No

2020-12-07 22:43 UTC, dmcalester commented on src/css/common/_theme--dark.css
> +	--selectOptBackground: var(--inputBackground);
Nope. That’s a browser/OS thing

2020-12-08 19:45 UTC, im-cr commented on src/css/common/_theme--light.css
> +	--selectHoverOptBackgroundColor: var(--primaryLight);
updated

2020-12-08 19:45 UTC, im-cr commented on src/css/common/_theme--light.css
> +	--selectTextColor: var(--defaultText);
updated

2020-12-08 19:46 UTC, im-cr commented on src/css/common/_theme--light.css
> +	--selectHoverOptBackgroundColor: var(--primaryLight);
the default opt color background is displayed but since we are using the select element and not a UL/LI the hover state background is not display, we would need additional dev work on this component. 


@dmcalester

2020-12-08 19:49 UTC, im-cr commented on src/css/common/_theme--light.css
> +	--selectHoverOptBackgroundColor: var(--primaryLight);
It is related to the browser, there are js overrides that can handle address the update and would need to be added to the storybook comp and library. 

@dmcalester @amalyah the fix seems a bit outside of the KM update scope as there are a few ways we could could address. 1) converting select elements to UL/LI to manage hover state with css 2) us js to attach hover styles to select option items.

2020-12-08 21:31 UTC, amalyah commented on src/css/common/_theme--light.css
> +	--selectHoverOptBackgroundColor: var(--primaryLight);
Relevant ticket: https://rocketcom.atlassian.net/browse/ASTRO-675

2020-12-08 21:40 UTC, amalyah requested changes

2020-12-08 21:40 UTC, amalyah commented on src/css/common/_theme--dark.css
> +	--selectCaret: url('data:image/svg+xml,%3Csvg%20width%3D%2210%22%20height%3D%225%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cpath%20fill%3D%22%23ffffff%22%20d%3D%22M0%200h10L5%205z%
Should be primary element text color as well

2020-12-08 21:40 UTC, amalyah commented on src/css/common/_theme--light.css
> +	--selectCaret: url("data:image/svg+xml,%3Csvg%20width%3D%2210%22%20height%3D%225%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cpath%20fill%3D%22%23292A2D%22%20d%3D%22M0%200h10L5%205z%
Should be primary element text color as well

2020-12-09 00:29 UTC, dmcalester commented on src/css/common/_theme--light.css
> +	--selectHoverOptBackgroundColor: var(--primaryLight);
@im-cr agreed, well outside of KM. We won’t be replacing native elements with custom for a long time.

2020-12-09 10:33 UTC, im-cr commented on src/css/common/_theme--dark.css
> +	--selectCaret: url('data:image/svg+xml,%3Csvg%20width%3D%2210%22%20height%3D%225%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cpath%20fill%3D%22%23ffffff%22%20d%3D%22M0%200h10L5%205z%
updated

2020-12-09 10:33 UTC, im-cr commented on src/css/common/_theme--light.css
> +	--selectCaret: url("data:image/svg+xml,%3Csvg%20width%3D%2210%22%20height%3D%225%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cpath%20fill%3D%22%23292A2D%22%20d%3D%22M0%200h10L5%205z%
updated

2020-12-09 14:44 UTC, im-cr commented on src/css/common/_theme--dark.css
> +	--selectHoverOptBackgroundColor: var(--primaryLight);
answered below

2020-12-09 14:56 UTC, im-cr commented on src/css/common/_theme--light.css
> +	--selectBackgroundColor: var(--inputBackground);
updated

2020-12-09 16:12 UTC, amalyah approved these changes

2020-12-09 16:54 UTC, merged