V2:Astro-956 - Tabs KM Styles Update
RocketCommunicationsInc/astro-components pull request #48
Opened 2020-12-04 23:32 UTC by im-cr

**Tickets**
  - https://rocketcom.atlassian.net/browse/ASTRO-956

**Changes** - commit: 
  - tabs.css
  - theme-dark
  - theme-light

**Designs**
  - [Dark](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/efbff853-e518-4870-80a9-faa9fb34a4b9/files/1d17329d-e1a3-490a-a6ad-097e2ecd4825?filter=changed&s=tabs)
  - [Light](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/efbff853-e518-4870-80a9-faa9fb34a4b9/files/b7c2bf0c-9dec-4b07-96d4-ead85393c9d0?filter=changed&s=tabs)

2020-12-04 23:54 UTC, dmcalester commented on src/css/common/_theme--light.css
> +  --tabBackgroundColor: var(--inputBackground);
should be transparent

2020-12-04 23:55 UTC, dmcalester requested changes
Minor change to tab background property in light

2020-12-05 01:26 UTC, im-cr commented
@dmcalester value updated

2020-12-07 20:42 UTC, amalyah requested changes
Some color changes and structure questions

2020-12-07 20:42 UTC, amalyah commented on src/css/common/_theme--dark.css
>    --tabBorderColor: var(--globalAppHeader);
transparent

2020-12-07 20:42 UTC, amalyah commented on src/css/common/_theme--dark.css
Light theme has a hover state, but this one doesn't.
  --tabHoverTextColor: var(--defaultText);

2020-12-07 20:42 UTC, amalyah commented on src/css/common/_theme--light.css
> +  --tabBorderColor: var(--primary);
No tabBorderColor necessary for the non-selected state (or use transparent).

2020-12-07 20:42 UTC, amalyah commented on src/css/components/tabs.css
>    font-size: 1rem;
We want this to be the equivalent of an H5, so 18px equivalent in rem.

2020-12-07 20:42 UTC, amalyah commented on src/css/components/tabs.css
> +  box-shadow: inset 0 -5px 0 0 var(--tabSelectedBorderColor);
@carmenparks Another shadow. Want to keep or get rid of it? (Same in small tabs)

2020-12-07 21:28 UTC, carmenparks commented on src/css/components/tabs.css
> +  box-shadow: inset 0 -5px 0 0 var(--tabSelectedBorderColor);
Let's evict all those shadows :)

2020-12-07 22:33 UTC, im-cr commented on src/css/components/tabs.css
> +  box-shadow: inset 0 -5px 0 0 var(--tabSelectedBorderColor);
box shadows removed

2020-12-07 22:42 UTC, cskerbo approved these changes

2020-12-07 23:55 UTC, dmcalester commented on src/css/components/tabs.css
> +  box-shadow: inset 0 -5px 0 0 var(--tabSelectedBorderColor);
@im-cr please verify this box-shadow wasn’t the selected state bottom border, if it was should be replaced or use border bottom. It’s been a while since this one was originally created, but I believe there was a reason `box-shadow` was used instead of `border-bottom`. As long as it looks and behaves correctly either way is fine.

2020-12-08 23:47 UTC, im-cr commented on src/css/common/_theme--light.css
> +  --tabBorderColor: var(--primary);
updated

2020-12-08 23:49 UTC, im-cr commented on src/css/components/tabs.css
> +  box-shadow: inset 0 -5px 0 0 var(--tabSelectedBorderColor);
box-shadow for rux-tabs/rux-tab have been updated to use bottom-border

2020-12-08 23:49 UTC, im-cr commented on src/css/components/tabs.css
>    font-size: 1rem;
updated

2020-12-09 18:41 UTC, amalyah approved these changes

2020-12-09 20:00 UTC, merged