V2:Astro-960 - Log KM Style Update
RocketCommunicationsInc/astro-components pull request #50
Opened 2020-12-05 00:36 UTC by im-cr

**Tickets**
  - https://rocketcom.atlassian.net/browse/ASTRO-960

**Changes** - commit: 
  - rux-log.js
  - log.css
  - theme-dark
  - theme-light

**Designs**
  - [Dark ](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/bba22ad9-950c-4122-ad49-a0f29e96f263/files/1d17329d-e1a3-490a-a6ad-097e2ecd4825?s=log%2F)
  - [Light ](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/bba22ad9-950c-4122-ad49-a0f29e96f263/files/b7c2bf0c-9dec-4b07-96d4-ead85393c9d0?s=log%2F)

2020-12-07 20:59 UTC, amalyah commented
Quick fix: Change Search text to Search...

2020-12-07 21:18 UTC, amalyah commented
Change log header text to 1 rem

2020-12-07 21:19 UTC, amalyah commented
If you have time, could you left align the Time header label?

2020-12-07 21:35 UTC, amalyah requested changes

2020-12-07 21:35 UTC, amalyah commented on src/components/rux-log/rux-log.js
> +          font-family: var(--fontFamilyMono);
@carmenparks In the design we are using Roboto for the time stamps, but we're using roboto mono in the code. In this case, since the times need to line up in a column, I suspect that using Roboto Mono is the correct way to go. Are you okay with that change to the design?

2020-12-07 21:35 UTC, amalyah commented on src/css/common/_theme--dark.css
> +  --logFilterBackgroundColor: var(--primary);
Suggest primary-dark here instead since the bar is not actionable itself.

2020-12-07 21:35 UTC, amalyah commented on src/css/common/_theme--dark.css
> +  --logFilterTextColor: var(--defaultText);
primary element font color

2020-12-07 21:35 UTC, amalyah commented on src/css/common/_theme--light.css
> +  --logBackgroundColor: var(--inputBackground);
surface element color

2020-12-07 21:35 UTC, amalyah commented on src/css/common/_theme--light.css
> +  --logBorderColor: var(--backgroundColor);
secondary text

2020-12-07 21:35 UTC, amalyah commented on src/css/common/_theme--light.css
> +  --logFilterBackgroundColor: var(--primary);
Let's try primary light instead since this bar isn't actionable.

2020-12-07 21:35 UTC, amalyah commented on src/css/common/_theme--light.css
> +  --logHeaderBackgroundColor: var(--backgroundColor);
+headerBorder: secondary text color

2020-12-07 21:35 UTC, amalyah commented on src/css/common/_theme--dark.css
>    --logHeaderBackgroundColor: var(--globalAppHeader);
+headerBorder: background color

2020-12-07 21:42 UTC, carmenparks commented on src/components/rux-log/rux-log.js
> +          font-family: var(--fontFamilyMono);
This is a tough one, I'm inclined to say it should be Roboto even tough it's denoted 'time' because it's within the Log component. That would be my suggestion but would like @dmcalester to weigh in here.

2020-12-08 20:48 UTC, amalyah requested changes
- Quick fix: Change Search text to Search...
- Change log header and body text to 1 rem

2020-12-08 20:59 UTC, im-cr commented on src/components/rux-log/rux-log.js
> +          font-family: var(--fontFamilyMono);
updated

2020-12-08 21:16 UTC, im-cr commented
@amalyah font size and search tex updated

2020-12-08 22:34 UTC, amalyah commented on src/css/common/_theme--dark.css
> +  --logFilterBackgroundColor: var(--primary);
That will work for now. We've got some other tickets out to look into general table pattern filtering in more depth later: https://rocketcom.atlassian.net/browse/ASTRO-931

2020-12-08 22:35 UTC, amalyah approved these changes

2020-12-08 23:49 UTC, cskerbo approved these changes

2020-12-09 10:22 UTC, merged