V2:Astro-961 - Tree KM Style Update
RocketCommunicationsInc/astro-components pull request #51
Opened 2020-12-07 14:45 UTC by im-cr

**Tickets**
  - https://rocketcom.atlassian.net/browse/ASTRO-961

**Changes** - commit: 
  - rux-tree.js
  - theme--dark
  - theme--light
  - tree.css

**Designs**
  - [Dark](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/d80b7c6b-5773-4fc5-9040-5d4e98eb83e8/files/1d17329d-e1a3-490a-a6ad-097e2ecd4825?filter=changed)
  - [Light](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/d80b7c6b-5773-4fc5-9040-5d4e98eb83e8/files/b7c2bf0c-9dec-4b07-96d4-ead85393c9d0?filter=changed)

2020-12-07 21:49 UTC, amalyah commented
Design has a primary border around the outside of the full component (not just top and bottom borders).

2020-12-07 21:50 UTC, amalyah commented
Do we allow for tertiary states of groupings in the code? (We do in design, so I was curious about the code.)

2020-12-07 21:53 UTC, amalyah commented
Hover state should be a background color adjustment like other components. (primary-dark for light theme and primary-light for dark theme.)

2020-12-07 22:09 UTC, amalyah requested changes

2020-12-07 22:09 UTC, amalyah commented on src/css/common/_theme--dark.css
> +  --treeHoverBackgroundColor: var(--globalAppHeader);
See general comments for hover edits

2020-12-07 22:09 UTC, amalyah commented on src/css/common/_theme--dark.css
> +  --treeSelectedBackgroundColor: var(--surfaceElements);
See general comments for selected edits

2020-12-07 22:09 UTC, amalyah commented on src/css/common/_theme--light.css
> +  --treeBackgroundColor: var(--inputBackground);
surface elements color

2020-12-07 22:09 UTC, amalyah commented on src/css/common/_theme--light.css
> +  --treeHoverBackgroundColor: var(--backgroundColor);
see general comments for hover states

2020-12-07 22:09 UTC, amalyah commented on src/css/common/_theme--light.css
> +  --treeSelectedBackgroundColor: var(--inputBackground);
surface element color
See general  comments for other selected state features

2020-12-07 22:09 UTC, amalyah commented on src/css/common/_theme--light.css
> +  --treeChildrenBackgroundColor: var(--inputBackground);
surface element color

2020-12-07 22:09 UTC, amalyah commented on src/css/components/tree.css
> +  box-shadow: inset 5px 0 var(--treeSelectedAccentColor);
More shadows for your judgment @carmenparks (keep or not? design has none, code has some)

2020-12-07 22:12 UTC, carmenparks commented on src/css/components/tree.css
> +  box-shadow: inset 5px 0 var(--treeSelectedAccentColor);
Let's remove all shadows.

2020-12-07 22:46 UTC, cskerbo approved these changes

2020-12-09 00:01 UTC, im-cr commented on src/components/rux-tree/rux-tree.js
>          color: var(--treeTextColor, rgb(255, 255, 255));
removed

2020-12-09 00:38 UTC, im-cr commented on src/css/common/_theme--light.css
> +  --treeChildrenBackgroundColor: var(--inputBackground);
updated

2020-12-09 10:17 UTC, im-cr commented on src/css/components/tree.css
> +  box-shadow: inset 5px 0 var(--treeSelectedAccentColor);
@amalyah @carmenparks this box shadow is used for creating the left border element when selected so it has to stay.

2020-12-09 10:19 UTC, im-cr commented on src/css/common/_theme--light.css
> +  --treeBackgroundColor: var(--inputBackground);
updated

2020-12-09 10:19 UTC, im-cr commented on src/css/common/_theme--dark.css
> +  --treeSelectedBackgroundColor: var(--surfaceElements);
updated

2020-12-09 10:20 UTC, im-cr commented on src/css/common/_theme--dark.css
> +  --treeHoverBackgroundColor: var(--globalAppHeader);
updated

2020-12-09 10:20 UTC, im-cr commented
@amalyah hover state wasn't represented in designs, has been added in from your notes above.

2020-12-09 19:14 UTC, amalyah commented
> @amalyah hover state wasn't represented in designs, has been added in from your notes above.

Sorry, it's built as an option in the filters, but it's not explicitly a symbol in the design files itself. I've attached an image to the Jira ticket to help for the desired  design state.

2020-12-09 19:14 UTC, amalyah requested changes
- Border design: Only selected rows should have the top and bottom primary-dark borders. For the primary items, they should have a bottom border of Background Color. If you want to see this clearer in the designs, I've attached a screenshot to the Jira ticket.

- Bug?: Not seeing a hover state over selected rows. (Which is okay if that's intentional)

- Hover: On hover, group items should change the caret to the same primary element font color as the text for now.

- Bug: When I open a group and  then hover another item, sometimes I see a bug where I see the correct hover state in the row I'm hovering over, but a hover background with incorrect  text colors on the previously opened folder. See the Jira ticket for screenshot.

2020-12-09 23:14 UTC, dmcalester commented
@im-cr @amalyah @carmenparks I don't think the hover color is working. Aesthetically it’s really heavy and technically for whatever reason there’s a stair step effect on hover that was difficult to see in the previous version. Recommend for the time being removing hover altogether as no design spec available and revisiting in a dot-one

2020-12-10 14:49 UTC, amalyah commented
> @im-cr @amalyah @carmenparks I don't think the hover color is working. Aesthetically it’s really heavy and technically for whatever reason there’s a stair step effect on hover that was difficult to see in the previous version. Recommend for the time being removing hover altogether as no design spec available and revisiting in a dot-one

Hi Duncan, I agree that hover states could stand another look and I agree that we should remove the stair step effect animation since that's feeling pretty awkward (meant to put in a comment, but forgot). However, it is in the design spec currently for both dark and light libraries. It is just currently a setting instead of a separate symbol. An example of that hover state in action was posted in the Jira ticket. Not sure if that affects your opinion on removing altogether from code or not, but I thought I'd state the correction.

2020-12-11 15:46 UTC, amalyah commented
New bug found: double selection occurs sometimes between group items and individual items. Screenshot attached to Jira ticket for posterity.

2020-12-11 16:17 UTC, dmcalester commented
> > @im-cr @amalyah @carmenparks I don't think the hover color is working. Aesthetically it’s really heavy and technically for whatever reason there’s a stair step effect on hover that was difficult to see in the previous version. Recommend for the time being removing hover altogether as no design spec available and revisiting in a dot-one
> 
> Hi @dmcalester , I agree that hover state designs should get another look and I agree that we should remove the stair step effect animation since that's feeling pretty awkward (meant to put in a comment, but forgot). However, the hover state is in the design spec currently for both dark and light libraries. It is just currently a setting instead of a separate symbol. An example of that hover state in action was posted in the Jira ticket. Not sure if that affects your opinion on removing altogether from code or not, but I thought I'd state the correction.

@amalyah @im-cr 
Understood. Let’s talk about this in standup because as-is it’s not ready for release.

2020-12-14 10:03 UTC, im-cr commented
@amalyah double select issue resolved. Primary expanded item border color updated.

2020-12-14 19:32 UTC, amalyah commented
> @amalyah double select issue resolved. Primary expanded item border color updated.

Looks like it's partially resolved. Still seeing the blue borders around some previously opened/closed folders. Screenshot on the Jira ticket.

Primary item border color should apply regardless of expanded/collapsed state and the blue dividing lines should be removed. Let me know if this would be easier to describe over a call.

2020-12-14 19:33 UTC, amalyah requested changes
See general comment

2020-12-14 22:18 UTC, im-cr commented
@amalyah unable to reproduce last bug, let's hop on a call and review to close out.

2020-12-15 17:09 UTC, dmcalester approved these changes

2020-12-15 17:15 UTC, amalyah approved these changes

2020-12-15 18:17 UTC, merged