V2:Astro 948 - Update Status Bar and Clock KM Color Styles
RocketCommunicationsInc/astro-components pull request #52
Opened 2020-12-07 18:59 UTC by im-cr

**Tickets**
  - https://rocketcom.atlassian.net/browse/ASTRO-948

**Changes** - commit: 
  - rux-global-status-bar.js
  - rux-clock.js
  - clock.css
  - theme--dark
  - theme--light

**Designs**
  - [Dark](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/b241d1e8-9a5c-4f69-a529-c85b87f50ab6/files/1d17329d-e1a3-490a-a6ad-097e2ecd4825?s=clock)
  - [Light](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/b241d1e8-9a5c-4f69-a529-c85b87f50ab6/files/b7c2bf0c-9dec-4b07-96d4-ead85393c9d0?s=clock)

2020-12-07 19:02 UTC, im-cr commented
@amalyah small color issue for the clock component in light theme. 

The Design reference for the clock in light theme has a BG color of #101923 and a border color #1b2d3e. Neither of these color values are represented in the KM color changes for theme--light.css but are present in the Dark theme. I've altered the color values for the light theme color to use #172635 (globalAppHeader). Please advise.

2020-12-07 22:35 UTC, amalyah requested changes

2020-12-07 22:35 UTC, amalyah commented on src/components/rux-global-status-bar/rux-global-status-bar.js
>          .app-meta h1 {
This may be being reserved for a later dev effort, but H1s got changed to 34 px, so that's what we're using for the GSB title as well in the designs.

2020-12-07 22:35 UTC, amalyah commented on src/components/rux-global-status-bar/rux-global-status-bar.js
> +          color: var(--inputBackground);
Is there a reason that this is inputBackground instead of default text from dark theme or something more semantic?

2020-12-07 22:35 UTC, amalyah commented on src/css/common/_theme--light.css
> +	--clockLabelColor: var(--defaultText);
So far we've only designed a version of the clock that would go on the GSB using dark theme colors.  @dmcalester and @carmenparks  Do we need a light theme version of the clock?

2020-12-07 22:39 UTC, im-cr commented on src/components/rux-global-status-bar/rux-global-status-bar.js
> +          color: var(--inputBackground);
@amalyah accounting for white text referenced on both dark and light design mocks. Seeing your comment below about only one version made for dark. This was not specifically noted previously.

2020-12-07 22:40 UTC, cskerbo approved these changes

2020-12-07 22:40 UTC, im-cr commented on src/components/rux-global-status-bar/rux-global-status-bar.js
>          .app-meta h1 {
@amalyah  will add to outstanding dev refactor list

2020-12-07 22:41 UTC, carmenparks commented on src/css/common/_theme--light.css
> +	--clockLabelColor: var(--defaultText);
@dmcalester correct me if I'm wrong, but since both the light and dark themes use the dark GSB - we only need the dark theme version of the clock.

2020-12-07 23:58 UTC, dmcalester commented on src/css/common/_theme--light.css
> +	--clockLabelColor: var(--defaultText);
@carmenparks correct. Though I have always wanted to see a proper light theme GSB, but that’s a topic for another day.

2020-12-08 19:57 UTC, im-cr commented on src/css/common/_theme--light.css
> +	--clockLabelColor: var(--defaultText);
@amalyah since there is no light clock, I've updated the light theme clock settings to match the same color palette as dark. some values are hard code in light theme variables. 

@dmcalester

2020-12-08 22:38 UTC, amalyah approved these changes
If Duncan's okay with hard coding the dark colors into the clock in the light theme, then that's fine with me.

2020-12-08 22:39 UTC, dmcalester commented
> If Duncan's okay with hard coding the dark colors into the clock in the light theme, then that's fine with me.

I am fine with it for this effort.

2020-12-08 23:28 UTC, merged