V2:Astro-950 - Table KM Style Updates
RocketCommunicationsInc/astro-components pull request #53
Opened 2020-12-09 12:35 UTC by im-cr

**Tickets**
  - https://rocketcom.atlassian.net/browse/ASTRO-950

**Changes** - commit: 
  - table.css
  - rux-table.stories.js
  - theme--dark
  - theme--light

**Designs**
  - [Dark](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/master/files/1d17329d-e1a3-490a-a6ad-097e2ecd4825?s=table)
  - [Light](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/master/files/b7c2bf0c-9dec-4b07-96d4-ead85393c9d0?s=table)

2020-12-09 12:39 UTC, im-cr commented
@dmcalester the ag-grid table styles are handled in the https://github.com/RocketCommunicationsInc/astro-ag-Grid/blob/master/src/css/astro-theme.scss repo. I've added overrides to the storybook for consistency on the ag-grid table.

I can migrate these updates over to that css file. Is that outside of the scope of this KM update as I am not familiar with where ag-grid lives as Sarah worked on ag-grid

2020-12-09 12:39 UTC, im-cr commented
@amalyah please ping me when you start reviewing this item.

2020-12-09 18:10 UTC, cskerbo approved these changes

2020-12-09 19:54 UTC, amalyah requested changes
I am confused about the Storybook example. Could we add a checkbox column so we  can select and deselect rows or let the user change the selection by clicking on the row? Right now it looks like three rows are selected, but that's not very clear without any other cue. Also not sure why 3 rows would be selected. (Feel free to tell me that this needs to be a different ticket.)

2020-12-09 19:54 UTC, amalyah commented on src/css/core/table.css
>    font-weight: 600;
We would like the Header font size to be H5 size (18px equivalent in rem) and regular font weight (not bold).

2020-12-09 19:54 UTC, amalyah commented on src/css/common/_theme--dark.css
> +  --tableHeaderAccentColor:  var(--primary);
What does this do?

2020-12-09 19:54 UTC, amalyah commented on src/css/common/_theme--dark.css
> +  --tableControlsBackgroundColor: var(--primary);
Are these controls and filters pieces in use somewhere?

2020-12-09 19:54 UTC, amalyah commented on src/css/common/_theme--dark.css
> +  --tableCellSelectedBorderColor: var(--backgroundColor);
After discussion with the other Designers, lets change hover/selected/etc. to a row by row basis instead of cell by cell. So selected would change the background color to background color and the row border to primary only.

2020-12-09 19:54 UTC, amalyah commented on src/css/common/_theme--light.css
> +  --tableCellSelectedBorderColor: var(--primary);
This can now be removed.

2020-12-09 19:54 UTC, amalyah commented on src/css/common/_theme--light.css
> +  --tableRowBorderColor: var(---backgroundColor);
Looks like another instance where the background color is being overridden somewhere. This should be a light grey  but it's appearing as a dark grey to me in the preview.

2020-12-09 20:52 UTC, dmcalester commented on src/css/common/_theme--dark.css
> +  --tableControlsBackgroundColor: var(--primary);
These are for the Astro approved, but not Astro authored ag Grid implementation.

2020-12-09 20:57 UTC, im-cr commented on src/css/core/table.css
>    font-weight: 600;
updated

2020-12-09 20:58 UTC, im-cr commented on src/css/common/_theme--dark.css
> +  --tableHeaderAccentColor:  var(--primary);
not currently in use in table.css or rux-table.js. Assuming similar to other components it was used for elements within table cell.

2020-12-09 22:04 UTC, im-cr commented on src/css/common/_theme--dark.css
> +  --tableControlsBackgroundColor: var(--primary);
not currently

2020-12-09 22:09 UTC, im-cr commented on src/css/common/_theme--light.css
> +  --tableRowBorderColor: var(---backgroundColor);
@amalyah can you provide screen? tableRowBorderColor is  #eaeef4 in light theme, correct? This is what I am currently seeing for row borders.

2020-12-09 22:16 UTC, im-cr commented on src/css/common/_theme--light.css
> +  --tableRowBorderColor: var(---backgroundColor);
@amalyah found it. updated

2020-12-10 00:25 UTC, im-cr commented on src/css/common/_theme--dark.css
> +  --tableCellSelectedBorderColor: var(--backgroundColor);
updated

2020-12-10 00:36 UTC, im-cr commented
@amalyah Added in a table with a control column for preview. https://deploy-preview-53--astro-components.netlify.app/?path=/story/components-table--html-controls-table. 

Lets confirm/approve visual consistency and any functional updates can be separated into another ticket and revisited since its outside of the KM Style update.

For the hover states on the control table I maintained the row hover states in the table library and matched the control styles. There is not currently a hover state displaying a default control button within a :hovered row. Additional clarity around selected row hover state will allow us to close out this item. 


@dmcalester @cskerbo

2020-12-10 00:37 UTC, im-cr commented
@dmcalester Please see general comments at the top about ag-grid table. Please advise. https://github.com/RocketCommunicationsInc/astro-components/pull/53#issuecomment-741745026

2020-12-10 15:19 UTC, amalyah requested changes
- HTML Table demo missing selected border color.
- HTML Controls Table demo not completed. Missing header checkbox. Checkbox does not affect selection styling. Made ticket to complete functional updates later:
https://rocketcom.atlassian.net/browse/ASTRO-1063
-ag-Grid Content: I don't understand the true column. It looks out of place in this demo. Was that accidentally added in?
- ag-Grid Selection: Are we able to show the full row selected on click instead of just the cell?
- ag-Grid Bug: When a cell in a row is selected, but another cell in the same row is hovered over, the text in the selected cell turns the wrong color.
- Primary color elements like the checkboxes are hard to see on hover. Updated [ASTRO-1030](https://rocketcom.atlassian.net/browse/ASTRO-1030) to look into improving hover state design for all components and not just trees.
- Hover state for selected row. This is a good question. This is part of the reason why adding a checkbox is helpful: to increase the visibility of what is selected vs. not in various states. @carmenparks thoughts for a quick fix? Updated [ASTRO-1030](https://rocketcom.atlassian.net/browse/ASTRO-1030) to look into this issue in more detail in the future as well.

2020-12-10 16:06 UTC, im-cr commented on src/css/core/table.css
>    font-weight: 600;
updated

2020-12-10 16:34 UTC, im-cr commented
@amalyah updates added. notes below. 

- selected border color resolved
- Functional control outside of KM update scope - ticket https://rocketcom.atlassian.net/browse/ASTRO-1063
- agGrid demo data display resolved
- agGrid select text color resolved
- 

**Remaining Issues** - 
- agGrid exists outside of astro components and has different functionality
- agGrid row select change (functional changes will need approval and updated in agGrid repo https://github.com/RocketCommunicationsInc/astro-ag-Grid)
- Table hover updates in progress (can we merge and circle back when designs have been updated?)

@dmcalester @cskerbo

2020-12-10 17:05 UTC, amalyah requested changes
- Hovers seem fine to me as is in our non-ag-Grid demos since they do match the current designs, but that seems to be a decision for @dmcalester / @carmenparks.
- Created ticket for ag-Grid row select: [ASTRO-1064](https://rocketcom.atlassian.net/browse/ASTRO-1064)
- Header font weight still not normal. (See inline comment)

2020-12-10 17:05 UTC, amalyah commented on src/css/core/table.css
> +  font-weight: 500;
I believe normal font-weight is 400. Could you change it to that (or remove the code if that's the default otherwise)?

2020-12-10 17:09 UTC, carmenparks approved these changes

2020-12-10 17:15 UTC, carmenparks commented
> * Hover state for selected row. This is a good question. This is part of the reason why adding a checkbox is helpful: to increase the visibility of what is selected vs. not in various states. @carmenparks thoughts for a quick fix? Updated [ASTRO-1030](https://rocketcom.atlassian.net/browse/ASTRO-1030) to look into this issue in more detail in the future as well.

Selected rows shouldn't have a hover state since they're already selected and don't have/need further functionality (same logic as selected buttons discussed a few days ago). 
I took a peek at ASTRO-1030 and saw it was directed around contrast/accessibility which I agree needs to be looked at in the future.

2020-12-10 17:22 UTC, im-cr commented on src/css/core/table.css
> +  font-weight: 500;
@amalyah yep it is was matching it to the typograhy.css setting. updated to 400.

adding this to a list we can review after pi. small deviations between css/design.

2020-12-10 18:20 UTC, amalyah requested changes
Looks good on the normal tables. Bold header text still on the ag-Grid version.

2020-12-10 19:14 UTC, im-cr commented
@amalyah @carmenparks removed hover state on selected. FW on agGrid updated.

2020-12-10 19:24 UTC, amalyah approved these changes

2020-12-10 19:59 UTC, merged