V2:Astro-1065 - Buttons KM Style Update
RocketCommunicationsInc/astro-components pull request #56
Opened 2020-12-10 20:29 UTC by im-cr

**Tickets**
  - https://rocketcom.atlassian.net/browse/ASTRO-1065

**Changes** - commit: 
  - button.css
  - rux-button.js
  - rux-icon.js
  - button.stories.js
  - theme--dark
  - theme-light 

**Designs**
  - [Dark](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/master/files/1d17329d-e1a3-490a-a6ad-097e2ecd4825?s=button)
  - [Light](https://app.abstract.com/projects/2d8cf270-0b93-11e8-89ff-61554354acb1/branches/master/files/b7c2bf0c-9dec-4b07-96d4-ead85393c9d0?s=button)

2020-12-10 22:04 UTC, amalyah requested changes

2020-12-10 22:04 UTC, amalyah commented on src/css/core/button.css
>    padding: 0 1.5rem;
0 1rem

2020-12-10 23:30 UTC, dmcalester commented on src/components/rux-button/rux-button.js
> +          border: 1px solid var(--buttonBorderColor);
@im-cr I would retain the border for the time being. There was a reason that I’m struggling to recall but possibilities.

2020-12-10 23:32 UTC, im-cr commented on src/css/components/icons.css
> +  color: var(--colorSecondary);
no leaving this alone in this pr but removed fallback, color updates addressing icon color are in buttons.css and rux-button. I was testing color issues. but leaving initial color value in this repo.

2020-12-10 23:41 UTC, im-cr commented on src/components/rux-button/rux-button.js
> +          border-color: var(--buttonHoverBorderColor);
@amalyah this is for the default buttons not outline button, there is no text color change from default to hover for the standard buttons.

2020-12-11 00:05 UTC, carmenparks commented on src/components/rux-button/rux-button.js
>            /* min-width: 2.875rem; */
> Looks like the large button's min width got lost at some point in the design files. What's the desired min width for Large Buttons @carmenparks ? (Once we have an answer, I'll create a design ticket as well.)

@amalyah the smallest button we have uses just an icon, so I would use that as reference to define the min width - which in the library is 48px.

2020-12-11 14:36 UTC, amalyah commented on src/components/rux-button/rux-button.js
> +          border-color: var(--buttonHoverBorderColor);
Whoops! I meant to find where the hover text is for the outline buttons, since that needs to change to hover color with the outline.

2020-12-11 14:39 UTC, amalyah commented on src/components/rux-button/rux-button.js
>            /* min-width: 2.875rem; */
Alrighty. Looks like we're updating all minimum button widths to 48 px equivalent rem (a nice even 3 I believe) @im-cr.  I'll make a ticket to do the fix in designs. Cortney, let me know if you would prefer for this change to be a separate  ticket for later since I don't think any external person will notice in the meantime.

2020-12-14 13:07 UTC, im-cr commented on src/components/rux-button/rux-button.js
> +          border-color: var(--buttonHoverBorderColor);
default outline text color:
line 94: color: var(--buttonOutlineTextColor);

hover outline text color:
line 126: color: var(--buttonOutlineTextColor);

matches design mock

2020-12-14 13:09 UTC, im-cr commented on src/components/rux-button/rux-button.js
>            padding: 0 1.5rem;
updated

2020-12-14 13:24 UTC, im-cr commented on src/components/rux-button/rux-button.js
> +          color="${this.outline ? 'var(--buttonOutlineTextColor)' : 'var(--buttonTextColor)'}"
Current css/js matches. Design. The icon color is static on both default and hover state for buttons in designs. Also svgs color state is handled differently. This should stay the same for now.

2020-12-14 13:25 UTC, im-cr commented on src/components/rux-button/rux-button.js
>            /* min-width: 2.875rem; */
@amalyah yea, lets push this to another ticket outside of KM updates.

2020-12-14 13:27 UTC, im-cr commented on src/css/core/button.css
>    padding: 0 1.5rem;
resolved

2020-12-14 13:27 UTC, im-cr commented on src/css/core/button.css
> -.rux-button:active:not([hover]):not([disabled]):not(.rux-button--outline) {
no. removed

2020-12-14 13:28 UTC, im-cr commented on src/css/common/_theme--light.css
>    --buttonOutlineTextColor: var(--primary);
resolved

2020-12-14 13:30 UTC, im-cr commented
@amalyah all updates should be consistent with design. Lets circle back on any svg color state issue outside of this merge as that is a design change. Any additional dev changes outside of KM updates should be added to additional dev/design tickets.

2020-12-14 19:39 UTC, amalyah commented on src/components/rux-button/rux-button.js
> +          border-color: var(--buttonHoverBorderColor);
Actually, design mock changes the text color on hover to primary light along with the outline color.

2020-12-14 19:43 UTC, amalyah commented on src/components/rux-button/rux-button.js
> +          color="${this.outline ? 'var(--buttonOutlineTextColor)' : 'var(--buttonTextColor)'}"
Unfortunately, this goes hand in hand with the outline button text color change on hover so that the icon does, in fact, continue to match the text color on hover.

2020-12-14 19:59 UTC, amalyah requested changes
1. For this PI, hover states of outline button need to have the hover color for both the outline border and the text/icons in the button as seen in the design files.
2.  Light theme still has a non-variable color listed for the outline hover background color.

I will make follow up tickets: 
- to change the min-width of the small and medium buttons to 3 rem as well.
- to make sure that the padding between icons and text in all buttons is 10 px
- change all icon sizes in buttons to match the text size (16x16px).

2020-12-14 19:59 UTC, amalyah commented on src/components/rux-button/rux-button.js
> +          color: var(--buttonOutlineTextColor);
As mentioned in previous comment, on hover, outline button text and any related icons colors need to change to the standard hover color for that theme to match the outline color of the button.

2020-12-14 19:59 UTC, amalyah commented on src/css/common/_theme--light.css
>    --buttonOutlineHoverTextColor: var(--primary);
Needs to be changed to primaryDark for A5 KM v1.1 changes.

2020-12-14 19:59 UTC, amalyah commented on src/css/common/_theme--light.css
>    --buttonOutlineHoverBackgroundColor: rgba(77, 172, 255, 0.1);
This needs to be changed to a variable.

2020-12-14 20:30 UTC, im-cr commented on src/components/rux-button/rux-button.js
> +          border-color: var(--buttonHoverBorderColor);
@amalyah think our wires are cross. I was responding to the initial comment. The border-color set is for the default button state not outline hover. The lines at 94 and 126 in source code is for outline default/hover state. I believe that currently matches the color values you mention for outline border and outline text matching. please confirm.

2020-12-14 21:02 UTC, amalyah commented on src/components/rux-button/rux-button.js
> +          color: var(--buttonOutlineTextColor);
@im-cr I figured it out. This line is missing the Hover portion of the variable name, so it's not using the right color.

2020-12-14 21:46 UTC, im-cr commented
@amalyah icon color hover updated

2020-12-15 16:21 UTC, amalyah approved these changes

2020-12-15 16:48 UTC, merged