V2:Astro-1054 - Global Color KM Update
RocketCommunicationsInc/astro-components pull request #57
Opened 2020-12-14 18:41 UTC by im-cr

**Tickets**
  - https://rocketcom.atlassian.net/browse/ASTRO-1054

**Changes** - commit: 
  - theme__dark
  - theme__light

**Related**
  - https://rocketcom.atlassian.net/browse/ASTRO-971

2020-12-14 18:41 UTC, im-cr commented
@amalyah please confirm correct color swap for   --fontInvertedBackgroundColor in dark/light theme.css files

2020-12-14 20:35 UTC, amalyah requested changes

2020-12-14 20:35 UTC, amalyah commented on src/css/common/_theme--dark.css
> +  --fontInvertedBackgroundColor: var(--inputBackground);
What are the inverted variables used for @im-cr?

2020-12-14 20:35 UTC, amalyah commented on src/css/common/_theme--light.css
> +  --fontInvertedBackgroundColor: var(--primary);
My suspicion is that this color will need to change, but I need to know where this color is used in order to suggest a different color.

2020-12-15 17:00 UTC, im-cr commented on src/css/common/_theme--dark.css
> +  --fontInvertedBackgroundColor: var(--inputBackground);
@amalyah They aren't used anywhere, just declared i the theme css files. Keeping place just in case for future proofing.

2020-12-15 17:00 UTC, im-cr commented on src/css/common/_theme--light.css
> +  --fontInvertedBackgroundColor: var(--primary);
Only used as declarations. Not actively being used in any css or component file.

2020-12-15 17:19 UTC, amalyah commented
I hate to delegate this out, but I think this question would be better directed at @carmenparks for visual design decision. 

> @amalyah please confirm correct color swap for --fontInvertedBackgroundColor in dark/light theme.css files

2020-12-15 17:23 UTC, amalyah requested changes
Suggest asking Carmen about what colors should be used for the invertedBackground colors.  Otherwise, I suggest either using primary and the background color for both or the white/black combo for both (by using global header color awkwardly in light theme) instead of a combination of the two.

2020-12-15 20:44 UTC, carmenparks commented
> @amalyah please confirm correct color swap for --fontInvertedBackgroundColor in dark/light theme.css files

@im-cr let's go with using the primary and background colors for both themes.

2020-12-15 20:57 UTC, amalyah approved these changes
Sounds good for now since we don't have an example of what it's used in.

2020-12-15 21:13 UTC, merged