Astro 1119 css icon implementation
RocketCommunicationsInc/astro-components pull request #76
Opened 2021-02-08 20:02 UTC by Cheshire89

clean up node files and restructure to work as true cli
create script to auto generate icons css file

2021-02-08 22:33 UTC, dmcalester commented
Hey Sasha,

In the preview deploy (https://deploy-preview-76--astro-components.netlify.app/?path=/story/components-icons-symbols--monitoring-icon-set) the `rux-icon` icons appear to be fuzzy now (and some SVG shifting) almost like a border property is being applied. Compared to the PR for ASTRO-1118 (https://deploy-preview-76--astro-components.netlify.app/?path=/story/components-icons-symbols--monitoring-icon-set) which are rendering w/o the border

2021-02-17 19:56 UTC, cskerbo approved these changes

2021-02-18 17:42 UTC, dmcalester commented on src/css/components/icons-list.css
> +                    -webkit-mask-size: cover;
Would it make sense here to put the universally applicable properties in to the `.rux-icon` class to reduce file size.

```
.rux-icon {
 -webkit-mask-size: cover;
mask-size: cover;
-webkit-mask-repeat: no-repeat;
mask-repeat: no-repeat;
}
```

2021-02-18 17:47 UTC, dmcalester commented on src/css/components/icons-list.css
> +                    -webkit-mask: url("/icons/astro.svg#check-box-outline-blank") no-repeat;
I’d be interested in your thoughts on putting the urls in CSS Custom Properties. 

`--iconCheckBoxOutlineBlank: url("/icons/astro.svg#check-box-outline-blank");`

and then:

```
-webkit-mask: var(--iconCheckBoxOutlineBlank);
mask: var(--iconCheckBoxOutlineBlank);
```

I’m not sold on the idea, just curious about your thoughts. I think we’d save a small amount of file space, but I don’t know if there’s much other benefit particularly as this file is generated

2021-02-18 17:49 UTC, dmcalester commented on src/css/components/icons-list.css
> +.rux-icon-check-box-outline-blank{
For the class names we generally follow a rough BEM style naming convention. Please add a double dash between `rux-icon` and its specific icon type. E.g.,

`rux-icon--check-box-outline-blank`

2021-02-18 17:50 UTC, dmcalester requested changes
Hey Sasha,

I have a couple of notes. I inadvertently put them in the generated CSS file, but they may have been more appropriate in the js. If you’d like me to move them let me know.

2021-02-18 19:09 UTC, Cheshire89 commented on src/css/components/icons-list.css
> +                    -webkit-mask: url("/icons/astro.svg#check-box-outline-blank") no-repeat;
@dmcalester  Icon list is already 6.5k lines long
creating variables and applying them will add additional 6.5k lines of code
from stand point of performance this will be an overkill

2021-02-18 19:30 UTC, Cheshire89 commented on src/css/components/icons-list.css
> +                    -webkit-mask-size: cover;
Agreed

2021-02-18 21:23 UTC, dmcalester approved these changes

2021-02-18 23:32 UTC, merged