Astro 1256 select update
RocketCommunicationsInc/astro-components pull request #77
Opened 2021-02-12 22:14 UTC by Cheshire89

renamed dropdown to select
update select styling
removed redundant variables

2021-02-15 17:25 UTC, cskerbo reviewed
@dmcalester Is there a desire or need to update the Readme and various links to reference select instead of drop-down?

![Screen Shot 2021-02-15 at 9 22 57 AM](https://user-images.githubusercontent.com/54558554/107977275-b0036e80-6f6f-11eb-87c0-b30665dc2c49.png)

2021-02-15 19:29 UTC, amalyah commented
@Cheshire89 Could you add the link to the relevant Jira ticket in the description of this branch? Helps me track time better.

2021-02-16 16:10 UTC, amalyah requested changes
- Bottom of the Select menu does not need to have the sharp bottom edges when the field is not expanded. Could we return the radii to the same as the top corners?
- In general, is it possible to use color variables instead of color declarations throughout the CSS files?

2021-02-16 16:41 UTC, dmcalester commented on static/css/astro.core.css
> +  color: rgb(8,12,17);
@amalyah `astro.core.css`, `astro.css`, `astro.core.min.css` and `astro.min.css` are all compiled from the separate CSS files so will resolve with fixes above.

2021-02-16 16:42 UTC, dmcalester commented
> @dmcalester Is there a desire or need to update the Readme and various links to reference select instead of drop-down?
> 
> ![Screen Shot 2021-02-15 at 9 22 57 AM](https://user-images.githubusercontent.com/54558554/107977275-b0036e80-6f6f-11eb-87c0-b30665dc2c49.png)


Yes please.

2021-02-16 16:45 UTC, dmcalester commented on src/css/documentation/select-menu-README.md
> +- [Astro UXDS: Select](https://www.astrouxds.com/ui-components/drop-down)
Please update URL to https://astrouxds.com/components/select/

2021-02-16 17:07 UTC, dmcalester commented
**Chrome Fixes**
In Chrome on hover both the disabled and enabled state do a 1px shift on hover after initial load. Subsequent hover events are fine. In the disabled state the cursor flickers between the `not-allowed` and and `pointer` cursor. It appears the `not-allowed` occurs when hovering over the border of the `select` menu.

https://user-images.githubusercontent.com/60529018/108096836-49955380-7036-11eb-8ccb-bf7be9d83225.mov

**Safari/Firefox Fixes**
In both Firefox and Safari the disabled select state is accepting mouse enter state and changing the cursor to pointer and accepting click event swapping the background arrow. 

https://user-images.githubusercontent.com/60529018/108096201-8c0a6080-7035-11eb-8eea-b0586a9ae812.mov

- Please disable pointer cursor and/or use the `not-allowed` cursor.
- Please disable the arrow swap when clicking on the disabled select input

Also please target the `next` branch for merging. Typically planned fixed target `next` and hot fixes will target `master`. Thank you.

2021-02-16 17:10 UTC, dmcalester requested changes
Thanks Sasha,

Left a few comments for some visual/interaction fixes. Also please target the `next` branch.

2021-02-16 18:10 UTC, Cheshire89 commented on src/css/common/_theme--dark.css
> +  --inputBorderColorAlt: rgb(8, 12, 17);
this line is creating a color variable ... its just not referencing one as other variables do

2021-02-17 17:17 UTC, amalyah requested changes
Few small comments for color consistency. If it's controlled by us in any way, the pop up menu appears off horizontally from the control when I don't think it was doing that before.

2021-02-17 17:17 UTC, amalyah commented on src/css/common/_theme--dark.css
> +  --inputDark: rgb(8,12,17);
Other color variables are using hex values. Could you do the same here for consistency?

2021-02-17 17:17 UTC, amalyah commented on src/css/common/_theme--dark.css
> +  --inputBorderColorDisabled: rgb(41, 42, 45);
Hex code please.

2021-02-17 17:17 UTC, amalyah commented on src/css/common/_theme--light.css
> +  --inputDark: rgb(8,12,17);
Hex code please

2021-02-17 17:17 UTC, amalyah commented on src/css/common/_theme--light.css
> +  --inputBorderColorDisabled: rgb(41, 42, 45);
Hex code please

2021-02-17 19:23 UTC, amalyah approved these changes

2021-02-17 19:33 UTC, cskerbo approved these changes

2021-02-18 22:49 UTC, dmcalester commented on static/css/astro.core.css
> +  background-image: var(--select-active-caret);
Minor, but stylistically we use Hungarian notation for CSS Custom Properties to differentiate from class names.

2021-02-18 22:55 UTC, dmcalester requested changes
One minor code update and then a visual glitch in Chrome is present.

2021-02-23 18:33 UTC, dmcalester approved these changes
I’m still seeing the weird shift in Chrome, but only when refreshing the page and only when in the full storybook ui. When in an external it seems fine. Approving for now with a lien to keep an eye out for it.

2021-02-24 17:40 UTC, merged