Astro 1120 update icons
RocketCommunicationsInc/astro-components pull request #80
Opened 2021-02-17 20:42 UTC by Cheshire89

depends on ASTO-1119 being merged

updates icon list with its css icons counterpart

2021-02-18 15:33 UTC, amalyah requested changes
- Do we need to credit where we got the new icons in the readme text?
- Need to remove the To Do note from the 4.0 revision history in the readme.
- For the icon names that are too long, could we do a tooltip with the full name so that people know how to refer to them in conversation using just the Storybook page? (This is something I suspect that I'll need myself.)
- The Progress Icon example seems broken now (latest version of Chrome).
- Antenna icons appear to be broken with lines no longer  in the right places.
- Some of the new icons appear to just be filled in shapes like squares, circles, or triangles. I suspect that's not what they're supposed to look like.
- Looks like some of the icon names have typos in them or are missing the first letter like  "otate-right"
- Satellite icons are missing their satellite body shape.
- Solar icon is on there twice
- X in a circle icon (close-large) does not have an equivalent in the new icons. Is this intentional @dmcalester ? (Fine if it is. Just wanted  to  check.)
- Timeline icon  appears to be missing
- I see a zoom-out-map icon, but is there also a zoom-in-map-icon? (Looking to find the replacement for the old collapse icon)

2021-02-18 16:24 UTC, dmcalester commented on src/components/rux-monitoring-icon/rux-monitoring-icon.js
>          fill: var(--colorOff, rgb(158, 167, 173));
@Cheshire89 actually in this instance we should remove the fallback color entirely.

2021-02-18 16:48 UTC, dmcalester commented on bin/astro-icon-export/index.js
> +    // TODO: create cleaner way removeing unnecessar wrapping groups
> Do we need to credit where we got the new icons in the readme text?
Yes

> For the icon names that are too long, could we do a tooltip with the full name so that people know how to refer to them in conversation using just the Storybook page? (This is something I suspect that I'll need myself.)

There is a title tag that I see on hover.  It does have the standard browser delay.

> The Progress Icon example seems broken now (latest version of Chrome).

@Cheshire89 I think we’ll have to extract this from the existing svg library and re-implement.

> Antenna icons appear to be broken with lines no longer in the right places.
> Some of the new icons appear to just be filled in shapes like squares, circles, or triangles. I suspect that's not what they're supposed to look like.
> Looks like some of the icon names have typos in them or are missing the first letter like "otate-right"
> Satellite icons are missing their satellite body shape.
> Timeline icon appears to be missing
> I see a zoom-out-map icon, but is there also a zoom-in-map-icon? (Looking to find the replacement for the old collapse icon)

I’m going to move these in to a Jira ticket https://rocketcom.atlassian.net/browse/ASTRO-1261

> X in a circle icon (close-large) does not have an equivalent in the new icons. Is this intentional @dmcalester ? (Fine if it is. Just wanted to check.)

There is a request for various icons encapsulated by a circle. I think the more prudent action here might be a new icon button type that applies a circle outline to the icon rather than adding circle outlines to each or a subset of icons.

2021-02-18 17:14 UTC, dmcalester commented on bin/astro-icon-export/index.js
> +    // TODO: create cleaner way removeing unnecessar wrapping groups
> Leftover To Do text probably shouldn't go live. If it does, then we should fix the typos.

I’ll defer to @cskerbo as there are many schools of thought here.

2021-02-18 17:27 UTC, dmcalester reviewed
Sasha of the call outs by Amalya the only ones I’d say blocking approval that fall solely on the code side are

- Adding a link to Material icons License (https://github.com/google/material-design-icons/blob/master/LICENSE) in our README
- The rest are a conversation with Ty  and/or an updated Sketch file with fixes

2021-02-18 22:35 UTC, cskerbo commented on bin/astro-icon-export/index.js
> +    // TODO: create cleaner way removeing unnecessar wrapping groups
@amalyah @dmcalester @Cheshire89 My preference is:

- If the TODO is still valid and still needs to be done, I'd prefer to correct the typos and keep it in the code. It does help Devs who  track the TODOs to manage future tasks. It can also be beneficial to users of open source code to understand future changes (and maybe, just maybe, someone out there will do it for us and submit a PR!).

- If the TODO has already been completed - definitely remove.

2021-02-18 23:04 UTC, dmcalester approved these changes
I believe most of the outstanding icon issues are related to art files not code related issues and if they are code related issues they can be addressed outside the core thrust of this ticket.

There are some knock-on changes that I’ll create tickets for

2021-02-19 01:18 UTC, cskerbo approved these changes

2021-02-22 19:32 UTC, amalyah requested changes
Icon questions will not hold up approval, but typos will.

- Is there a reason that thumb-down and thumb-down-alt appear to be the same icon?
- Is there a difference between the stay-current icons and the stay-primary icons? (I don't see one and don't understand why we need both then)
- otate-right icon appears to be missing
- Is having both access-alarm an access-alarms on purpose or an accident we should clean up?

2021-02-22 19:32 UTC, amalyah commented on bin/astro-icon-export/index.js
> +    // TODO: create cleaner way removing unnecessar wrapping groups
"create cleaner way **of** removing **unnecessary** wrapping groups"

2021-02-22 19:32 UTC, amalyah commented on src/components/rux-icon/README.md
> +Material icons License (https://github.com/google/material-design-icons/blob/master/LICENSE)
Material design icons (Material by itself may not be enough context)

Also it feels weird that this license link is in the Astro 4 migration section of the readme. I would have expected to see this up with the latest version of the notes.

2021-02-22 19:32 UTC, amalyah commented on stories/rux-icons-and-symbols.stories.js
> +  const colorKnob = select('Color', colors, '#4dacff');
Would it make sense to use the color variable Primary here instead of the hex code?

2021-02-22 23:59 UTC, dmcalester commented
> * Is there a reason that thumb-down and thumb-down-alt appear to be the same icon?
> * Is there a difference between the stay-current icons and the stay-primary icons? (I don't see one and don't understand why we need both then)
> * Is having both access-alarm an access-alarms on purpose or an accident we should clean up?
Another Google thing. For v1 we should keep all intact. For v2 a sweep for redundant icons and icons immaterial to our use case can be excised. Try as I might, I cannot see the use case for a slice of pizza.


> * otate-right icon appears to be missing
Added to comment on Ticket https://rocketcom.atlassian.net/browse/ASTRO-1115

2021-02-23 17:23 UTC, Cheshire89 commented on src/components/rux-icon/README.md
> +Material icons License (https://github.com/google/material-design-icons/blob/master/LICENSE)
@amalyah 
Should this be under the `## Revision History` ? 

- Extended icon set with Google material design icons. Material icons License (https://github.com/google/material-design-icons/blob/master/LICENSE)

2021-02-23 17:26 UTC, Cheshire89 commented on bin/astro-icon-export/index.js
> +    // TODO: create cleaner way removing unnecessar wrapping groups
Just note for future (not sure if story book does it) 
Most of the frame works remove comments during build process. However, i'm not aware how build process works for this project

2021-02-23 22:09 UTC, amalyah commented on src/components/rux-icon/README.md
> +Material icons License (https://github.com/google/material-design-icons/blob/master/LICENSE)
Good question.  @dmcalester Would that location make  sense for the Material Design icons license?

2021-02-23 22:14 UTC, dmcalester commented on src/components/rux-icon/README.md
> +Material icons License (https://github.com/google/material-design-icons/blob/master/LICENSE)
It’s not required as long as it’s referenced somewhere in the README. I have no opposition to having it in both places but Revision History would be secondary to a permanent location.

2021-02-23 22:23 UTC, amalyah requested changes
Small changes and then approved

2021-02-23 22:23 UTC, amalyah commented on src/components/rux-icon/README.md
> +- Extended icon set with Google material design icons. Material icons License (https://github.com/google/material-design-icons/blob/master/LICENSE)
Extended icon set with Google Material Design icons. License: https://github.com/google/material-design-icons/blob/master/LICENSE

2021-02-23 22:23 UTC, amalyah commented on stories/rux-icons-and-symbols.stories.js
> +  const colorKnob = select('Color', colors, '#4dacff');
Question is still relevant: Would it make sense to use the color variable Primary here instead of the hex code?

2021-02-23 22:27 UTC, amalyah commented on src/components/rux-icon/README.md
> +Material icons License (https://github.com/google/material-design-icons/blob/master/LICENSE)
Makes sense to me to move it above revision information  then.

2021-02-25 15:21 UTC, Design-Kat commented on static/css/astro.css
>    mask: url("/icons/astro.svg#otate-right") no-repeat;
Shouldn't this be rotate instead of otate?

2021-02-25 15:25 UTC, Design-Kat requested changes
It looks like Amalya had some suggestions that are still relevant, and if we are correcting the other svg names, could we fix "rotate" as well, please, to be consistent.

2021-03-03 16:15 UTC, Cheshire89 commented
Regenerated the icon list based on the new icon sketch file. From my review it fixed a lot of typos (can't tell for all of them but most). Also it fixed an issue of developer having to go in and fix "blue square" icons manually

2021-03-03 21:57 UTC, amalyah requested changes
- The only icon name typos left are the ones that are still in the design files since they are not completed yet. (See relevant [Abstract Branch](https://share.goabstract.com/3d72f04e-1af6-4dd8-8d1f-1e5a7b216727) for comments regarding remaining design file issues.)
- Still pending one grammar fix that was mentioned in the last review.

2021-03-03 21:57 UTC, amalyah commented on src/components/rux-icon/README.md
>  - Replaced the DOM manipulation library for loading icons in favor of an HTML5 template TODO: add support for template outside of WebComponents when browser’s support shadowDOM piercing
@cskerbo In this case, the TODO is in the text of the revision notes. Should that TODO be moved to a comment? It's in an informal grammar format, so it looks a little odd if it's meant to be left in.

2021-03-03 21:57 UTC, amalyah commented on src/components/rux-icon/README.md
> +- Extended icon set with Google material design icons. Material icons License (https://github.com/google/material-design-icons/blob/master/LICENSE)
Still relevant: Change text to "Extended icon set with Google Material Design icons. License: https://github.com/google/material-design-icons/blob/master/LICENSE" for proper capitalization of proper nouns.

2021-03-10 18:05 UTC, merged