Astro 1211 radio
RocketCommunicationsInc/astro-components pull request #86
Opened 2021-02-24 16:55 UTC by Cheshire89

adjust radio button sizing and fix hover behavior
PR includes Duncans production fixes

2021-02-24 21:03 UTC, dmcalester requested changes
Two required changes and a couple of notes
- Update the hard coded width property with the var (inline comment)
- There are merge conflicts in the compiled CSS

There is a discrepancy in the size from design. Sketch library is showing 16px height/width, but **don’t change** I want to understand why the design change.

2021-02-25 16:40 UTC, amalyah commented
Could you add a link to the relevant ticket in the description?

2021-02-25 16:56 UTC, amalyah approved these changes
Side Note: The Radio buttons readme page references the "Toggle and Push Buttons" UXDS page. We should update the link to separate the two topics and then change Toggle to Switch.

2021-02-25 16:56 UTC, amalyah commented on src/css/common/__variables.css
> +  --controlOptionSize: 1.125rem; /* 18px */
The latest version of the PI branch has the radio buttons as 18x18. @dmcalester, the link you have there is not the source for these change requests. That is an incomplete spike for structure changes to the symbol.

2021-02-25 16:56 UTC, amalyah commented on src/css/core/control.css
> +  letter-spacing: 0.5px;
The letter-spacing is not specific to these controls. That letter spacing should be true for all body-sized text.

2021-02-25 16:56 UTC, amalyah commented on static/css/astro.core.css
> +  letter-spacing: 0.5px;
This letter-spacing is true for any body-sized font.

2021-02-25 20:32 UTC, Cheshire89 commented on src/css/common/__variables.css
> +  --controlOptionSize: 1.125rem; /* 18px */
@dmcalester there was merge conflicts with minified astro.core and astro css files which might have caused it

2021-02-26 23:38 UTC, cskerbo approved these changes
No changes from me, but please be sure to include the link to the relevant ticket upon initial creation of future PRs. 

Thanks for your hard work!

https://rocketcom.atlassian.net/browse/ASTRO-1211

2021-03-03 16:08 UTC, dmcalester approved these changes

2021-03-03 16:40 UTC, merged