Astro 1160 checkbox
RocketCommunicationsInc/astro-components pull request #87
Opened 2021-02-25 18:45 UTC by Cheshire89

update styling for astro checkbox
update checkbox page to checkbox group layout

2021-03-02 17:01 UTC, dmcalester commented on static/css/astro.core.css
> +  transform: rotate(0deg);
What does `rotate(0deg)` accomplish here?

2021-03-02 17:03 UTC, dmcalester commented on src/css/core/checkbox.css
> +  transform: rotate(0deg);
What does `rotate(0deg)` accomplish here?

2021-03-02 17:09 UTC, dmcalester commented on src/css/core/checkbox.css
> +  left: 4px;
please change this to 3px 

left: 3px;
<img width="545" alt="Screen Shot 2021-03-02 at 9 06 50 AM" src="https://user-images.githubusercontent.com/60529018/109686248-f42d6c00-7b36-11eb-92ef-763e4d1f18b8.png">

left: 4px;
<img width="526" alt="Screen Shot 2021-03-02 at 9 06 41 AM" src="https://user-images.githubusercontent.com/60529018/109686254-f55e9900-7b36-11eb-8304-cca261022af1.png">

2021-03-02 17:10 UTC, dmcalester requested changes
One minor change.

2021-03-03 16:07 UTC, dmcalester approved these changes

2021-03-03 19:56 UTC, amalyah commented
Could you update the description to have the Jira link that covers checkboxes instead of radio buttons?
https://rocketcom.atlassian.net/browse/ASTRO-1160

2021-03-03 20:14 UTC, amalyah requested changes
- See comments.
- Also the indeterminate dash part of the checkbox does not appear to be horizontally centered when viewed in Chrome.
- Still not seeing a grouped checkbox sample. Has this feature been cut from the PI?

2021-03-03 20:14 UTC, amalyah commented on src/css/core/checkbox.css
> +**  Added Custom CSS Properties to support light/dark theming
Missing dashes for bullet points in comment text (if it matters).

2021-03-03 20:14 UTC, amalyah commented on src/css/core/checkbox.css
> +  /* DEBUG */
Does this debug code that is  commented out be removed on publishing? If not, we may want to consider deleting this.

2021-03-03 20:14 UTC, amalyah commented on src/css/core/checkbox.css
> +  letter-spacing: 0.5px;
Does this need to be controlled here? This is the same letter spacing for any other Body 1 text.

2021-03-03 20:14 UTC, amalyah commented on src/css/core/checkbox.css
> +  height: 6px;
What part of the design do these properties correspond to?

2021-03-03 20:14 UTC, amalyah commented on stories/rux-form-elements.stories.js
> +    <div style="padding: 10vh 5vw; display: flex; justify-content: center;" id="hey">
Is there a reason to call this id "hey"?

2021-03-04 05:45 UTC, Cheshire89 commented on src/css/core/checkbox.css
> +  height: 6px;
This is check mark

2021-03-04 05:48 UTC, Cheshire89 commented on src/css/core/checkbox.css
> +  letter-spacing: 0.5px;
Not necessarily. However when checking global styles I could not find this property being set globally. Therefore I've resorted to setting it specifically on this element

2021-03-04 05:49 UTC, Cheshire89 commented on src/css/core/checkbox.css
> +  /* DEBUG */
Agreed. Generally a bad practice keeping debug code around

2021-03-04 05:50 UTC, Cheshire89 commented on src/css/core/checkbox.css
> +**  Added Custom CSS Properties to support light/dark theming
It doesn't but I'll add them for appearance consistency

2021-03-04 05:52 UTC, Cheshire89 commented on stories/rux-form-elements.stories.js
> +    <div style="padding: 10vh 5vw; display: flex; justify-content: center;" id="hey">
my bad testing code

2021-03-04 14:49 UTC, amalyah commented on src/css/core/checkbox.css
> +  height: 6px;
Thanks!

2021-03-04 14:52 UTC, amalyah commented on src/css/core/checkbox.css
> +  letter-spacing: 0.5px;
@dmcalester Do you know where/if the letter spacing is being set for Body 1 text throughout the CSS?

2021-03-04 15:00 UTC, amalyah requested changes
1. Is this PR for checkboxes only or also for Radio Buttons and other edits?
Checkbox Jira link that is missing from the description (please add it): https://rocketcom.atlassian.net/browse/ASTRO-11601. 
2. Still not seeing a grouped checkbox sample. Has this feature been cut from the PI on the Storybook side?

2021-03-04 15:00 UTC, amalyah commented on src/css/core/checkbox.css
> +.rux-checkbox--indeterminate input[type="checkbox"]:checked + label::after{
The indeterminate state dash in the middle of the square is not centered horizontally when viewing in Chrome.

2021-03-04 17:30 UTC, Cheshire89 commented on src/css/core/checkbox.css
> +.rux-checkbox--indeterminate input[type="checkbox"]:checked + label::after{
My apologies. Once fix broke this one

2021-03-04 17:33 UTC, Cheshire89 commented on src/css/core/checkbox.css
> +  letter-spacing: 0.5px;
normally global styles like those are either set via `body` or `*`

2021-03-04 19:15 UTC, Cheshire89 commented on src/css/core/checkbox.css
> +.rux-checkbox--indeterminate input[type="checkbox"]:checked + label::after{
The grouped checkbox sample is not feasible due to limitations of storybook and lit-elements working together. I've talked to @dmcalester before dropping attempts of trying to create that. 

storybook version update that is planned after PI release could solve some of those issues but i'm not 100% sure

2021-03-05 15:51 UTC, Cheshire89 commented
Use react (for display only) to build checkbox group integration on forms -> checkbox page
https://rocketcom.atlassian.net/browse/ASTRO-1272

2021-03-09 00:23 UTC, cskerbo approved these changes

2021-03-10 15:26 UTC, amalyah approved these changes
Looks good. Is there a reason that some pages have a Revision History section but not others? (like this one)

2021-03-10 16:49 UTC, merged