Astro 1204 sentence case
RocketCommunicationsInc/astro-components pull request #90
Opened 2021-03-04 18:06 UTC by Cheshire89

https://rocketcom.atlassian.net/browse/ASTRO-1204

Applied sentence case to following attributes

placeholder
label
select list items if applicable

2021-03-04 18:35 UTC, dmcalester approved these changes

2021-03-05 20:56 UTC, amalyah requested changes
- Need to add in sentence case changes to the rest of the components  as well (re: conversation with Duncan)
- Push button in the working  sample needs to have its label updated.
- The All Push Button Variants page needs to be updated as well.
- The All Slider Variants page needs to be updated.

2021-03-05 20:56 UTC, amalyah commented on stories/rux-form-elements.stories.js
>            <optgroup label="Group One">
This label may have to be sentence cased for consistency. Same with Group Two.

2021-03-05 20:56 UTC, amalyah commented on stories/rux-form-elements.stories.js
>            <optgroup label="Group One">
Sentence case the label for consistency. Same for Group Two.

2021-03-09 18:03 UTC, cskerbo approved these changes

2021-03-11 16:21 UTC, amalyah requested changes
Only small comments.
- 'Min', 'Middle', 'Max' in Sliders need to have capitalized first letters.
- Monitoring Icon has a proper noun that needs to stay capitalized.

Sub label > Sub-label change is a Nice to Have, not required for approval.

2021-03-11 16:21 UTC, amalyah commented on src/components/rux-monitoring-icon/README.md
> + label="Altitude for satellite x"
In this example, I suspect that Satellite X is the name of the satellite and would need to be capitalized as a proper noun.

2021-03-11 16:21 UTC, amalyah commented on src/components/rux-monitoring-icon/README.md
> +  sublabel="Sub label"
Sub-label

2021-03-11 16:21 UTC, amalyah commented on src/components/rux-monitoring-icon/README.md
> +  sublabel="Sub label"
Sub-label

2021-03-11 16:21 UTC, amalyah commented on stories/rux-icons-and-symbols.stories.js
> +          sublabel="Sub label"
Sub-label

2021-03-11 16:21 UTC, amalyah commented on stories/rux-icons-and-symbols.stories.js
> +          sublabel="Sub label"
Sub-label

2021-03-11 16:21 UTC, amalyah commented on stories/rux-icons-and-symbols.stories.js
> +          sublabel="Sub label"
Sub-label

2021-03-11 16:21 UTC, amalyah commented on stories/rux-icons-and-symbols.stories.js
> +          sublabel="Sub label"
Sub-label

2021-03-11 16:21 UTC, amalyah commented on stories/rux-icons-and-symbols.stories.js
> +          sublabel="Sub label"
Sub-label

2021-03-11 16:21 UTC, amalyah commented on stories/rux-slider.stories.js
> +  const axisLabelsKnob = array('Axis labels', ['min', 'middle', 'max']);
'Min', 'Middle', 'Max'

2021-03-11 16:21 UTC, amalyah commented on stories/rux-slider.stories.js
>    const axisLabels4 = ['min', 'middle', 'max'];
'Min', 'Middle', 'Max'

2021-03-18 15:22 UTC, dmcalester commented
@Cheshire89 I think this can be merged?

2021-03-19 22:18 UTC, amalyah requested changes
Only change request: There is another section of the segmented button readme file further down that says Segment in labels that need to be lower cased.

Other things look great!

2021-03-22 20:30 UTC, merged