ASTRO-1205 Added help class to form fields; Added help examles
RocketCommunicationsInc/astro-components pull request #94
Opened 2021-03-09 20:02 UTC by nortonprojects

https://rocketcom.atlassian.net/browse/ASTRO-1205

In the example (https://astro-components.netlify.app/?path=/story/components-form-elements--input-fields) adding the help text to one element makes the rest of them out of line. The forms documentation (https://astrouxds.com/patterns/forms-and-validation/) specifies a 38px bottom spacing from the input, which would leave space for the help text. Should that spacing be added to all form fields regardless of whether or not there's help text?

2021-03-10 15:20 UTC, amalyah reviewed
@dmcalester I see in the ticket description that you changed the scope so that Help Text is only tied to input fields. Ultimately, we will need to be able to use help text with all form elements. Have you created a new ticket to cover that scope or is there another plan?

2021-03-10 15:20 UTC, amalyah commented on src/css/core/input.css
> +  font-size: 0.875rem;
If we can, it would be great to have these properties linked back to a generic "Body 2" size since we us this  font-size, family, weight, and spacing combo elsewhere as well.

2021-03-10 15:20 UTC, amalyah commented on src/css/documentation/input-fields-README.md
> +  <label for="input__text">Text Input Label</label>
Text Input Label > Text input label
(changing everything to sentence case)

2021-03-10 15:20 UTC, amalyah commented on src/css/documentation/input-fields-README.md
> +  <input id="input__text" class="rux-input" type="text" required placeholder="Text Input">
Text Input > Text input

2021-03-10 15:20 UTC, amalyah commented on src/css/documentation/input-fields-README.md
> +  <span class="help">Help Text</span>
Help Text > Help text

2021-03-10 15:20 UTC, amalyah commented on stories/rux-form-elements.stories.js
> +          <label for="input__text">Text Input</label>
Text Input > Text input

2021-03-10 15:20 UTC, amalyah commented on stories/rux-form-elements.stories.js
> +          <input id="input__text" class="rux-input" type="text" placeholder="Text Input" />
Text Input > Text input

2021-03-10 15:20 UTC, amalyah commented on stories/rux-form-elements.stories.js
> +          <span class="help">Help Text</span>
Help Text > Help text

2021-03-12 14:05 UTC, Cheshire89 requested changes
Small change for help text class name.

2021-03-12 14:05 UTC, Cheshire89 commented on src/css/core/input.css
> +.rux-form-field .help {
Since help text is an extension of form field element, shouldn't .help  be .input__help ?

2021-03-15 17:48 UTC, cskerbo commented
@nortonprojects Will review after you commit requested changes. Are you waiting on any answers before proceeding?

2021-03-17 16:08 UTC, amalyah requested changes
Some sentence case text changes for the new content. 

Would it be possible to show an example of how we'd suggest inputs align with other inputs that have help text in the story without building it into the component? If yes, would suggest re-aligning third and fourth row inputs to match height of the last two fields in the first column.

2021-03-18 21:58 UTC, cskerbo approved these changes

2021-03-22 21:18 UTC, Cheshire89 approved these changes

2021-03-23 14:53 UTC, dmcalester commented
@nortonprojects does this need a re-review?

2021-03-23 16:33 UTC, nortonprojects commented on stories/rux-form-elements.stories.js
> +        display: grid;
@Cheshire89 This conflicts with the changes you made in 1208, not sure which you want to keep

2021-03-24 16:21 UTC, Cheshire89 commented on stories/rux-form-elements.stories.js
> +        display: grid;
@nortonprojects  I'd keep mine just because media queries stack those inputs a tad better on the smaller screen sizes than grid you have

2021-03-24 17:31 UTC, Cheshire89 approved these changes

2021-03-24 18:23 UTC, amalyah approved these changes

2021-03-24 18:32 UTC, merged