Astro 1210 text input
RocketCommunicationsInc/astro-components pull request #98
Opened 2021-03-15 17:28 UTC by Cheshire89

https://rocketcom.atlassian.net/browse/ASTRO-1210
light styling update for text inputs

2021-03-15 20:26 UTC, dmcalester approved these changes

2021-03-15 20:41 UTC, cskerbo approved these changes

2021-03-16 20:30 UTC, Design-Kat commented on src/css/core/input.css
>    border-radius: 3px;
Unless there is a separate ticket for text-areas, the border and font changes should be reflected in text area as well. I'm still verifying the border- it appears it was changed and I want to confirm as I believe it was originally designed to match the buttons, will update when I've got the confirmation.

2021-03-16 20:40 UTC, Design-Kat commented on src/css/core/input.css
>    border-radius: 3px;
@Cheshire89 Confirmed with Ty that it actually should be 3px border radius- I will put in a change for the sketch file for this.

2021-03-16 20:40 UTC, Design-Kat commented on src/css/core/input.css
> +  border-radius: 4px;
@Cheshire89 Confirmed with Ty that it actually should be 3px border radius- I will put in a change for the sketch file for this.

2021-03-16 20:40 UTC, Design-Kat commented on static/css/astro.core.css
> +  border-radius: 4px;
@Cheshire89 Confirmed with Ty that it actually should be 3px border radius- I will put in a change for the sketch file for this.

2021-03-16 20:44 UTC, Design-Kat requested changes
So, 2 things: 1) It seems that the sketch file has the input's border radius changed to 4px, I have confirmed with Ty that it should match the 3px border radius of buttons. 2) Any changes made to text inputs should probably matched on Text areas (I can't think of a reason why they wouldn't be, @amalyah @dmcalester could you confirm please? There's no special reason I'm not thinking of, is there?)

2021-03-17 18:55 UTC, Design-Kat approved these changes

2021-03-18 20:11 UTC, merged